from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

from scripts.action_precision_multitimeframe_decomposition import (
    _build_joined_frame,
    _candidate_pool,
    build_multitimeframe_decomposition,
)


def _write_parquet(path: Path, frame: pd.DataFrame) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    frame.to_parquet(path, index=False)


def test_build_joined_frame_prefers_native_hierarchical_join(tmp_path) -> None:
    samples = pd.DataFrame(
        [
            {
                "dt": 20240304,
                "code": "1306",
                "side": "buy",
                "logic_version": "v1",
                "basis_version": "v1",
                "name": "sample",
                "setup_type": "test",
                "entry_qualified": True,
                "signal_month": 202403,
                "signal_date_ymd": 20240304,
                "entry_date_ymd": 20240305,
                "entry_price": 100.0,
                "long_entry_price": 100.0,
                "short_entry_price": 100.0,
                "long_mfe_20": 0.12,
                "long_mae_20": 0.03,
                "short_mfe_20": 0.05,
                "short_mae_20": 0.02,
                "days_to_long_mfe": 6,
                "days_to_long_mae": 2,
                "days_to_short_mfe": 8,
                "days_to_short_mae": 3,
                "long_mfe_before_stop_20": 0.09,
                "short_mfe_before_stop_20": 0.04,
                "best_refined_long_entry_open": 99.0,
                "best_refined_short_entry_open": 101.0,
                "long_entry_improvement_gap": 0.01,
                "short_entry_improvement_gap": 0.01,
                "pre_signal_runup_long": 0.02,
                "pre_signal_drop_short": 0.02,
                "remaining_upside_ratio_long": 0.7,
                "remaining_downside_ratio_short": 0.3,
                "long_timing_label": "BUY_ON_TIME",
                "short_timing_label": None,
                "long_timing_score": 81.0,
                "short_timing_score": 79.0,
                "tradeability_score": 60.0,
                "directional_label": "BUY_STRONG",
                "directional_strong": True,
                "directional_weak": False,
                "state_combination": "monthly=foo|weekly=bar|daily=baz",
                "reason_snapshot": json.dumps({"monthlyChangeDayFlag": True}, ensure_ascii=False),
                "score_snapshot": json.dumps({"tradePriorityScore": 66.0}, ensure_ascii=False),
                "rank_snapshot": json.dumps({"finalRank": 1}, ensure_ascii=False),
                "basis_payload": json.dumps(
                    {
                        "marketRegime": "risk_on",
                        "monthlyBoxState": "box_upper",
                        "weeklyBreakoutUpProb": 0.72,
                        "weeklyBreakoutDownProb": 0.18,
                        "monthlyBreakoutUpProb": 0.68,
                        "monthlyBreakoutDownProb": 0.19,
                        "changePct": 0.04,
                        "bullMarubozu": 1.0,
                        "bearMarubozu": 0.0,
                        "shootingStarLike": 0.0,
                        "morningStar": 1.0,
                        "reclaim60": 1.0,
                        "v60Core": 1.0,
                        "v60Strong": 1.0,
                    },
                    ensure_ascii=False,
                ),
                "failure_kind": "success",
                "is_success": True,
                "month_bucket": "202403",
                "context_days_used": 20,
                "pre_signal_context_full": True,
            }
            ,
            {
                "dt": 20240304,
                "code": "2306",
                "side": "sell",
                "logic_version": "v1",
                "basis_version": "v1",
                "name": "sample",
                "setup_type": "test",
                "entry_qualified": True,
                "signal_month": 202403,
                "signal_date_ymd": 20240304,
                "entry_date_ymd": 20240305,
                "entry_price": 100.0,
                "long_entry_price": 100.0,
                "short_entry_price": 100.0,
                "long_mfe_20": 0.05,
                "long_mae_20": 0.02,
                "short_mfe_20": 0.11,
                "short_mae_20": 0.04,
                "days_to_long_mfe": 5,
                "days_to_long_mae": 3,
                "days_to_short_mfe": 6,
                "days_to_short_mae": 2,
                "long_mfe_before_stop_20": 0.04,
                "short_mfe_before_stop_20": 0.08,
                "best_refined_long_entry_open": 99.5,
                "best_refined_short_entry_open": 101.5,
                "long_entry_improvement_gap": 0.005,
                "short_entry_improvement_gap": 0.015,
                "pre_signal_runup_long": 0.01,
                "pre_signal_drop_short": 0.03,
                "remaining_upside_ratio_long": 0.4,
                "remaining_downside_ratio_short": 0.6,
                "long_timing_label": None,
                "short_timing_label": "SELL_ON_TIME",
                "long_timing_score": 77.0,
                "short_timing_score": 82.0,
                "tradeability_score": 65.0,
                "directional_label": "SELL_STRONG",
                "directional_strong": True,
                "directional_weak": False,
                "state_combination": "monthly=foo|weekly=bar|daily=baz",
                "reason_snapshot": json.dumps({"monthlyChangeDayFlag": False}, ensure_ascii=False),
                "score_snapshot": json.dumps({"tradePriorityScore": 62.0}, ensure_ascii=False),
                "rank_snapshot": json.dumps({"finalRank": 2}, ensure_ascii=False),
                "basis_payload": json.dumps(
                    {
                        "marketRegime": "risk_off",
                        "monthlyBoxState": "box_lower",
                        "weeklyBreakoutUpProb": 0.24,
                        "weeklyBreakoutDownProb": 0.74,
                        "monthlyBreakoutUpProb": 0.18,
                        "monthlyBreakoutDownProb": 0.71,
                        "changePct": -0.05,
                        "bullMarubozu": 0.0,
                        "bearMarubozu": 1.0,
                        "shootingStarLike": 1.0,
                        "morningStar": 0.0,
                        "reclaim60": 0.0,
                        "v60Core": 0.0,
                        "v60Strong": 0.0,
                    },
                    ensure_ascii=False,
                ),
                "failure_kind": "success",
                "is_success": True,
                "month_bucket": "202403",
                "context_days_used": 20,
                "pre_signal_context_full": True,
            }
            ,
            {
                "dt": 20240304,
                "code": "2306",
                "side": "sell",
                "logic_version": "v1",
                "basis_version": "v1",
                "name": "sample",
                "setup_type": "test",
                "entry_qualified": True,
                "signal_month": 202403,
                "signal_date_ymd": 20240304,
                "entry_date_ymd": 20240305,
                "entry_price": 100.0,
                "long_entry_price": 100.0,
                "short_entry_price": 100.0,
                "long_mfe_20": 0.05,
                "long_mae_20": 0.02,
                "short_mfe_20": 0.11,
                "short_mae_20": 0.04,
                "days_to_long_mfe": 5,
                "days_to_long_mae": 3,
                "days_to_short_mfe": 6,
                "days_to_short_mae": 2,
                "long_mfe_before_stop_20": 0.04,
                "short_mfe_before_stop_20": 0.08,
                "best_refined_long_entry_open": 99.5,
                "best_refined_short_entry_open": 101.5,
                "long_entry_improvement_gap": 0.005,
                "short_entry_improvement_gap": 0.015,
                "pre_signal_runup_long": 0.01,
                "pre_signal_drop_short": 0.03,
                "remaining_upside_ratio_long": 0.4,
                "remaining_downside_ratio_short": 0.6,
                "long_timing_label": None,
                "short_timing_label": "SELL_ON_TIME",
                "long_timing_score": 77.0,
                "short_timing_score": 82.0,
                "tradeability_score": 65.0,
                "directional_label": "SELL_STRONG",
                "directional_strong": True,
                "directional_weak": False,
                "state_combination": "monthly=foo|weekly=bar|daily=baz",
                "reason_snapshot": json.dumps({"monthlyChangeDayFlag": False}, ensure_ascii=False),
                "score_snapshot": json.dumps({"tradePriorityScore": 62.0}, ensure_ascii=False),
                "rank_snapshot": json.dumps({"finalRank": 2}, ensure_ascii=False),
                "basis_payload": json.dumps(
                    {
                        "marketRegime": "risk_off",
                        "monthlyBoxState": "box_lower",
                        "weeklyBreakoutUpProb": 0.24,
                        "weeklyBreakoutDownProb": 0.74,
                        "monthlyBreakoutUpProb": 0.18,
                        "monthlyBreakoutDownProb": 0.71,
                        "changePct": -0.05,
                        "bullMarubozu": 0.0,
                        "bearMarubozu": 1.0,
                        "shootingStarLike": 1.0,
                        "morningStar": 0.0,
                        "reclaim60": 0.0,
                        "v60Core": 0.0,
                        "v60Strong": 0.0,
                    },
                    ensure_ascii=False,
                ),
                "failure_kind": "success",
                "is_success": True,
                "month_bucket": "202403",
                "context_days_used": 20,
                "pre_signal_context_full": True,
            }
            ,
            {
                "dt": 20240304,
                "code": "2306",
                "side": "sell",
                "logic_version": "v1",
                "basis_version": "v1",
                "name": "sample",
                "setup_type": "test",
                "entry_qualified": True,
                "signal_month": 202403,
                "signal_date_ymd": 20240304,
                "entry_date_ymd": 20240305,
                "entry_price": 100.0,
                "long_entry_price": 100.0,
                "short_entry_price": 100.0,
                "long_mfe_20": 0.05,
                "long_mae_20": 0.02,
                "short_mfe_20": 0.11,
                "short_mae_20": 0.04,
                "days_to_long_mfe": 5,
                "days_to_long_mae": 3,
                "days_to_short_mfe": 6,
                "days_to_short_mae": 2,
                "long_mfe_before_stop_20": 0.04,
                "short_mfe_before_stop_20": 0.08,
                "best_refined_long_entry_open": 99.5,
                "best_refined_short_entry_open": 101.5,
                "long_entry_improvement_gap": 0.005,
                "short_entry_improvement_gap": 0.015,
                "pre_signal_runup_long": 0.01,
                "pre_signal_drop_short": 0.03,
                "remaining_upside_ratio_long": 0.4,
                "remaining_downside_ratio_short": 0.6,
                "long_timing_label": None,
                "short_timing_label": "SELL_ON_TIME",
                "long_timing_score": 77.0,
                "short_timing_score": 82.0,
                "tradeability_score": 65.0,
                "directional_label": "SELL_STRONG",
                "directional_strong": True,
                "directional_weak": False,
                "state_combination": "monthly=foo|weekly=bar|daily=baz",
                "reason_snapshot": json.dumps({"monthlyChangeDayFlag": False}, ensure_ascii=False),
                "score_snapshot": json.dumps({"tradePriorityScore": 62.0}, ensure_ascii=False),
                "rank_snapshot": json.dumps({"finalRank": 2}, ensure_ascii=False),
                "basis_payload": json.dumps(
                    {
                        "marketRegime": "risk_off",
                        "monthlyBoxState": "box_lower",
                        "weeklyBreakoutUpProb": 0.24,
                        "weeklyBreakoutDownProb": 0.74,
                        "monthlyBreakoutUpProb": 0.18,
                        "monthlyBreakoutDownProb": 0.71,
                        "changePct": -0.05,
                        "bullMarubozu": 0.0,
                        "bearMarubozu": 1.0,
                        "shootingStarLike": 1.0,
                        "morningStar": 0.0,
                        "reclaim60": 0.0,
                        "v60Core": 0.0,
                        "v60Strong": 0.0,
                    },
                    ensure_ascii=False,
                ),
                "failure_kind": "success",
                "is_success": True,
                "month_bucket": "202403",
                "context_days_used": 20,
                "pre_signal_context_full": True,
            }
            ,
            {
                "dt": 20240304,
                "code": "2306",
                "side": "sell",
                "logic_version": "v1",
                "basis_version": "v1",
                "name": "sample",
                "setup_type": "test",
                "entry_qualified": True,
                "signal_month": 202403,
                "signal_date_ymd": 20240304,
                "entry_date_ymd": 20240305,
                "entry_price": 100.0,
                "long_entry_price": 100.0,
                "short_entry_price": 100.0,
                "long_mfe_20": 0.05,
                "long_mae_20": 0.02,
                "short_mfe_20": 0.11,
                "short_mae_20": 0.04,
                "days_to_long_mfe": 5,
                "days_to_long_mae": 3,
                "days_to_short_mfe": 6,
                "days_to_short_mae": 2,
                "long_mfe_before_stop_20": 0.04,
                "short_mfe_before_stop_20": 0.08,
                "best_refined_long_entry_open": 99.5,
                "best_refined_short_entry_open": 101.5,
                "long_entry_improvement_gap": 0.005,
                "short_entry_improvement_gap": 0.015,
                "pre_signal_runup_long": 0.01,
                "pre_signal_drop_short": 0.03,
                "remaining_upside_ratio_long": 0.4,
                "remaining_downside_ratio_short": 0.6,
                "long_timing_label": None,
                "short_timing_label": "SELL_ON_TIME",
                "long_timing_score": 77.0,
                "short_timing_score": 82.0,
                "tradeability_score": 65.0,
                "directional_label": "SELL_STRONG",
                "directional_strong": True,
                "directional_weak": False,
                "state_combination": "monthly=foo|weekly=bar|daily=baz",
                "reason_snapshot": json.dumps({"monthlyChangeDayFlag": False}, ensure_ascii=False),
                "score_snapshot": json.dumps({"tradePriorityScore": 62.0}, ensure_ascii=False),
                "rank_snapshot": json.dumps({"finalRank": 2}, ensure_ascii=False),
                "basis_payload": json.dumps(
                    {
                        "marketRegime": "risk_off",
                        "monthlyBoxState": "box_lower",
                        "weeklyBreakoutUpProb": 0.24,
                        "weeklyBreakoutDownProb": 0.74,
                        "monthlyBreakoutUpProb": 0.18,
                        "monthlyBreakoutDownProb": 0.71,
                        "changePct": -0.05,
                        "bullMarubozu": 0.0,
                        "bearMarubozu": 1.0,
                        "shootingStarLike": 1.0,
                        "morningStar": 0.0,
                        "reclaim60": 0.0,
                        "v60Core": 0.0,
                        "v60Strong": 0.0,
                    },
                    ensure_ascii=False,
                ),
                "failure_kind": "success",
                "is_success": True,
                "month_bucket": "202403",
                "context_days_used": 20,
                "pre_signal_context_full": True,
            }
            ,
            {
                "dt": 20240304,
                "code": "2306",
                "side": "sell",
                "logic_version": "v1",
                "basis_version": "v1",
                "name": "sample",
                "setup_type": "test",
                "entry_qualified": True,
                "signal_month": 202403,
                "signal_date_ymd": 20240304,
                "entry_date_ymd": 20240305,
                "entry_price": 100.0,
                "long_entry_price": 100.0,
                "short_entry_price": 100.0,
                "long_mfe_20": 0.05,
                "long_mae_20": 0.02,
                "short_mfe_20": 0.11,
                "short_mae_20": 0.04,
                "days_to_long_mfe": 5,
                "days_to_long_mae": 3,
                "days_to_short_mfe": 6,
                "days_to_short_mae": 2,
                "long_mfe_before_stop_20": 0.04,
                "short_mfe_before_stop_20": 0.08,
                "best_refined_long_entry_open": 99.5,
                "best_refined_short_entry_open": 101.5,
                "long_entry_improvement_gap": 0.005,
                "short_entry_improvement_gap": 0.015,
                "pre_signal_runup_long": 0.01,
                "pre_signal_drop_short": 0.03,
                "remaining_upside_ratio_long": 0.4,
                "remaining_downside_ratio_short": 0.6,
                "long_timing_label": None,
                "short_timing_label": "SELL_ON_TIME",
                "long_timing_score": 77.0,
                "short_timing_score": 82.0,
                "tradeability_score": 65.0,
                "directional_label": "SELL_STRONG",
                "directional_strong": True,
                "directional_weak": False,
                "state_combination": "monthly=foo|weekly=bar|daily=baz",
                "reason_snapshot": json.dumps({"monthlyChangeDayFlag": False}, ensure_ascii=False),
                "score_snapshot": json.dumps({"tradePriorityScore": 62.0}, ensure_ascii=False),
                "rank_snapshot": json.dumps({"finalRank": 2}, ensure_ascii=False),
                "basis_payload": json.dumps(
                    {
                        "marketRegime": "risk_off",
                        "monthlyBoxState": "box_lower",
                        "weeklyBreakoutUpProb": 0.24,
                        "weeklyBreakoutDownProb": 0.74,
                        "monthlyBreakoutUpProb": 0.18,
                        "monthlyBreakoutDownProb": 0.71,
                        "changePct": -0.05,
                        "bullMarubozu": 0.0,
                        "bearMarubozu": 1.0,
                        "shootingStarLike": 1.0,
                        "morningStar": 0.0,
                        "reclaim60": 0.0,
                        "v60Core": 0.0,
                        "v60Strong": 0.0,
                    },
                    ensure_ascii=False,
                ),
                "failure_kind": "success",
                "is_success": True,
                "month_bucket": "202403",
                "context_days_used": 20,
                "pre_signal_context_full": True,
            }
        ]
    )
    hierarchical = pd.DataFrame(
        [
            {
                "code": "1306",
                "sample_month": 202403,
                "monthly_main_state": "monthly_up_mid",
                "weekly_main_state": "weekly_up_mid",
                "daily_main_state": "daily_up_mid",
                "monthly_environment_score": 68.0,
                "weekly_trend_score": 71.0,
                "daily_execution_score": 64.0,
                "change_day_score": 58.0,
                "monthly_change_day_flag": True,
                "weekly_change_day_flag": False,
                "daily_change_day_flag": True,
                "daily_gap_up_flag": False,
                "daily_gap_down_flag": False,
                "daily_engulfing_bull_flag": True,
                "daily_engulfing_bear_flag": False,
                "daily_reclaim_ma20_flag": True,
                "daily_lose_ma20_flag": False,
                "daily_long_lower_wick_flag": True,
                "daily_long_upper_wick_flag": False,
                "daily_small_body_flag": False,
                "monthly_price_vs_ma12_state": "above",
                "monthly_price_vs_ma24_state": "above",
                "monthly_ma12_slope_state": "up",
                "monthly_ma24_slope_state": "up",
                "monthly_alignment_state": "bull_stack",
                "weekly_price_vs_ma10_state": "above",
                "weekly_price_vs_ma30_state": "above",
                "weekly_price_vs_ma60_state": "above",
                "weekly_ma10_slope_state": "up",
                "weekly_ma30_slope_state": "up",
                "weekly_alignment_state": "bull_stack",
                "daily_price_vs_ma7_state": "above",
                "daily_price_vs_ma20_state": "above",
                "daily_price_vs_ma60_state": "above",
                "daily_ma7_slope_state": "up",
                "daily_ma20_slope_state": "up",
                "daily_alignment_state": "bull_stack",
                "winner_promotion_score": 72.0,
                "loser_removal_score": 28.0,
                "regime_tag": "risk_on",
            }
            ,
            {
                "code": "2306",
                "sample_month": 202403,
                "monthly_main_state": "monthly_down_mid",
                "weekly_main_state": "weekly_down_mid",
                "daily_main_state": "daily_down_mid",
                "monthly_environment_score": 32.0,
                "weekly_trend_score": 29.0,
                "daily_execution_score": 35.0,
                "change_day_score": 42.0,
                "monthly_change_day_flag": False,
                "weekly_change_day_flag": True,
                "daily_change_day_flag": False,
                "daily_gap_up_flag": False,
                "daily_gap_down_flag": True,
                "daily_engulfing_bull_flag": False,
                "daily_engulfing_bear_flag": True,
                "daily_reclaim_ma20_flag": False,
                "daily_lose_ma20_flag": True,
                "daily_long_lower_wick_flag": False,
                "daily_long_upper_wick_flag": True,
                "daily_small_body_flag": False,
                "monthly_price_vs_ma12_state": "below",
                "monthly_price_vs_ma24_state": "below",
                "monthly_ma12_slope_state": "down",
                "monthly_ma24_slope_state": "down",
                "monthly_alignment_state": "bear_stack",
                "weekly_price_vs_ma10_state": "below",
                "weekly_price_vs_ma30_state": "below",
                "weekly_price_vs_ma60_state": "below",
                "weekly_ma10_slope_state": "down",
                "weekly_ma30_slope_state": "down",
                "weekly_alignment_state": "bear_stack",
                "daily_price_vs_ma7_state": "below",
                "daily_price_vs_ma20_state": "below",
                "daily_price_vs_ma60_state": "below",
                "daily_ma7_slope_state": "down",
                "daily_ma20_slope_state": "down",
                "daily_alignment_state": "bear_stack",
                "winner_promotion_score": 24.0,
                "loser_removal_score": 76.0,
                "regime_tag": "risk_off",
            }
        ]
    )

    frame = _build_joined_frame(samples, hierarchical)

    assert bool(frame.loc[0, "exact_join_available"]) is True
    assert frame.loc[0, "join_mode"] == "exact"
    assert bool(frame.loc[0, "hierarchical_native_exact_match"]) is True
    assert frame.loc[0, "monthly_main_state_ctx"] == "monthly_up_mid"
    assert frame.loc[0, "weekly_main_state_ctx"] == "weekly_up_mid"
    assert frame.loc[0, "daily_main_state_ctx"] == "daily_up_mid"
    assert frame.loc[0, "triple_state_key"].startswith("monthly_main_state=monthly_up_mid")


def test_candidate_pool_orders_family_specific_priority() -> None:
    rows = [
        {
            "state_combination": "cluster_a",
            "sample_count": 40,
            "directional_success_rate": 0.25,
            "timing_on_time_rate": 0.40,
            "too_early_rate": 0.10,
            "too_late_rate": 0.55,
            "mfe_20_mean": 0.04,
            "mae_20_mean": 0.08,
            "timing_score_mean": 71.0,
            "coverage_status": "usable",
        },
        {
            "state_combination": "cluster_b",
            "sample_count": 42,
            "directional_success_rate": 0.55,
            "timing_on_time_rate": 0.72,
            "too_early_rate": 0.08,
            "too_late_rate": 0.12,
            "mfe_20_mean": 0.08,
            "mae_20_mean": 0.04,
            "timing_score_mean": 79.0,
            "coverage_status": "usable",
        },
    ]

    output = _candidate_pool(
        rows,
        side_role="long",
        family="long_too_late_candidates_multitimeframe",
        long_soft_gain=0.05,
        short_soft_gain=0.05,
        min_sample_threshold=30,
    )

    assert output[0]["state_combination"] == "cluster_a"
    assert output[0]["candidate_rank_in_family"] == 1
    assert output[0]["candidate_priority_score"] >= output[1]["candidate_priority_score"]
    assert output[0]["recommendation"] == "block_candidate"


def test_build_multitimeframe_decomposition_emits_multi_level_contract(tmp_path) -> None:
    samples_path = tmp_path / "samples.parquet"
    hierarchical_path = tmp_path / "hierarchical.parquet"
    thresholds_path = tmp_path / "thresholds.json"

    samples = pd.DataFrame(
        [
            {
                "dt": 20240304,
                "code": "1306",
                "side": "buy",
                "logic_version": "v1",
                "basis_version": "v1",
                "name": "sample",
                "setup_type": "test",
                "entry_qualified": True,
                "signal_month": 202403,
                "signal_date_ymd": 20240304,
                "entry_date_ymd": 20240305,
                "entry_price": 100.0,
                "long_entry_price": 100.0,
                "short_entry_price": 100.0,
                "long_mfe_20": 0.12,
                "long_mae_20": 0.03,
                "short_mfe_20": 0.05,
                "short_mae_20": 0.02,
                "days_to_long_mfe": 6,
                "days_to_long_mae": 2,
                "days_to_short_mfe": 8,
                "days_to_short_mae": 3,
                "long_mfe_before_stop_20": 0.09,
                "short_mfe_before_stop_20": 0.04,
                "best_refined_long_entry_open": 99.0,
                "best_refined_short_entry_open": 101.0,
                "long_entry_improvement_gap": 0.01,
                "short_entry_improvement_gap": 0.01,
                "pre_signal_runup_long": 0.02,
                "pre_signal_drop_short": 0.02,
                "remaining_upside_ratio_long": 0.7,
                "remaining_downside_ratio_short": 0.3,
                "long_timing_label": "BUY_ON_TIME",
                "short_timing_label": None,
                "long_timing_score": 81.0,
                "short_timing_score": 79.0,
                "tradeability_score": 60.0,
                "directional_label": "BUY_STRONG",
                "directional_strong": True,
                "directional_weak": False,
                "state_combination": "monthly=foo|weekly=bar|daily=baz",
                "reason_snapshot": json.dumps({"monthlyChangeDayFlag": True}, ensure_ascii=False),
                "score_snapshot": json.dumps({"tradePriorityScore": 66.0}, ensure_ascii=False),
                "rank_snapshot": json.dumps({"finalRank": 1}, ensure_ascii=False),
                "basis_payload": json.dumps(
                    {
                        "marketRegime": "risk_on",
                        "monthlyBoxState": "box_upper",
                        "weeklyBreakoutUpProb": 0.72,
                        "weeklyBreakoutDownProb": 0.18,
                        "monthlyBreakoutUpProb": 0.68,
                        "monthlyBreakoutDownProb": 0.19,
                        "changePct": 0.04,
                        "bullMarubozu": 1.0,
                        "bearMarubozu": 0.0,
                        "shootingStarLike": 0.0,
                        "morningStar": 1.0,
                        "reclaim60": 1.0,
                        "v60Core": 1.0,
                        "v60Strong": 1.0,
                    },
                    ensure_ascii=False,
                ),
                "failure_kind": "success",
                "is_success": True,
                "month_bucket": "202403",
                "context_days_used": 20,
                "pre_signal_context_full": True,
            }
        ]
    )
    hierarchical = pd.DataFrame(
        [
            {
                "code": "1306",
                "sample_month": 202403,
                "monthly_main_state": "monthly_up_mid",
                "weekly_main_state": "weekly_up_mid",
                "daily_main_state": "daily_up_mid",
                "monthly_environment_score": 68.0,
                "weekly_trend_score": 71.0,
                "daily_execution_score": 64.0,
                "change_day_score": 58.0,
                "monthly_change_day_flag": True,
                "weekly_change_day_flag": False,
                "daily_change_day_flag": True,
                "daily_gap_up_flag": False,
                "daily_gap_down_flag": False,
                "daily_engulfing_bull_flag": True,
                "daily_engulfing_bear_flag": False,
                "daily_reclaim_ma20_flag": True,
                "daily_lose_ma20_flag": False,
                "daily_long_lower_wick_flag": True,
                "daily_long_upper_wick_flag": False,
                "daily_small_body_flag": False,
                "monthly_price_vs_ma12_state": "above",
                "monthly_price_vs_ma24_state": "above",
                "monthly_ma12_slope_state": "up",
                "monthly_ma24_slope_state": "up",
                "monthly_alignment_state": "bull_stack",
                "weekly_price_vs_ma10_state": "above",
                "weekly_price_vs_ma30_state": "above",
                "weekly_price_vs_ma60_state": "above",
                "weekly_ma10_slope_state": "up",
                "weekly_ma30_slope_state": "up",
                "weekly_alignment_state": "bull_stack",
                "daily_price_vs_ma7_state": "above",
                "daily_price_vs_ma20_state": "above",
                "daily_price_vs_ma60_state": "above",
                "daily_ma7_slope_state": "up",
                "daily_ma20_slope_state": "up",
                "daily_alignment_state": "bull_stack",
                "winner_promotion_score": 72.0,
                "loser_removal_score": 28.0,
                "regime_tag": "risk_on",
            }
            ,
            {
                "code": "2306",
                "sample_month": 202403,
                "monthly_main_state": "monthly_down_mid",
                "weekly_main_state": "weekly_down_mid",
                "daily_main_state": "daily_down_mid",
                "monthly_environment_score": 32.0,
                "weekly_trend_score": 29.0,
                "daily_execution_score": 35.0,
                "change_day_score": 42.0,
                "monthly_change_day_flag": False,
                "weekly_change_day_flag": True,
                "daily_change_day_flag": False,
                "daily_gap_up_flag": False,
                "daily_gap_down_flag": True,
                "daily_engulfing_bull_flag": False,
                "daily_engulfing_bear_flag": True,
                "daily_reclaim_ma20_flag": False,
                "daily_lose_ma20_flag": True,
                "daily_long_lower_wick_flag": False,
                "daily_long_upper_wick_flag": True,
                "daily_small_body_flag": False,
                "monthly_price_vs_ma12_state": "below",
                "monthly_price_vs_ma24_state": "below",
                "monthly_ma12_slope_state": "down",
                "monthly_ma24_slope_state": "down",
                "monthly_alignment_state": "bear_stack",
                "weekly_price_vs_ma10_state": "below",
                "weekly_price_vs_ma30_state": "below",
                "weekly_price_vs_ma60_state": "below",
                "weekly_ma10_slope_state": "down",
                "weekly_ma30_slope_state": "down",
                "weekly_alignment_state": "bear_stack",
                "daily_price_vs_ma7_state": "below",
                "daily_price_vs_ma20_state": "below",
                "daily_price_vs_ma60_state": "below",
                "daily_ma7_slope_state": "down",
                "daily_ma20_slope_state": "down",
                "daily_alignment_state": "bear_stack",
                "winner_promotion_score": 24.0,
                "loser_removal_score": 76.0,
                "regime_tag": "risk_off",
            }
        ]
    )
    thresholds = {
        "signal_replay_contract": {"entry_convention": "next_session_open_after_signal_date"},
        "thresholds": {"baseline": {"soft_gain_pct_long": 0.05, "soft_gain_pct_short": 0.05}},
        "split_contract": {
            "train_months": [202403],
            "tune_months": [202404],
            "validation_months": [202403],
        },
    }

    _write_parquet(samples_path, samples)
    _write_parquet(hierarchical_path, hierarchical)
    thresholds_path.write_text(json.dumps(thresholds, ensure_ascii=False), encoding="utf-8")

    result = build_multitimeframe_decomposition(
        samples_path=samples_path,
        hierarchical_path=hierarchical_path,
        thresholds_path=thresholds_path,
    )

    assert result["candidate_map"]["join_summary"]["exact_join_rate"] == 1.0
    assert result["authoritative_decision"]["decision"] == "keep_multitimeframe_decomposition_layer"
    assert result["long_decomposition"]["level_summary"]["single_timeframe"]["monthly_only"]["group_count"] == 1
    assert result["long_decomposition"]["single_timeframe"]["monthly_only"][0]["directional_label_counts"]["BUY_STRONG"] == 1
    assert result["long_decomposition"]["single_timeframe"]["monthly_only"][0]["timing_label_counts"]["BUY_ON_TIME"] == 1
    assert result["candidate_map"]["long_too_late_candidates_multitimeframe"][0]["candidate_priority_score"] >= 0.0
