"""Authoritative rollup for the monthly-selection / daily-action sell research."""
import argparse,hashlib,json
from pathlib import Path
import pandas as pd
def load(p):return json.loads(Path(p).read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def slice5(x):
 h=x['horizon_results']['5'];return {'executable':h['executable'],'clean_2026_excluding_teacher_codes':h['clean_2026_excluding_teacher_codes'],'clean_2026_codes':h['clean_2026_codes'],'loss_streaks':h['loss_streaks'],'portfolio':h['portfolio'],'by_signal_year':h['by_signal_year']}
def main():
 ap=argparse.ArgumentParser();
 for n in ['monthly','teacher','baseline','oversold','age','breakdown','add','add_actions']:ap.add_argument('--'+n.replace('_','-'),required=True)
 ap.add_argument('--output',type=Path,required=True);a=ap.parse_args();a.output.mkdir(parents=True,exist_ok=False)
 monthly=load(a.monthly);teacher=load(a.teacher);baseline=load(a.baseline);oversold=load(a.oversold);age=load(a.age);breakdown=load(a.breakdown);add=load(a.add)
 base_actions=pd.read_parquet(Path(a.teacher).parent/'action_ledger.parquet');adds=pd.read_parquet(a.add_actions);adds=adds.rename(columns={'parent_core_ymd':'source_core_ymd'});adds['action']='ADD'
 unified=pd.concat([base_actions,adds[['code','ymd','action','reason','monthly_state']]],ignore_index=True).sort_values(['code','ymd','action'])
 data={'schema_version':'tradex_monthly_daily_sell_model_rollup_v1.compare.v1','artifact_role':'authoritative_rollup_decision','review_only':True,'research_phase':'effectiveness_judgment','fixed_conditions':{'universe':'Nikkei225-centered fixed feature ledger plus declared teacher coverage','period':'2020-2025 same-condition; 2026 clean excludes six teacher codes','monthly':'confirmed prior month plus month-to-date OHLC truncated at decision close','daily_execution':'signal close then next-session open','primary_horizon_sessions':5,'barriers':'short target -3%, stop +3%, same-bar stop-first','costs':'ignored','weekly_inputs':[],'automatic_reflection':False},'teacher_contract':{'decision':teacher['judgment']['decision'],'expected':teacher['teacher_expected'],'avoided':teacher['teacher_avoided'],'monthly_selection_summary':monthly['summary']},'candidate_flow':{'monthly_selection_events':monthly['summary']['event_counts'],'daily_action_counts':teacher['observed_branching']['action_counts'],'probe_to_core':baseline['probe_to_core'],'add_signals':int((unified.action=='ADD').sum()),'breakdown_candidates':breakdown['observed_branching']['raw_core_events']},'authoritative_results':{'baseline_core':slice5(baseline),'oversold_risk_single_axis':slice5(oversold),'selection_age5_single_axis':slice5(age),'breakdown_branch':slice5(breakdown),'add_continuation':slice5(add)},'observed_branching':{'baseline_core':baseline['observed_branching'],'oversold_core':oversold['observed_branching'],'age5_core':age['observed_branching'],'breakdown_core':breakdown['observed_branching'],'add_core':add['observed_branching']},'judgment':{'candidate_local_decision':{'teacher_state_contract':'keep','baseline_core':'hold','oversold_risk_gate':'hold_challenger','selection_age5_gate':'hold_challenger','breakdown':'drop','add_continuation':'hold_low_sample'},'session_aggregate_decision':'hold_review_only','authoritative_rollup_decision':'hold_review_only','reason':'teacher paths are reproduced and historical aggregate CORE is positive, but clean 2026 baseline is 0D/3R; each single-axis gate leaves only losses, their combination has zero clean breadth, BREAKDOWN loses, and ADD has no non-teacher clean-2026 sample'},'not_changed':['MeeMee','ranking','runtime DB','weekly features','production trading logic'],'remaining_risks':['clean 2026 breadth is three baseline events across two codes','2024 concentration','probe capital path not yet adopted as an executable portfolio','ADD has 14 signals and no non-teacher clean-2026 event','release directory hygiene failure is unrelated and was not modified']}
 sources=[]
 for name,p in [('monthly',a.monthly),('teacher',a.teacher),('baseline',a.baseline),('oversold',a.oversold),('age',a.age),('breakdown',a.breakdown),('add',a.add)]:sources.append({'name':name,'path':str(Path(p)),'sha256':sha(p)})
 data['sources']=sources;cp=a.output/'compare.json';cp.write_text(json.dumps(data,ensure_ascii=False,indent=2,allow_nan=False)+'\n',encoding='utf-8');unified.to_parquet(a.output/'unified_review_action_ledger.parquet',index=False);(a.output/'audit.json').write_text(json.dumps({'duplicates':int(unified.duplicated(['code','ymd','action']).sum()),'weekly_columns_used':[],'future_feature_columns_used':[],'teacher_all_pass':all(teacher['teacher_expected'].values()) and all(teacher['teacher_avoided'].values()),'source_count':len(sources)},indent=2)+'\n');(a.output/'_ARTIFACT_COMPLETE.json').write_text(json.dumps({'complete':True,'authoritative':'compare.json','sha256':sha(cp)},indent=2)+'\n');print(json.dumps({'output':str(a.output),'judgment':data['judgment'],'candidate_flow':data['candidate_flow']},ensure_ascii=False))
if __name__=='__main__':main()
