"""One-axis follow-up: require close position >=55% after below7 lower wick."""
from __future__ import annotations
import argparse,json
from datetime import datetime,timezone
from pathlib import Path
import pandas as pd
def rates(x):return {"n":int(len(x)),"further_down_first":None if x.empty else float(x.label.eq(0).mean()),"rebound_first":None if x.empty else float(x.label.eq(1).mean()),"neutral":None if x.empty else float(x.label.eq(2).mean())}
def main():
 p=argparse.ArgumentParser();p.add_argument("--lower-wick-ledger",type=Path,required=True);p.add_argument("--output-root",type=Path,required=True);a=p.parse_args();stamp=datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ");out=a.output_root/f"{stamp}-tradex-profit-take-below7-lower-wick-closepos-oos-v1";out.mkdir(parents=True,exist_ok=False)
 x=pd.read_parquet(a.lower_wick_ledger);base=x[x.lower_wick_rejection];q=base[base.close_pos.ge(.55)];years={str(y):{"champion":rates(base[base.year.eq(y)]),"challenger":rates(q[q.year.eq(y)])} for y in range(2019,2027)};overall={"champion":rates(base),"challenger":rates(q)};stable=all(v["challenger"]["n"]==0 or v["challenger"]["rebound_first"]>v["challenger"]["further_down_first"] for v in years.values());improved=overall["challenger"]["rebound_first"]>overall["champion"]["rebound_first"] and overall["challenger"]["further_down_first"]<overall["champion"]["further_down_first"];decision="keep" if stable and improved else "drop"
 data={"schema_version":"tradex_profit_take_below7_lower_wick_closepos_oos_v1.compare.v1","artifact_role":"authoritative","axis":"add close_pos >=0.55 to below7 plus lower-wick>=0.40 profit-take candidate","threshold_provenance":"existing rejection-veto contract; no sweep","year_results":years,"overall":overall,"judgment":{"decision":decision,"stable_all_years":stable,"improved_overall":improved,"reason":"close-position add-on must improve overall and preserve rebound dominance each year"},"not_changed":["below7","lower-wick threshold","MA proximity","position path","MeeMee","ranking","runtime DB"]};(out/"compare.json").write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");q.to_parquet(out/"profit_take_below7_lower_wick_closepos_ledger.parquet",index=False);audit={"base_rows":int(len(base)),"challenger_rows":int(len(q)),"duplicates":int(q.duplicated(["code","ymd"]).sum()),"future_used_for_selection":False,"review_only":True};(out/"audit.json").write_text(json.dumps(audit,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");(out/"_ARTIFACT_COMPLETE.json").write_text(json.dumps({"complete":True,"authoritative":"compare.json"},indent=2)+"\n",encoding="utf-8");print(out);print(json.dumps({"years":years,"overall":overall,"judgment":data["judgment"],"audit":audit},ensure_ascii=False,indent=2))
if __name__=="__main__":main()
