from __future__ import annotations
import argparse,json
from datetime import datetime,timezone
from pathlib import Path
import pandas as pd
from tradex_long_trend_pullback_portfolio_v1 import simulate,portfolio_summary,COST
SCHEMES={'均等5%':None,'ボラ上限1.5%':.015,'ボラ上限2.0%':.020,'ボラ上限2.5%':.025}
def allocated(base,cap):
 z=base.copy();z['allocation_weight']=.05 if cap is None else .05*(cap/z.realized_vol20.clip(lower=.001)).clip(upper=1);z['realized_ret']=z.raw_return_pct*z.allocation_weight;return z
def main():
 p=argparse.ArgumentParser();p.add_argument('--output',required=True);p.add_argument('--events',default=r'G:\Tradex\tradex_long_fresh_family_events_v1\20260720T-authoritative-v4\fresh_family_events.parquet');a=p.parse_args();out=Path(a.output);out.mkdir(parents=True,exist_ok=False);e=pd.read_parquet(a.events).rename(columns={'p1_date':'entry_date','p1_o':'entry_price','p20_date':'exit_date','p20_c':'exit_price'});e['rank']=-e.family_score;base=simulate(e,20);base['year']=pd.to_datetime(base.date,unit='s').dt.year;rows=[];ledgers={}
 for name,cap in SCHEMES.items():
  t=allocated(base,cap);ledgers[name]=t;d=t[t.year.between(2016,2023)];v=t[t.year.between(2024,2025)];rows.append({'scheme':name,'volatility_cap':cap,'development':portfolio_summary(d),'validation_2024_2025':portfolio_summary(v),'validation_years':{str(y):portfolio_summary(v[v.year.eq(y)]) for y in [2024,2025]},'mean_allocation_development':float(d.allocation_weight.mean()),'mean_allocation_validation':float(v.allocation_weight.mean())})
 def ok(m,n):return m['trades']>=n and m['raw_trade_metrics']['mean_return_pct']>0 and m['raw_trade_metrics']['win_rate']>=.50 and m['capital_contribution_metrics']['severe_loss5_rate']<=.03 and m['positive_month_rate']>.50 and m['capital_contribution_metrics']['top3_positive_profit_share']<=.35
 baseline=next(x for x in rows if x['scheme']=='均等5%')
 eligible=[x for x in rows if ok(x['development'],250) and ok(x['validation_2024_2025'],100) and x['development']['positive_year_rate']>=.75 and all(m['total_return_pct']>0 for m in x['validation_years'].values()) and x['development']['total_return_pct']>=.50*baseline['development']['total_return_pct'] and x['validation_2024_2025']['total_return_pct']>=.50*baseline['validation_2024_2025']['total_return_pct']]
 def risk_key(x):
  months=list(x['development']['monthly'].values())+list(x['validation_2024_2025']['monthly'].values());years=list(x['development']['yearly'].values())+list(x['validation_2024_2025']['yearly'].values());return (-min(months),-min(years),-x['validation_2024_2025']['total_return_pct'])
 chosen=min(eligible,key=risk_key) if eligible else None;t=ledgers[chosen['scheme']] if chosen else pd.DataFrame();t=t[t.year.eq(2026)] if len(t) else t;tm=portfolio_summary(t);r=tm['raw_trade_metrics'];c=tm['capital_contribution_metrics'];checks={'selected_without_2026':chosen is not None,'test_n250_or_full_audit':chosen is not None,'test_mean_positive':r['mean_return_pct'] is not None and r['mean_return_pct']>0,'test_win_at_least_50pct':r['win_rate'] is not None and r['win_rate']>=.50,'test_capital_loss5_at_most_3pct':c['severe_loss5_rate'] is not None and c['severe_loss5_rate']<=.03,'test_months_majority_positive':tm['positive_month_rate'] is not None and tm['positive_month_rate']>.50,'profit_not_concentrated':c['top3_positive_profit_share'] is not None and c['top3_positive_profit_share']<=.35,'test_total_return_positive':tm['total_return_pct']>0};decision='hold_for_baseline_and_mark_to_market_gate' if all(checks.values()) else 'drop'
 payload={'schema_version':'tradex_long_fresh_risk_allocation_v1.compare.v1','artifact_role':'authoritative','generated_at':datetime.now(timezone.utc).isoformat(),'fixed_evaluation_conditions':{'source':a.events,'universe':'ordinary domestic stocks only','selection':'fresh three-family continuous score; max 20 slots fixed','entry':'next session open','exit':'session-20 close','axis_changed':'per-position volatility allocation only','schemes':SCHEMES,'allocation':'base 5%; high 20-day realized volatility scales down; residual stays cash','minimum_return_retention':'50% of equal allocation total return in both development and validation','selection_objective':'minimize worst 2016-2025 calendar month, then worst year; 2026 excluded','round_trip_cost_pct':COST,'development':'2016-2023','validation':'2024-2025','full_audit_test':'2026 matured through 2026-07-17','production_changed':False},'authoritative_result':{'candidates':rows,'baseline':baseline,'eligible_without_2026':eligible,'chosen_without_2026':chosen,'test_2026':tm,'test_mix':t.family.value_counts().to_dict() if len(t) else {},'test_mean_allocation':float(t.allocation_weight.mean()) if len(t) else None,'checks':checks},'observed_branching':{'changed_top5_members_count':0,'changed_top10_members_count':0,'changed_rank_count':tm['trades'],'selection_divergence_reason':'same trades; volatility-adjusted capital weight only'},'judgment':{'candidate_local_decision':decision,'authoritative_rollup_decision':decision,'reason_type':'fresh_risk_allocation_gate'},'remaining_risks':['same-condition baseline and mark-to-market drawdown pending only if test passes']}
 if len(t):t.to_parquet(out/'test_2026_portfolio_ledger.parquet',index=False)
 (out/'compare.json').write_text(json.dumps(payload,ensure_ascii=False,indent=2,default=str),encoding='utf-8');(out/'_ARTIFACT_COMPLETE.json').write_text(json.dumps({'complete':True,'authoritative':'compare.json'}),encoding='utf-8');print(json.dumps({'eligible_count':len(eligible),'chosen':chosen,'test':tm,'test_mean_allocation':payload['authoritative_result']['test_mean_allocation'],'checks':checks,'decision':decision},ensure_ascii=False))
if __name__=='__main__':main()
