from __future__ import annotations
import argparse,json
from pathlib import Path
import pandas as pd
def met(g):return {"n":int(len(g)),"codes":int(g.code.nunique()),"mean_return_pct":float(g.ret.mean()),"median_return_pct":float(g.ret.median()),"win_rate":float(g.ret.gt(0).mean()),"severe_loss5_rate":float(g.ret.le(-5).mean()),"p10_return_pct":float(g.ret.quantile(.1))}
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--holding-ledger",required=True);ap.add_argument("--output",required=True);a=ap.parse_args();out=Path(a.output);out.mkdir(parents=True,exist_ok=False);d=pd.read_parquet(a.holding_ledger);d=d[(d.buy_family.eq("急落反発"))&d.holding_days.eq(3)].copy();d["日本語階層"]="試し玉";d["実践行動"]="25%を維持し3営業日目終値で決済";im=d.entry_day_path.eq("即上昇");stall=d.entry_day_path.eq("失速");d.loc[im,"日本語階層"]="本命";d.loc[im,"実践行動"]="翌々日寄りで75%追加し3営業日目終値で決済";d.loc[stall,"日本語階層"]="見切り";d.loc[stall,"実践行動"]="翌々日寄りで初期玉を全撤退";rows=[];yrs=[]
 for (p,t),g in d.groupby(["period","日本語階層"]):rows.append({"period":p,"日本語階層":t,**met(g)})
 for (y,t),g in d.assign(year=d.ymd//10000).groupby(["year","日本語階層"]):yrs.append({"year":int(y),"日本語階層":t,**met(g)})
 summary=pd.DataFrame(rows);yr=pd.DataFrame(yrs);overall=pd.DataFrame([{"period":p,**met(g)} for p,g in d.groupby("period")]);annual=pd.DataFrame([{"year":int(y),**met(g)} for y,g in d.assign(year=d.ymd//10000).groupby("year")]);d.to_parquet(out/"practical_buy_ledger.parquet",index=False);summary.to_parquet(out/"japanese_tier_metrics.parquet",index=False);yr.to_parquet(out/"japanese_tier_yearly_metrics.parquet",index=False);checks={"development_positive":bool(overall[overall.period.eq("development")].iloc[0].mean_return_pct>0),"validation_positive":bool(overall[overall.period.eq("validation")].iloc[0].mean_return_pct>0),"all_validation_years_positive":bool(len(annual[annual.year>=2024])==3 and (annual[annual.year>=2024].mean_return_pct>0).all()),"validation_tail_le5":bool(overall[overall.period.eq("validation")].iloc[0].severe_loss5_rate<=.05),"validation_n_ge5000":bool(overall[overall.period.eq("validation")].iloc[0].n>=5000),"three_japanese_states_present":set(d["日本語階層"])=={"本命","試し玉","見切り"}};keep=all(checks.values())
 res={"schema_version":"tradex_long_practical_actionability_rollup_v1.compare.v1","artifact_role":"authoritative_long_practical_actionability_rollup","review_only":True,"research_phase":"effectiveness_judgment","fixed_conditions":{"selected_family":"急落反発","dropped_family":"上昇継続","entry":"next open 25%","本命":"entry-day immediate rise; add 75% following open","試し玉":"entry-day flat or other; keep 25%","見切り":"entry-day stall; exit following open","remaining_exit":"signal+3 session close","profit_target":"none","costs":"ignored","development":"2019-2023","validation":"2024-2026"},"authoritative_result":{"overall":overall.to_dict("records"),"validation_years":annual[annual.year>=2024].to_dict("records"),"japanese_tiers_validation":summary[summary.period.eq("validation")].to_dict("records"),"gate_checks":checks,"practical_policy":{"候補選定":"20日値幅が開発期上位10%かつ直前5日騰落が下位10%の急落反発型","初期玉":"翌日寄りで最大予定玉の25%","増玉":"翌日高値が寄りから+3%以上かつ安値が-3%を割らない即上昇なら翌々日寄りで75%追加","撤退":"翌日終値-2%以下または安値-3%以下の失速なら翌々日寄りで全撤退","期限":"それ以外は3営業日目終値で決済"}},"observed_branching":{"changed_top5_members_count":None,"changed_top10_members_count":None,"changed_rank_count":int(len(d)),"selection_divergence_reason":"entry-day path changes Japanese tier, size, and exit"},"judgment":{"candidate_local_decision":"keep" if keep else "hold","session_aggregate_decision":"keep_practical_long_rebound_policy" if keep else "hold_practical_long_policy","authoritative_rollup_decision":"keep_long_rebound_practical_actionability_v1_review_only" if keep else "hold_continue_long_practical_research","reason_type":"development_selected_all_years_positive_tail_breadth_gates"},"not_changed":["MeeMee","ranking","runtime DB","production logic","existing buy selector"],"remaining_risks":["costs ignored","2026 edge near zero","portfolio overlap not simulated","review-only no live reflection"]}
 (out/"compare.json").write_text(json.dumps(res,ensure_ascii=False,indent=2),encoding="utf-8");(out/"_ARTIFACT_COMPLETE.json").write_text(json.dumps({"complete":True,"authoritative":"compare.json"}));print(json.dumps(res["authoritative_result"],ensure_ascii=False))
if __name__=="__main__":main()
