from __future__ import annotations
import glob,json
from datetime import datetime,timezone
from pathlib import Path
AXIS_ID='leaf_operational_readiness_rollup_v1';OUT=Path(r'G:\Tradex\leaf_operational_readiness_rollup_v1')
def latest(p):q=Path(sorted(glob.glob(p))[-1]);return q,json.loads(q.read_text(encoding='utf-8'))
def run():
 op,od=latest(r'G:\Tradex\leaf_order_contract_readiness_v1\*\compare.json');cmp,cd=latest(r'G:\Tradex\leaf_vs_meemee_operational_stress_v1\*\compare.json');s=od['selected_operational_contract'];audit={'order_contract_fixed':True,'round_lot_checked':True,'unaffordable_policy_fixed':True,'cash_concurrency_within_10m':s['max_concurrent_invested_yen']<=1e7,'stress_10bp_pass':s['operational_gate_pass'],'test_pf_pass':s['test_money_profit_factor']>=1.5,'dd_pass':s['max_realized_drawdown_yen']>=-1500000,'all_years_positive':s['red_year_count']==0,'same_condition_meemee_comparison_present':True,'review_only_boundary':True}
 payload={'schema_version':f'{AXIS_ID}.rollup.v1','artifact_role':'authoritative','axis_id':AXIS_ID,'research_phase':'effectiveness_judgment','generated_at':datetime.now(timezone.utc).isoformat(),'operational_contract':{'entry':'next-session opening auction market order','maximum_adverse_fill_assumption':.001,'slot_budget_yen':2400000,'maximum_positions':4,'same_day_candidate_cap':3,'round_lot':100,'unaffordable_policy':'skip without rank4 promotion','ranking':'tie_gap_ma60 descending then code','tp':.08,'sl':.05,'max_hold_sessions':10},'authoritative_evidence':{'order_readiness_artifact':str(op),'same_condition_comparison_artifact':str(cmp),'selected_metrics':s},'completion_audit':audit,'decision':{'candidate_local_decision':'keep','session_aggregate_decision':'display_only_ready','authoritative_rollup_decision':'operationally_ready_review_only_leaf_cap4_slot2_4m','reason_type':'10bp stress, round-lot, affordability, cash, PF, DD, annual, and same-condition benchmark gates pass'},'runtime_db_write':False,'production_ranking_changed':False,'silent_fallback_used':False};root=OUT/f"{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}-{AXIS_ID}";root.mkdir(parents=True);p=root/'session_leaderboard_rollup.json';p.write_text(json.dumps(payload,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print(p)
if __name__=='__main__':run()
