from __future__ import annotations
import argparse,json,sys
from datetime import datetime,timezone
from pathlib import Path
import duckdb,pandas as pd
from tradex_long_trend_pullback_portfolio_v1 import simulate,portfolio_summary,COST

PRIORITIES=['均等順位','底反転優先','押し目優先']
def prioritized(events,name):
 z=events.copy();base=z.original_rank.astype(float)
 if name=='均等順位':z['rank']=base+z.family.map({'底反転':0.0,'押し目':0.1})
 elif name=='底反転優先':z['rank']=base+z.family.map({'底反転':0.0,'押し目':10.0})
 else:z['rank']=base+z.family.map({'底反転':10.0,'押し目':0.0})
 return z
def main():
 p=argparse.ArgumentParser();p.add_argument('--output',required=True);p.add_argument('--pullback',default=r'G:\Tradex\long_selector_10y_research_v1\20260626T054716Z-long_selector_10y_research_v1\strict_trend_pullback_top3_events.csv');p.add_argument('--reversal',default=r'G:\Tradex\long_selector_10y_research_v1\20260626T054716Z-long_selector_10y_research_v1\strict_bottom_reversal_top3_events.csv');a=p.parse_args();out=Path(a.output);out.mkdir(parents=True,exist_ok=False);sys.path[:0]=[str(Path.cwd()),str(Path.cwd()/'app')]
 from backend.services.codex_bridge_service import get_runtime_stock_db_status
 runtime=get_runtime_stock_db_status();frames=[]
 for family,path in [('押し目',a.pullback),('底反転',a.reversal)]:
  x=pd.read_csv(path,dtype={'code':str});x=x[['code','date','rank']].copy();x['family']=family;frames.append(x)
 src=pd.concat(frames,ignore_index=True);src['event_id']=range(len(src));src=src.rename(columns={'rank':'original_rank'})
 with duckdb.connect(runtime['selected_runtime_db_path'],read_only=True) as c:
  c.register('src',src);e=c.execute("""select * exclude(next_rn) from (select s.*,b.date entry_date,b.o entry_price,row_number() over(partition by s.event_id order by b.date) next_rn from src s join daily_bars b on b.code=s.code and b.date>s.date) where next_rn=1""").fetchdf();c.register('events',e)
  events=c.execute("""select * exclude(exit_rn) from (select e.*,i.market_code,b.date exit_date,b.c exit_price,row_number() over(partition by e.event_id order by b.date) exit_rn from events e join industry_master i using(code) join daily_bars b on b.code=e.code and b.date>=e.entry_date where i.market_code in ('プライム（内国株式）','スタンダード（内国株式）','グロース（内国株式）')) where exit_rn=20""").fetchdf()
 events['signal_dt']=pd.to_datetime(events.date,unit='s');events['year']=events.signal_dt.dt.year;rows=[];ledgers={}
 for priority in PRIORITIES:
  t=simulate(prioritized(events,priority),5);t['year']=pd.to_datetime(t.signal_date if 'signal_date' in t else t.date,unit='s').dt.year;ledgers[priority]=t;dev=t[t.year.between(2016,2023)];val=t[t.year.between(2024,2025)];rows.append({'priority':priority,'development':portfolio_summary(dev),'validation_2024_2025':portfolio_summary(val),'validation_years':{str(y):portfolio_summary(val[val.year.eq(y)]) for y in [2024,2025]},'family_mix_development':dev.family.value_counts().to_dict(),'family_mix_validation':val.family.value_counts().to_dict(),'accepted_rate':len(t)/len(events)})
 eligible=[x for x in rows if x['development']['trades']>=250 and x['development']['raw_trade_metrics']['mean_return_pct']>0 and x['development']['raw_trade_metrics']['win_rate']>=.50 and x['development']['capital_contribution_metrics']['severe_loss5_rate']<=.03 and x['development']['positive_month_rate']>.50 and x['development']['positive_year_rate']>=.75 and x['development']['capital_contribution_metrics']['top3_positive_profit_share']<=.35 and x['validation_2024_2025']['raw_trade_metrics']['mean_return_pct']>0 and x['validation_2024_2025']['raw_trade_metrics']['win_rate']>=.50 and x['validation_2024_2025']['capital_contribution_metrics']['severe_loss5_rate']<=.03 and x['validation_2024_2025']['positive_month_rate']>.50 and x['validation_2024_2025']['capital_contribution_metrics']['top3_positive_profit_share']<=.35 and all(v['total_return_pct']>0 for v in x['validation_years'].values())]
 chosen=max(eligible,key=lambda x:(x['validation_2024_2025']['total_return_pct'],x['development']['total_return_pct'])) if eligible else None;test=ledgers[chosen['priority']] if chosen else pd.DataFrame();test=test[test.year.eq(2026)] if len(test) else test;sm=portfolio_summary(test);severe=sm['capital_contribution_metrics']['severe_loss5_rate'];conc=sm['capital_contribution_metrics']['top3_positive_profit_share'];win=sm['raw_trade_metrics']['win_rate'];checks={'selected_without_2026':chosen is not None,'test_n250_or_full_audit':chosen is not None,'test_raw_mean_positive':sm['raw_trade_metrics']['mean_return_pct'] is not None and sm['raw_trade_metrics']['mean_return_pct']>0,'test_win_at_least_50pct':win is not None and win>=.50,'test_capital_loss5_at_most_3pct':severe is not None and severe<=.03,'test_months_majority_positive':sm['positive_month_rate'] is not None and sm['positive_month_rate']>.50,'profit_not_concentrated':conc is not None and conc<=.35,'test_total_return_positive':sm['total_return_pct']>0};decision='hold_for_baseline_and_mark_to_market_gate' if all(checks.values()) else 'drop'
 payload={'schema_version':'tradex_long_two_family_portfolio_v1.compare.v1','artifact_role':'authoritative','generated_at':datetime.now(timezone.utc).isoformat(),'runtime':runtime,'fixed_evaluation_conditions':{'sources':{'押し目':a.pullback,'底反転':a.reversal},'source_events':len(src),'ordinary_mature_events':len(events),'universe':'ordinary domestic stocks only: Prime, Standard, Growth','entry':'next session open','exit':'session-20 close','round_trip_cost_pct':COST,'portfolio':'max 5, equal 20% slots, no same-code overlap','axis_changed':'same-day family priority only','priority_candidates':PRIORITIES,'development':'2016-2023','validation':'2024-2025','full_audit_test':'2026 matured events','production_changed':False},'authoritative_result':{'candidates':rows,'eligible_without_2026':eligible,'chosen_without_2026':chosen,'test_2026':sm,'test_family_mix':test.family.value_counts().to_dict() if len(test) else {},'checks':checks},'observed_branching':{'changed_top5_members_count':None,'changed_top10_members_count':None,'changed_rank_count':sm['trades'],'selection_divergence_reason':'two independent families compete for fixed capital slots'},'judgment':{'candidate_local_decision':decision,'authoritative_rollup_decision':decision,'reason_type':'two_family_capital_allocation_gate'},'remaining_risks':['same-condition baseline and mark-to-market drawdown pending only if test passes']}
 if len(test):test.to_parquet(out/'test_2026_portfolio_ledger.parquet',index=False)
 (out/'compare.json').write_text(json.dumps(payload,ensure_ascii=False,indent=2,default=str),encoding='utf-8');(out/'_ARTIFACT_COMPLETE.json').write_text(json.dumps({'complete':True,'authoritative':'compare.json'}),encoding='utf-8');print(json.dumps({'ordinary_events':[len(events),len(src)],'eligible_count':len(eligible),'chosen':chosen,'test':sm,'test_family_mix':payload['authoritative_result']['test_family_mix'],'checks':checks,'decision':decision},ensure_ascii=False))
if __name__=='__main__':main()
