"""Authoritative rollup for human-SELL/model-AVOID loss avoidance research."""
import argparse,hashlib,json
from pathlib import Path
def load(p):return json.loads(Path(p).read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--support',type=Path,required=True);ap.add_argument('--localbox-discovery',type=Path,required=True);ap.add_argument('--localbox-validation',type=Path,required=True);ap.add_argument('--sample',type=Path,required=True);ap.add_argument('--output',type=Path,required=True);a=ap.parse_args();a.output.mkdir(parents=True,exist_ok=False)
 support=load(a.support);disc=load(a.localbox_discovery);val=load(a.localbox_validation);sample=load(a.sample);res=val['authoritative_results'];metric_keys={'D','R','N','mean_fixed3_pct','profit_factor','max_loss_pct','max_drawdown_units_pct','max_loss_streak','max_concurrent','n'};req={'support_prior20_pit_axis_completed':support['judgment']['authoritative_rollup_decision']=='drop','localbox_candidate_fixed_before_unused_validation':disc['judgment']['authoritative_rollup_decision']=='hold_pending_unused_human_validation','unused_distinct_sample_ge_30':sample['fixed_conditions']['one_case_per_code'] and sample['bucket_counts'] and sum(sample['bucket_counts'].values())>=30,'human_model_gate_disagreement_metrics_complete':all(metric_keys.issubset(res[k]) for k in ['human_alone','model_alone','complement_union','human_sell_model_avoid','human_nosell_model_sell']),'stage_breadth_present':bool(val['by_model_action']),'environment_breadth_covers_32':sum(x['n'] for x in val['by_environment'].values())==32,'weekly_excluded':not val['fixed_conditions']['weekly_inputs'],'next_open_h5_fixed3_cost0':val['fixed_conditions']['execution']=='next_session_open' and val['fixed_conditions']['horizon_sessions']==5 and val['fixed_conditions']['costs']=='ignored','no_auto_reflection':all(x in val['not_changed'] for x in ['MeeMee','ranking','runtime DB','production trading logic'])}
 if not all(req.values()):raise RuntimeError({k:v for k,v in req.items() if not v})
 result={'schema_version':'tradex_human_model_avoid_goal_rollup_v1.compare.v1','artifact_role':'authoritative_goal_completion_rollup','review_only':True,'research_phase':'effectiveness_judgment','fixed_conditions':val['fixed_conditions'],'current_champion':'none_on_fresh32','axis_decisions':{'prior20_support_break':support['judgment'],'localbox_lower_half_discovery':disc['judgment'],'localbox_lower_half_unused_validation':val['judgment']},'authoritative_results':res,'observed_branching':val['observed_branching'],'direction_pairs':val['direction_pairs'],'by_model_action':val['by_model_action'],'by_environment':val['by_environment'],'completion_requirements':req,'judgment':{'candidate_local_decision':{'support_break':'drop','localbox_lower_half':'drop'},'session_aggregate_decision':'research_complete_no_gate_kept','authoritative_rollup_decision':'research_complete_no_automatic_reflection','reason':'the local-box lower-half split perfectly removed discovery R but failed fresh blind validation; R rate and maximum loss did not improve and model expectancy was negative'},'next_axis_candidate':{'decision':'hold_research_only','axis':'market/year regime conditioning before any further human/model disagreement gate','reason':'model alone changed from positive in the prior fresh32 to negative in this fresh32, so regime instability now dominates local geometry'},'not_changed':['MeeMee','ranking','runtime DB','production trading logic']};cp=a.output/'compare.json';cp.write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');audit={'requirements':req,'all_requirements_pass':all(req.values()),'sources':{n:{'path':str(getattr(a,n)),'sha256':sha(getattr(a,n))} for n in ['support','localbox_discovery','localbox_validation','sample']},'weekly_columns_used':[],'runtime_writes':0,'automatic_reflection':False,'compare_sha256':sha(cp)};apath=a.output/'audit.json';apath.write_text(json.dumps(audit,indent=2)+'\n',encoding='utf-8');(a.output/'_ARTIFACT_COMPLETE.json').write_text(json.dumps({'complete':True,'authoritative':'compare.json','sha256':sha(cp)},indent=2)+'\n',encoding='utf-8');print(json.dumps({'output':str(a.output),'requirements':req,'judgment':result['judgment'],'next':result['next_axis_candidate']},ensure_ascii=False,indent=2))
if __name__=='__main__':main()
