from __future__ import annotations
import glob,json,math
from datetime import datetime,timezone
from pathlib import Path
import pandas as pd
AXIS_ID='leaf_lot_rounding_slippage_v1';OUT=Path(r'G:\Tradex\leaf_lot_rounding_slippage_v1');SLOTS=(2_300_000,2_400_000);SLIPPAGE=(0,.001,.002)
def replay(x,slot,slip):
 z=x.copy();z['fill_price']=z.entry_price*(1+slip);z['shares']=(z.fill_price.rdiv(slot/100).apply(math.floor)*100).astype(int);z['invested_yen']=z.shares*z.fill_price;z['exit_price']=z.entry_price*(1+z.next_open_return);z['pnl_yen']=z.shares*(z.exit_price-z.fill_price);z=z[z.shares>0];daily=z.groupby('exit_date').pnl_yen.sum().sort_index();eq=1e7+daily.cumsum();dd=eq-eq.cummax();pos=z.loc[z.pnl_yen>0,'pnl_yen'].sum();neg=-z.loc[z.pnl_yen<0,'pnl_yen'].sum();annual=z.groupby('year').pnl_yen.sum();recent=z[z.year>=2024];rpos=recent.loc[recent.pnl_yen>0,'pnl_yen'].sum();rneg=-recent.loc[recent.pnl_yen<0,'pnl_yen'].sum();rpf=float(rpos/rneg);return {'slot_yen':slot,'slippage_rate':slip,'trade_count':len(z),'mean_invested_yen':float(z.invested_yen.mean()),'maximum_invested_per_position_yen':float(z.invested_yen.max()),'pnl_2024_2025_yen':float(recent.pnl_yen.sum()),'net_pnl_yen':float(z.pnl_yen.sum()),'ending_capital_yen':float(1e7+z.pnl_yen.sum()),'all_money_profit_factor':float(pos/neg),'test_2024_2025_money_profit_factor':rpf,'max_realized_drawdown_yen':float(dd.min()),'annual_pnl_yen':{str(int(y)):float(v) for y,v in annual.items()},'red_year_count':int((annual<=0).sum()),'target_pass':bool(recent.pnl_yen.sum()>4964781 and rpf>=1.5 and dd.min()>=-1500000 and (annual>0).all())}
def run():
 source=Path(sorted(glob.glob(r'G:\Tradex\leaf_position_cap_axis_v1\*\selected_events.csv'))[-1]);x=pd.read_csv(source);rows=[replay(x,s,k) for s in SLOTS for k in SLIPPAGE];base=[r for r in rows if r['slippage_rate']==0 and r['target_pass']];stress=[r for r in rows if r['slippage_rate']==.001 and r['target_pass']];selected=max(stress,key=lambda r:r['slot_yen'],default=None)
 root=OUT/f"{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}-{AXIS_ID}";root.mkdir(parents=True);payload={'schema_version':f'{AXIS_ID}.compare.v1','artifact_role':'authoritative','axis_id':AXIS_ID,'research_phase':'effectiveness_judgment','fixed_evaluation_conditions':{'source':str(source),'shape_exit_rank_cap_unchanged':True,'maximum_positions':4,'round_lot_shares':100,'slot_sizes':SLOTS,'entry_adverse_slippage':SLIPPAGE,'exit_price_contract':'original simulated exit price; adverse entry fill reduces realized return','costs_other_than_slippage':'not modeled'},'variants':rows,'selection':{'protocol':'largest slot passing all target gates under 10bp adverse entry slippage','selected_slot_yen':selected['slot_yen'] if selected else None,'selected':selected},'decision':{'candidate_local_decision':'keep_for_display_only_readiness' if selected else ('keep_zero_slippage_only' if base else 'drop'),'authoritative_rollup_decision':'research_only','reason_type':'round_lot_and_entry_slippage_operational_stress'},'runtime_db_write':False,'production_ranking_changed':False,'silent_fallback_used':False};(root/'compare.json').write_text(json.dumps(payload,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print(root/'compare.json')
if __name__=='__main__':run()
