from __future__ import annotations
import argparse,json
from pathlib import Path
import pandas as pd
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--metrics",required=True);ap.add_argument("--yearly",required=True);ap.add_argument("--output",required=True);a=ap.parse_args();out=Path(a.output);out.mkdir(parents=True,exist_ok=False);m=pd.read_parquet(a.metrics);yr=pd.read_parquet(a.yearly);dev=m[m.period.eq("development")];ok=dev[(dev.mean_return_pct>0)&(dev.severe_loss5_rate<=.05)].sort_values("holding_days");selected=None if ok.empty else int(ok.iloc[0].holding_days);v=m[(m.period.eq("validation"))&m.holding_days.eq(selected)] if selected else m.iloc[0:0];yy=yr[(yr.year>=2024)&yr.holding_days.eq(selected)] if selected else yr.iloc[0:0];checks={"selected_on_development_only":selected is not None,"shortest_positive_tail5_selected":selected==3,"validation_positive":bool(len(v)==1 and v.iloc[0].mean_return_pct>0),"validation_tail_le5":bool(len(v)==1 and v.iloc[0].severe_loss5_rate<=.05),"all_validation_years_positive":bool(len(yy)==3 and (yy.mean_return_pct>0).all()),"validation_n_ge5000":bool(len(v)==1 and v.iloc[0].n>=5000)};keep=all(checks.values())
 pd.concat([m[m.holding_days.eq(selected)],yr[yr.holding_days.eq(selected)]],ignore_index=True,sort=False).to_parquet(out/"selected_risk_first_holding_metrics.parquet",index=False)
 res={"schema_version":"tradex_long_rebound_risk_first_holding_v1.compare.v1","artifact_role":"authoritative_long_rebound_risk_first_holding","review_only":True,"fixed_conditions":{"family":"急落反発","entry":"next open 25%","add":"immediate rise following open to 100%","stall":"following open exit","selection":"shortest development-positive horizon with severe-loss>=5% rate <=5%","horizon_candidates":[2,3,4,5],"development":"2019-2023","validation":"2024-2026","costs":"ignored"},"authoritative_result":{"selected_holding_days":selected,"development":m[(m.period.eq("development"))&m.holding_days.eq(selected)].to_dict("records"),"validation":v.to_dict("records"),"validation_years":yy.to_dict("records"),"gate_checks":checks},"observed_branching":{"changed_top5_members_count":None,"changed_top10_members_count":None,"changed_rank_count":0,"selection_divergence_reason":"risk-first horizon selection changes management only"},"judgment":{"candidate_local_decision":"keep" if keep else "hold","session_aggregate_decision":"keep_rebound_risk_first_holding" if keep else "hold_rebound_risk_first_holding","authoritative_rollup_decision":"keep_long_rebound_risk_first_3day_v1_review_only" if keep else "hold_no_practical_risk_first_horizon","reason_type":"development_selected_positive_all_years_tail_breadth_gates"},"not_changed":["family","entry","size","path rules","MeeMee","ranking","runtime DB","production logic"]}
 (out/"compare.json").write_text(json.dumps(res,ensure_ascii=False,indent=2),encoding="utf-8");(out/"_ARTIFACT_COMPLETE.json").write_text(json.dumps({"complete":True,"authoritative":"compare.json"}));print(json.dumps(res["authoritative_result"],ensure_ascii=False))
if __name__=="__main__":main()
