"""One-axis refinement: MA7 close break after lower-high W-top full erasure."""
from __future__ import annotations
import argparse,json
from datetime import datetime,timezone
from pathlib import Path
import pandas as pd
def rates(x):return {"n":int(len(x)),"down_first":None if x.empty else float(x.label.eq(0).mean()),"rebound_first":None if x.empty else float(x.label.eq(1).mean()),"neutral":None if x.empty else float(x.label.eq(2).mean())}
def main():
 p=argparse.ArgumentParser();p.add_argument("--wtop-ledger",type=Path,required=True);p.add_argument("--features",type=Path,required=True);p.add_argument("--output-root",type=Path,required=True);a=p.parse_args();stamp=datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ");out=a.output_root/f"{stamp}-tradex-uptrend-full-erasure-wtop-ma7-break-oos-v1";out.mkdir(parents=True,exist_ok=False)
 b=pd.read_parquet(a.wtop_ledger);base=b[b.wtop.fillna(False)];f=pd.read_parquet(a.features,columns=["code","ymd","cross_ma7"]);x=base.merge(f,on=["code","ymd"],how="left",validate="one_to_one");q=x[x.cross_ma7.fillna(0).astype(bool)];years={str(y):{"champion":rates(x[x.year.eq(y)]),"challenger":rates(q[q.year.eq(y)])} for y in range(2019,2027)};overall={"champion":rates(x),"challenger":rates(q)};quality=all(v["challenger"]["n"]==0 or v["challenger"]["down_first"]>v["challenger"]["rebound_first"] for v in years.values());breadth=all(years[str(y)]["challenger"]["n"]>=10 for y in (2023,2024,2025));decision="keep" if quality and breadth else "drop";anchor=x[(x.code.astype(str).str.zfill(4)=="2802")&x.ymd.eq(20240206)]
 data={"schema_version":"tradex_uptrend_full_erasure_wtop_ma7_break_oos_v1.compare.v1","artifact_role":"authoritative","axis":"add same-day MA7 close break to lower-high W-top full erasure","fixed_conditions":{"base":"monthly UPTREND + full erasure + confirmed lower-high W-top","only_changed_axis":"cross_ma7","outcome":"symmetric fixed 3% h5"},"year_results":years,"overall":overall,"human_anchor_2802":anchor[["code","ymd","wtop","cross_ma7","label"]].where(pd.notna(anchor),None).to_dict("records"),"judgment":{"decision":decision,"quality_pass_all_years":quality,"breadth_pass_2023_2025":breadth,"reason":"MA7 break refinement must have down dominance every year and sufficient recent breadth"},"not_changed":["W-top/full-erasure","monthly environment","MA20","entry lifecycle","MeeMee","ranking","runtime DB"]};(out/"compare.json").write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");x.to_parquet(out/"uptrend_full_erasure_wtop_ma7_break_ledger.parquet",index=False);audit={"base_rows":int(len(x)),"challenger_rows":int(len(q)),"missing_cross":int(x.cross_ma7.isna().sum()),"duplicates":int(x.duplicated(["code","ymd"]).sum()),"future_used_for_selection":False,"review_only":True};(out/"audit.json").write_text(json.dumps(audit,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");(out/"_ARTIFACT_COMPLETE.json").write_text(json.dumps({"complete":True,"authoritative":"compare.json"},indent=2)+"\n",encoding="utf-8");print(out);print(json.dumps({"years":years,"overall":overall,"anchor":data["human_anchor_2802"],"judgment":data["judgment"],"audit":audit},ensure_ascii=False,indent=2))
if __name__=="__main__":main()
