from __future__ import annotations

import argparse,hashlib,inspect,json
from datetime import datetime,timezone
from pathlib import Path
import duckdb,pandas as pd
from tradex_long_fresh_family_events_v1 import add_scores
from tradex_long_fresh_final_practical_v1 import prepare,routed
from tradex_long_trend_pullback_portfolio_v1 import simulate

ALLOWED={'プライム（内国株式）','スタンダード（内国株式）','グロース（内国株式）'}
FORBIDDEN_SCORE_TOKENS=['p1_','p2_','p3_','p4_','p5_','p10_','p20_','realized_ret','exit_']
def sha(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()

def main():
 p=argparse.ArgumentParser();p.add_argument('--output',required=True);p.add_argument('--final-artifact',type=Path,required=True);a=p.parse_args();out=Path(a.output);out.mkdir(parents=True,exist_ok=False);cmp=json.loads((a.final_artifact/'compare.json').read_text(encoding='utf-8'));cond=cmp['fixed_evaluation_conditions'];res=cmp['authoritative_result'];db=Path(cond['runtime_db']);events_path=Path(cond['source']);events=prepare(events_path);breakout=sorted(events.family.unique())[0];selected_events=routed(events,breakout,float(res['chosen_router_without_2026']));accepted=simulate(selected_events,20).reset_index(drop=True);accepted['trade_id']=accepted.index.astype('int64');ledger=pd.read_parquet(a.final_artifact/'final_trade_ledger.parquet');daily=pd.read_parquet(a.final_artifact/'final_daily_nav.parquet')
 with duckdb.connect(str(db),read_only=True) as c:
  latest=int(c.execute('select max(date) from daily_bars').fetchone()[0]);codes=pd.DataFrame({'code':events.code.astype(str).unique()});c.register('event_codes',codes);markets=c.execute('select distinct e.code,i.name,i.market_code from event_codes e left join industry_master i using(code)').fetchdf()
 market_by_code=markets.groupby('code').market_code.apply(lambda x:set(x.dropna())).to_dict();names_by_code=markets.groupby('code').name.apply(lambda x:' '.join(x.dropna().astype(str))).to_dict();bad_codes=sorted(code for code in codes.code if not market_by_code.get(code) or not market_by_code[code].issubset(ALLOWED) or '種類株' in names_by_code.get(code,'') or '優先株' in names_by_code.get(code,''))
 score_source=inspect.getsource(add_scores);forbidden_found=[x for x in FORBIDDEN_SCORE_TOKENS if x in score_source]
 expected=accepted[pd.to_datetime(accepted.exit_date,unit='s').dt.year.eq(2026)][['code','entry_date','exit_date','family']].sort_values(['code','entry_date','exit_date','family']).reset_index(drop=True);actual=ledger[pd.to_datetime(ledger.exit_date,unit='s').dt.year.eq(2026)][['code','entry_date','exit_date','family']].sort_values(['code','entry_date','exit_date','family']).reset_index(drop=True)
 overlap=False
 for _,g in ledger.sort_values(['code','entry_date']).groupby('code'):
  if len(g)>1 and bool((g.entry_date.iloc[1:].to_numpy()<=g.exit_date.iloc[:-1].to_numpy()).any()):overlap=True;break
 raw_recalc=100*(ledger.exit_price/ledger.entry_price-1)-.3
 # Corporate-action guard: adjusted close paths should not contain a one-day 50% discontinuity.
 keys=accepted[['trade_id','code','entry_date','exit_date']];
 with duckdb.connect(str(db),read_only=True) as c:
  c.register('keys',keys);paths=c.execute('select k.trade_id,b.date,b.c from keys k join daily_bars b on b.code=k.code and b.date between k.entry_date and k.exit_date order by k.trade_id,b.date').fetchdf()
 paths['ret1']=paths.groupby('trade_id').c.pct_change();max_jump=float(paths.ret1.abs().max());test_ledger=ledger[pd.to_datetime(ledger.exit_date,unit='s').dt.year.eq(2026)].copy();top=test_ledger.nlargest(3,'pnl')[['code','family','entry_date','exit_date','raw_return_pct','pnl']].to_dict('records')
 final_checks=res['checks'];checks={'final_rollup_checks_all_true':all(final_checks.values()),'db_exists':db.exists(),'db_latest_is_2026_07_17':latest==1784246400,'ordinary_market_allowlist_exact':not bad_codes,'score_has_no_future_or_outcome_tokens':not forbidden_found,'router_uses_signal_date_market_fields':cond['market_strength']=='0.5*market_breadth_ma20 + 0.5*market_advancers_ratio, signal-date values only','entry_strictly_after_signal_for_all_source_events':bool((events.entry_date>events.date).all()),'exit_strictly_after_entry_for_selected_events':bool((accepted.exit_date>accepted.entry_date).all()),'all_2026_accepted_exits_present_in_final_ledger':expected.equals(actual),'no_same_code_position_overlap':not overlap,'raw_return_reconciles_with_cost':bool((raw_recalc-ledger.raw_return_pct).abs().max()<1e-9),'daily_nav_finite_and_positive':bool(daily.nav.notna().all() and (daily.nav>0).all()),'max_positions_at_most_20':int(daily.positions_before_exit.max())<=20,'max_exposure_at_most_100pct':float(daily.max_intraday_exposure.max())<=1+1e-9,'no_50pct_single_day_path_discontinuity':max_jump<.5,'artifact_completion_marker_present':(a.final_artifact/'_ARTIFACT_COMPLETE.json').exists(),'production_unchanged':cond['production_changed'] is False}
 decision='practical_review_only' if all(checks.values()) else 'hold';payload={'schema_version':'tradex_long_fresh_adoption_audit_v1.audit.v1','artifact_role':'authoritative','generated_at':datetime.now(timezone.utc).isoformat(),'source_final_artifact':str(a.final_artifact),'source_hashes':{'final_compare_sha256':sha(a.final_artifact/'compare.json'),'family_event_script_sha256':sha(Path(__file__).with_name('tradex_long_fresh_family_events_v1.py')),'final_rollup_script_sha256':sha(Path(__file__).with_name('tradex_long_fresh_final_practical_v1.py')),'compounded_replay_script_sha256':sha(Path(__file__).with_name('tradex_long_fresh_compounded_portfolio_v1.py'))},'authoritative_result':{'checks':checks,'final_rollup_checks':final_checks,'bad_ordinary_market_codes':bad_codes,'forbidden_score_tokens_found':forbidden_found,'expected_2026_accepted_exits':len(expected),'audited_2026_ledger_exits':len(actual),'max_single_day_abs_return_in_holding_paths':max_jump,'top3_test_profit_trades':top,'final_candidate':res['final_candidate'],'same_condition_baseline':res['baseline_all_families_equal20']},'judgment':{'candidate_local_decision':decision,'session_aggregate_decision':decision,'authoritative_rollup_decision':decision,'reason_type':'independent_point_in_time_execution_and_artifact_audit'},'scope':'TRADEX review-only research result; no MeeMee or runtime ranking reflection','remaining_risks':['daily OHLC research cannot model intraday liquidity or borrow constraints; long entry uses next open and exit uses close','raw trade loss rate is diagnostic and remains materially above 3%; the explicit 3% gate is satisfied on portfolio-capital contribution under verified sizing']}
 (out/'audit.json').write_text(json.dumps(payload,ensure_ascii=False,indent=2,default=str),encoding='utf-8');(out/'_ARTIFACT_COMPLETE.json').write_text(json.dumps({'complete':True,'authoritative':'audit.json'}),encoding='utf-8');print(json.dumps({'checks':checks,'decision':decision,'expected_test':len(expected),'actual_test':len(actual),'max_jump':max_jump,'bad_codes':bad_codes,'forbidden':forbidden_found},ensure_ascii=False))
if __name__=='__main__':main()
