from __future__ import annotations
import argparse
from datetime import datetime,timezone
from pathlib import Path
import numpy as np,pandas as pd
from scripts.tradex_early_signal_first_detect_v1 import _metrics,_branching
from scripts.tradex_sell_support_break_breadth_current_contract_v1 import load,outcomes,select
from scripts.tradex_shallow_high_zone_universe_repair_v1 import _sha,_write,extra_metrics
AXIS_ID='tradex_sell_climax_failure_current_contract_v1';OUT=Path(r'G:\Tradex\tradex_sell_climax_failure_current_contract_v1');VARIANTS=('volume_ratio','ret20','close_pos');PERIODS={'train':(20240101,20241231),'validation':(20250101,20251231),'shadow':(20260101,20261231)}
def shape_frame(f:pd.DataFrame,b:pd.DataFrame)->pd.DataFrame:
 parts=[]
 for _,p in b.groupby('code',sort=False):
  p=p.sort_values('signal_ymd').copy();p['c20']=p.c.shift(20);p['av20']=p.v.shift(1).rolling(20,20).mean();parts.append(p)
 x=pd.concat(parts,ignore_index=True).merge(f,on=['signal_ymd','code'],how='inner',validate='one_to_one');x['ret20']=x.c/x.c20-1;x['volume_ratio']=x.v/x.av20;x['close_pos']=(x.c-x.l)/(x.h-x.l);x['family_hit']=(x.ret20>=.20)&(x.volume_ratio>=3)&(x.c<x.o)&(x.close_pos<=.35);return x
def score(x:pd.DataFrame,variant:str)->pd.DataFrame:
 z=x.copy();q={'volume_ratio':z.volume_ratio,'ret20':z.ret20,'close_pos':-z.close_pos}[variant].replace([np.inf,-np.inf],np.nan).fillna(-9);z['score']=z.family_hit.astype(float)*100+q.clip(-10,10);z=z.sort_values(['signal_ymd','score','code'],ascending=[True,False,True]);z['rank']=z.groupby('signal_ymd').cumcount()+1;z['percentile']=1-(z['rank']-1)/z.groupby('signal_ymd').code.transform('size');z['top10']=z['rank']<=10;z['side']='SELL';return z
def generate(db:Path,out:Path)->Path:
 f,b,r,cov=load(db);base=shape_frame(f,b);cal=sorted(base[base.signal_ymd>=20240101].signal_ymd.unique());td=sum(d<=20241231 for d in cal);variants=[];sets={}
 for v in VARIANTS:
  s=outcomes(score(base,v),b);s=s[s.signal_ymd>=20240101];e=select(s,True,cal,'rank');m=_metrics(e[e.signal_ymd<=20241231],td);variants.append({'priority':v,'train_metrics':m});sets[v]=(s,e)
 ok=[v for v in variants if (v['train_metrics']['expectancy'] or 0)>0 and v['train_metrics']['profit_factor'] is not None and v['train_metrics']['signals_per_week']>=1];pool=ok or [v for v in variants if v['train_metrics']['profit_factor'] is not None]
 if not pool:raise ValueError('NO_2024_VARIANT_WITH_METRICS')
 chosen=max(pool,key=lambda v:(v['train_metrics']['profit_factor'],v['train_metrics']['expectancy']));chosen['train_selection_gate_pass']=bool(ok);s,e=sets[chosen['priority']];s['split']=np.select([s.signal_ymd<20250101,s.signal_ymd<20260101],['train','validation'],default='shadow');elig=s[s.family_hit][['signal_ymd']].drop_duplicates();mm=r.merge(elig,on='signal_ymd',how='inner').merge(s[['signal_ymd','code','trade_return_h10','exit_day_h10','target_before_stop20','realized_mover20']],on=['signal_ymd','code'],how='left');mm['family_hit']=True;mm=select(mm.rename(columns={'baseline_rank':'rank'}),False,cal,'rank');latest=int(f.signal_ymd.max());periods={**PERIODS,'shadow':(20260101,latest)};metrics={};gates={};branch={};coverage={}
 for split,(a,z) in periods.items():
  days=sum(a<=d<=z for d in cal);ch=e[e.signal_ymd.between(a,z)];bl=mm[mm.signal_ymd.between(a,z)];allx=s[s.signal_ymd.between(a,z)&s.trade_return_h10.notna()];cm={**_metrics(ch,days),**extra_metrics(ch,allx)};bm={**_metrics(bl,days),**extra_metrics(bl,allx)};metrics[split]={'climax_failure_top1':cm,'meemee_sell_same_eligible_top1':bm};gates[split]={'pf_ge_1_30':(cm['profit_factor'] or 0)>=1.3,'expectancy_positive':(cm['expectancy'] or 0)>0,'frequency_ge_1_week':cm['signals_per_week']>=1,'pf_improves':cm['profit_factor'] is not None and bm['profit_factor'] is not None and cm['profit_factor']>bm['profit_factor'],'expectancy_improves':cm['expectancy'] is not None and bm['expectancy'] is not None and cm['expectancy']>bm['expectancy'],'cvar_non_degrade':cm['cvar10'] is not None and bm['cvar10'] is not None and cm['cvar10']>=bm['cvar10'],'dd_non_degrade':cm['max_drawdown'] is not None and bm['max_drawdown'] is not None and cm['max_drawdown']>=bm['max_drawdown']};branch[split]=_branching(s[s.top10],r.assign(side='SELL'),'SELL',a,z);cnt=s[s.signal_ymd.between(a,z)].groupby('signal_ymd').size();coverage[split]={'days':len(cnt),'min_ranked':int(cnt.min()),'all_days_ranked':bool(cnt.gt(0).all()),'eligible_days':int(elig.signal_ymd.between(a,z).sum())}
 root=out/f"{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}-{AXIS_ID}";root.mkdir(parents=True,exist_ok=False);s.to_parquet(root/'all_symbol_daily_sell_scores.parquet',index=False);e.to_parquet(root/'sell_entry_ledger.parquet',index=False);mm.to_parquet(root/'meemee_sell_baseline_ledger.parquet',index=False);keep=bool(chosen['train_selection_gate_pass'] and all(all(gates[x].values()) for x in ('validation','shadow')));payload={'schema_version':AXIS_ID+'.compare.v1','artifact_role':'authoritative','research_phase':'effectiveness_judgment','fixed_evaluation_conditions':{'shape':'ret20>=20%; volume>=3x prior20; bearish candle; close_pos<=.35','shape_audit':'PIT safe; future columns excluded','priority_variants_train_only':['volume_ratio desc','ret20 desc','close_pos asc'],'ranking':'all feature-covered historical PAN daily SELL rank; nonhits included; completed hit top1 entry','entry_exit':'next-open TP8/SL5/H10/10bp; gap-through actual open; reentry prohibited','baseline':'MeeMee SELL top1 exact eligible days','survivorship_filter':False,'fallback':False},'source_artifacts':[{'path':str(db),'sha256':_sha(db)}],'source_coverage':cov,'train_variants':variants,'selected_variant':chosen,'metrics':metrics,'adoption_gates':gates,'branching':branch,'rank_coverage':coverage,'decision':{'candidate_local_decision':'keep' if keep else 'drop','authoritative_rollup_decision':'review_only'},'shadow_tuning_used':False,'silent_fallback_used':False,'runtime_db_write':False,'production_ranking_changed':False,'meemee_changed':False};p=root/'compare.json';_write(p,payload);_write(root/'_ARTIFACT_COMPLETE.json',{'complete':True,'compare':str(p)});return p
def main():
 p=argparse.ArgumentParser();p.add_argument('--db',type=Path,required=True);p.add_argument('--out',type=Path,default=OUT);a=p.parse_args();print(generate(a.db,a.out))
if __name__=='__main__':main()
