"""One-axis follow-up: lower wick >=40% after long-MA touch-hold."""
from __future__ import annotations
import argparse,json
from datetime import datetime,timezone
from pathlib import Path
import pandas as pd
def rates(x):return {"n":int(len(x)),"further_down_first":None if x.empty else float(x.label.eq(0).mean()),"rebound_first":None if x.empty else float(x.label.eq(1).mean()),"neutral":None if x.empty else float(x.label.eq(2).mean())}
def main():
 p=argparse.ArgumentParser();p.add_argument("--ma-hold-ledger",type=Path,required=True);p.add_argument("--features",type=Path,required=True);p.add_argument("--output-root",type=Path,required=True);a=p.parse_args();stamp=datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ");out=a.output_root/f"{stamp}-tradex-profit-take-long-ma-hold-lower-wick-oos-v1";out.mkdir(parents=True,exist_ok=False)
 b=pd.read_parquet(a.ma_hold_ledger);f=pd.read_parquet(a.features,columns=["code","ymd","lower_wick_ratio"]);x=b.merge(f,on=["code","ymd"],how="left",validate="one_to_one");q=x[x.lower_wick_ratio.ge(.40)];years={str(y):{"champion":rates(x[x.year.eq(y)]),"challenger":rates(q[q.year.eq(y)])} for y in range(2019,2027)};overall={"champion":rates(x),"challenger":rates(q)};stable=all(v["challenger"]["n"]==0 or v["challenger"]["rebound_first"]>v["challenger"]["further_down_first"] for v in years.values());improved=overall["challenger"]["rebound_first"]>overall["champion"]["rebound_first"] and overall["challenger"]["further_down_first"]<overall["champion"]["further_down_first"];decision="keep" if stable and improved else "drop"
 data={"schema_version":"tradex_profit_take_long_ma_hold_lower_wick_oos_v1.compare.v1","artifact_role":"authoritative","axis":"add lower_wick_ratio>=0.40 to long-MA touch-hold profit candidate","threshold_provenance":"existing rejection-veto contract","year_results":years,"overall":overall,"judgment":{"decision":decision,"stable_all_years":stable,"improved_overall":improved,"reason":"lower-wick add-on must improve aggregate and preserve rebound dominance each year"},"not_changed":["MA touch-hold definition","position path","below7","MeeMee","ranking","runtime DB"]};(out/"compare.json").write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");q.to_parquet(out/"profit_take_long_ma_hold_lower_wick_ledger.parquet",index=False);audit={"base_rows":int(len(x)),"challenger_rows":int(len(q)),"duplicates":int(q.duplicated(["code","ymd"]).sum()),"future_used_for_selection":False,"review_only":True};(out/"audit.json").write_text(json.dumps(audit,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");(out/"_ARTIFACT_COMPLETE.json").write_text(json.dumps({"complete":True,"authoritative":"compare.json"},indent=2)+"\n",encoding="utf-8");print(out);print(json.dumps({"years":years,"overall":overall,"judgment":data["judgment"],"audit":audit},ensure_ascii=False,indent=2))
if __name__=="__main__":main()
