"""Test one axis on the 4755 branch: at least three bearish bars in five."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
import pandas as pd

YEARS=tuple(range(2019,2026))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rates(x):return {"n":int(len(x)),"codes":int(x.code.nunique()),"down_first":None if x.empty else float(x.outcome.eq("down_first").mean()),"rebound_first":None if x.empty else float(x.outcome.eq("rebound_first").mean()),"neutral":None if x.empty else float(x.outcome.str.startswith("neutral").mean())}
def main():
 p=argparse.ArgumentParser();p.add_argument("--base-events",type=Path,required=True);p.add_argument("--output",type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=False)
 x=pd.read_parquet(a.base_events);q=x[x.bear_count5>=3].copy();base={str(y):rates(x[x.year.eq(y)]) for y in YEARS};challenger={str(y):rates(q[q.year.eq(y)]) for y in YEARS};anchor=q[(q.code.astype(str).str.zfill(4)=="4755")&q.ymd.eq(20251114)]
 direction=all(challenger[str(y)]["n"]>0 and challenger[str(y)]["down_first"]>challenger[str(y)]["rebound_first"] for y in YEARS);breadth=all(challenger[str(y)]["n"]>=20 for y in YEARS);improved=[y for y in YEARS if challenger[str(y)]["down_first"]-challenger[str(y)]["rebound_first"]>base[str(y)]["down_first"]-base[str(y)]["rebound_first"]]
 data={"schema_version":"tradex_4755_prior_bear_cluster_oos_v1.compare.v1","artifact_role":"authoritative","axis":"prior five-bar bearish accumulation","fixed_conditions":{"base_branch":"POSTBOX_HIGH_FAILURE_SUPPORT_BREAK_DIRECT_CORE unchanged","single_filter":"bear_count5>=3","years":list(YEARS),"outcome":"inherited fixed3 h5","minimum_each_year":20,"threshold_sweep":False},"baseline_results":base,"challenger_results":challenger,"human_anchor":{"4755_20251114":{"match":len(anchor)==1,"rows":anchor.where(pd.notna(anchor),None).to_dict("records")}},"observed_branching":{"base_events":int(len(x)),"retained_events":int(len(q)),"removed_events":int(len(x)-len(q)),"improved_years":improved,"changed_rank_count":int(len(x)-len(q)),"selection_divergence_reason":"support break requires a three-of-five bearish cluster"},"judgment":{"decision":"keep" if direction and breadth and len(anchor)==1 else "drop","direction_pass_all_years":direction,"breadth_pass":breadth,"human_anchor_preserved":len(anchor)==1,"reason":"prior bearish cluster does not improve the branch consistently" if not(direction and breadth) else "all gates pass"},"not_changed":["base branch","support break","monthly context","MA60 warning","other branches","MeeMee","ranking","runtime DB"]}
 cp=a.output/"compare.json";cp.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");q.to_parquet(a.output/"filtered_events.parquet",index=False);audit={"base_events":int(len(x)),"retained_events":int(len(q)),"duplicates":int(q.duplicated(["code","ymd"]).sum()),"future_used_for_selection":False,"review_only":True,"source_sha256":sha(a.base_events)};(a.output/"audit.json").write_text(json.dumps(audit,indent=2)+"\n",encoding="utf-8");(a.output/"_ARTIFACT_COMPLETE.json").write_text(json.dumps({"complete":True,"authoritative":"compare.json","sha256":sha(cp)},indent=2)+"\n",encoding="utf-8");print(json.dumps({"output":str(a.output),"challenger":challenger,"judgment":data["judgment"],"audit":audit},indent=2))
if __name__=="__main__":main()
