from __future__ import annotations
import argparse,json
from pathlib import Path
import pandas as pd
def met(g):return {"n":int(len(g)),"codes":int(g.code.nunique()),"rise5_rate":float(g.rise5_in5.mean()),"rise_then_reversal20_rate":float(g.rise_then_reversal20.mean()),"rise_held_positive20_rate":float(g.rise_held_positive20.mean()),"failed_rise_drop5_rate":float(g.failed_rise_drop5.mean()),"median_close20_pct":float(g.close20_pct.median()),"p10_low20_pct":float(g.low20_pct.quantile(.1))}
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--families",required=True);ap.add_argument("--inventory",required=True);ap.add_argument("--output",required=True);a=ap.parse_args();out=Path(a.output);out.mkdir(parents=True,exist_ok=False);f=pd.read_parquet(a.families,columns=["code","ymd","buy_family","period"]);f=f[f.buy_family.isin(["急落反発","上昇継続"])];i=pd.read_parquet(a.inventory,columns=["code","ymd","rise5_in5","low5_pct","low20_pct","close20_pct"]);d=f.merge(i,on=["code","ymd"],validate="one_to_one");d["rise_then_reversal20"]=d.rise5_in5.eq(1)&d.low20_pct.le(-5)&d.close20_pct.lt(0);d["rise_held_positive20"]=d.rise5_in5.eq(1)&d.close20_pct.gt(0);d["failed_rise_drop5"]=d.rise5_in5.eq(0)&d.low5_pct.le(-5);rows=[];yrs=[]
 for (p,fam),g in d.groupby(["period","buy_family"]):rows.append({"period":p,"buy_family":fam,**met(g)})
 for (y,fam),g in d.assign(year=d.ymd//10000).groupby(["year","buy_family"]):yrs.append({"year":int(y),"buy_family":fam,**met(g)})
 m=pd.DataFrame(rows);yr=pd.DataFrame(yrs);d.to_parquet(out/"reversal_path_ledger.parquet",index=False);m.to_parquet(out/"reversal_path_metrics.parquet",index=False);yr.to_parquet(out/"reversal_path_yearly_metrics.parquet",index=False);checks={"both_families_present":set(m.buy_family)=={"急落反発","上昇継続"},"development_validation_present":set(m.period)=={"development","validation"},"outcome_only_no_membership_change":len(d)==len(f)}
 res={"schema_version":"tradex_long_reversal_path_context_v1.compare.v1","artifact_role":"authoritative_long_reversal_path_context","review_only":True,"fixed_conditions":{"rise":"+5% intraday within five sessions","rise_then_reversal":"rise then 20-session low<=-5% and close20<0","rise_held":"rise and close20>0","failed_rise_drop":"no rise5 and low5<=-5%","policy":"outcome diagnosis only"},"authoritative_result":{"validation":m[m.period.eq("validation")].to_dict("records"),"validation_years":yr[yr.year>=2024].to_dict("records"),"gate_checks":checks},"judgment":{"candidate_local_decision":"keep_diagnostic_only","session_aggregate_decision":"keep_long_reversal_context","authoritative_rollup_decision":"keep_long_reversal_path_context_v1_review_only","reason_type":"separates_rise_hold_from_post_rise_reversal"},"not_changed":["family","entry","management","MeeMee","ranking","runtime DB","production logic"]}
 (out/"compare.json").write_text(json.dumps(res,ensure_ascii=False,indent=2),encoding="utf-8");(out/"_ARTIFACT_COMPLETE.json").write_text(json.dumps({"complete":True,"authoritative":"compare.json"}));print(json.dumps(res["authoritative_result"],ensure_ascii=False))
if __name__=="__main__":main()
