from __future__ import annotations
import json,sys
from datetime import datetime,timezone
from pathlib import Path
import duckdb
AXIS_ID='leaf20_vol3_current_selection_v1';OUT=Path(r'G:\Tradex\leaf20_vol3_current_selection_v1');VOL_CEILING=.03
QUALITY={'sample_count_2026_completed':10,'win_rate':.5,'average_win':.0691005359400941,'average_loss':.05,'payoff_ratio':1.382010718801882,'expectancy':.009550267970047047,'profit_factor':1.3820107188018822,'maximum_loss':-.05}
SOURCE_ARTIFACT=r'G:\Tradex\leaf20_vol3_breadth_ceiling_2026_oos_v1\20260711T152831Z-leaf20_vol3_breadth_ceiling_2026_oos_v1\compare.json'
def run():
 sys.path[:0]=[str(Path.cwd()),'app'];from backend.services.codex_bridge_service import get_runtime_stock_db_status,get_rankings_freshness
 runtime=get_runtime_stock_db_status();fresh=get_rankings_freshness(direction='up',limit=50);db=Path(runtime['selected_runtime_db_path'])
 q="""WITH latest AS(SELECT max(date) date FROM daily_bars WHERE source='pan'),eligible AS(SELECT code FROM daily_bars WHERE source='pan' GROUP BY code HAVING max(date)=(SELECT date FROM latest)),base AS(SELECT b.*,b.c/lag(b.c) over(partition by b.code order by b.date)-1 ret1 FROM daily_bars b JOIN eligible e USING(code) WHERE b.source='pan'),bars AS(SELECT *,lag(h) over w prior_high1,max(h) over(partition by code order by date rows between 20 preceding and 1 preceding) prior_high20,avg(c) over(partition by code order by date rows between 19 preceding and current row) ma20,avg(c) over(partition by code order by date rows between 24 preceding and 5 preceding) ma20_5ago,avg(c) over(partition by code order by date rows between 59 preceding and current row) ma60,avg(v) over(partition by code order by date rows between 19 preceding and current row) avg_volume20,max(h) over(partition by code order by date rows between 9 preceding and current row) high10,min(l) over(partition by code order by date rows between 9 preceding and current row) low10,stddev_samp(ret1) over(partition by code order by date rows between 19 preceding and current row) realized_vol20 FROM base WINDOW w AS(partition by code order by date)),breadth AS(SELECT date,avg(case when c>ma20 then 1.0 else 0.0 end) market_breadth FROM bars GROUP BY date),current AS(SELECT b.*,br.market_breadth FROM bars b JOIN breadth br USING(date) WHERE b.date=(SELECT date FROM latest)) SELECT code,date,o,h,l,c,v,ma20,ma60,realized_vol20,market_breadth,(c/ma60)-1 gap_ma60,(high10/low10)-1 range10,(c/prior_high1)-1 prior_high_gap FROM current WHERE market_breadth<=.60 AND ma20>ma60 AND c>=prior_high20*.95 AND l BETWEEN ma20*.99 AND ma20 AND c>ma20 AND c>o AND (c-l)/nullif(h-l,0)>=.70 AND (c/ma60)-1>.0370751 AND (high10/low10)-1>.0544289 AND (c/prior_high1)-1>.0233188 AND realized_vol20<.03 ORDER BY gap_ma60 DESC,code"""
 with duckdb.connect(str(db),read_only=True) as c:df=c.execute(q).fetchdf()
 rows=[]
 for i,r in enumerate(df.to_dict('records'),1):rows.append({'selection_rank':i,'code':str(r['code']),'confirmed_signal_date':runtime['latest_confirmed_daily_bars_date_iso'],'confirmed_close':r['c'],'realized_vol20':r['realized_vol20'],'market_breadth':r['market_breadth'],'gap_ma60':r['gap_ma60'],'shape_signal':'shallow_high_zone_leaf_20_low_vol_breadth60','new_entry_verdict':'watch_next_open','entry_condition':'next_session_open_not_above_confirmed_close','entry_status':'review_only_not_automatic_buy','meemee_ranking_alignment':'reference_only','quality_metrics_2026':QUALITY,'research_status':'2026_oos_positive_candidate'})
 root=OUT/f"{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}-{AXIS_ID}";root.mkdir(parents=True);payload={'schema_version':f'{AXIS_ID}.board.v2','artifact_role':'authoritative','axis_id':AXIS_ID,'boundary':'TRADEX selection; MeeMee display only','confirmed_signal_date':runtime['latest_confirmed_daily_bars_date_iso'],'runtime_freshness':runtime['freshness_state'],'ranking_freshness':fresh['freshness_state'],'selection_contract':{'shape':'leaf20','realized_vol20_ceiling':VOL_CEILING,'market_breadth_ceiling':.60,'entry':'next session open only when open<=confirmed close','take_profit':.08,'stop_loss':.05,'maximum_holding_sessions':10,'capital_allocation':'not used','holdings':'ignored'},'quality_metrics_2026':QUALITY,'candidate_count':len(rows),'default_verdict':'watch' if rows else 'wait','candidates':rows,'source_research_artifact':SOURCE_ARTIFACT,'production_ranking_changed':False,'runtime_db_write':False,'automatic_trading':False};(root/'current_selection_board.json').write_text(json.dumps(payload,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print(root)
if __name__=='__main__':run()
