from __future__ import annotations
import argparse,json,sys
from datetime import datetime,timezone
from pathlib import Path
import pandas as pd
from tradex_long_ordinary_pit_compound_tree_v1 import load_rows
from tradex_long_fresh_family_events_v1 import FAMILIES,add_scores

def main():
 p=argparse.ArgumentParser();p.add_argument('--output',required=True);p.add_argument('--audit',type=Path,required=True);a=p.parse_args();out=Path(a.output);out.mkdir(parents=True,exist_ok=False);audit=json.loads(a.audit.read_text(encoding='utf-8'));sys.path[:0]=[str(Path.cwd()),str(Path.cwd()/'app')]
 from backend.services.codex_bridge_service import get_runtime_stock_db_status,get_rankings_freshness
 runtime=get_runtime_stock_db_status();rankings=get_rankings_freshness();d=load_rows(runtime['selected_runtime_db_path'],broad_trigger=False,min_date='2026-04-01');latest=int(d.date.max());x=add_scores(d[d.date.eq(latest)].copy());frames=[]
 for f in FAMILIES:
  q=x.sort_values([f,'code'],ascending=[False,True]).head(3).copy();q['family']=f;q['family_score']=q[f];q['family_rank']=range(1,len(q)+1);frames.append(q)
 e=pd.concat(frames,ignore_index=True);strength=.5*float(e.market_breadth_ma20.iloc[0])+.5*float(e.market_advancers_ratio.iloc[0]);breakout=sorted(e.family.unique())[0];e=e[(e.family!=breakout)|(e.family_rank<=1)|(strength>=.7)].copy();weight=5*min(1,strength/.7);e['market_strength']=strength;e['proposed_weight_pct']=weight;e['status']='Watch';e['entry_contract']='next session open only after operational chart and holding review';cols=['code','stock_name','family','family_rank','family_score','c','ret1','ret5','ret20','gap_ma20','gap_ma60','close_pos','volume_ratio20','realized_vol20','market_breadth_ma20','market_advancers_ratio','market_strength','proposed_weight_pct','status','entry_contract'];rows=e[cols].sort_values(['family','family_rank']).to_dict('records');checks={'final_audit_practical_review_only':audit['judgment']['authoritative_rollup_decision']=='practical_review_only','runtime_confirmed':runtime['confirmed'],'runtime_latest_2026_07_17':runtime['latest_confirmed_daily_bars_date_iso']=='2026-07-17','ranking_fresh':rankings['freshness_state']=='fresh','board_date_matches_runtime':latest==1784246400,'nonordinary_name_absent':not e.stock_name.str.contains('種類株|優先株',regex=True).any(),'market_strength_below_router_threshold':strength<.7,'breakout_restricted_to_rank1':int((e.family==breakout).sum())==1}
 decision='READY_REVIEW_ONLY' if all(checks.values()) else 'HOLD';payload={'schema_version':'tradex_long_fresh_current_board_v1.board.v1','artifact_role':'authoritative','generated_at':datetime.now(timezone.utc).isoformat(),'latest_as_of':'2026-07-17','runtime':runtime,'rankings_freshness':rankings,'source_adoption_audit':str(a.audit),'fixed_contract':{'ordinary_stocks_only':True,'market_strength':strength,'router_threshold':.7,'sizing_threshold':.7,'base_weight_pct':5,'proposed_weight_pct':weight,'entry':'next session open after review','maximum_holding':'20 sessions','max_positions':20,'production_changed':False},'authoritative_result':{'candidate_count':len(rows),'starter_count':0,'watch_count':len(rows),'rows':rows,'checks':checks},'judgment':{'candidate_local_decision':decision,'authoritative_rollup_decision':decision,'reason_type':'latest_confirmed_review_board_no_chart_confirmation'},'remaining_risks':['holdings and chart context not yet reconciled; Watch is not Buy','next session open price and gap are unknown']}
 (out/'current_board.json').write_text(json.dumps(payload,ensure_ascii=False,indent=2,default=str),encoding='utf-8');pd.DataFrame(rows).to_csv(out/'current_board.csv',index=False,encoding='utf-8-sig');(out/'_ARTIFACT_COMPLETE.json').write_text(json.dumps({'complete':True,'authoritative':'current_board.json'}),encoding='utf-8');print(json.dumps({'decision':decision,'strength':strength,'weight':weight,'checks':checks,'rows':rows},ensure_ascii=False))
if __name__=='__main__':main()
