import argparse,hashlib,json
from pathlib import Path
import pandas as pd
YEARS=range(2019,2026)
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def rates(x):
 n=len(x);return {'n':n,'down_first':int(x.outcome.eq('down_first').sum()),'rebound_first':int(x.outcome.eq('rebound_first').sum()),'neutral_no_hit':int(x.outcome.eq('neutral_no_hit').sum()),'down_first_pct':None if not n else 100*x.outcome.eq('down_first').mean(),'rebound_first_pct':None if not n else 100*x.outcome.eq('rebound_first').mean()}
def main():
 p=argparse.ArgumentParser();p.add_argument('--score-ledger',type=Path,required=True);p.add_argument('--daily',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=True)
 x=pd.read_parquet(a.score_ledger);f=pd.read_parquet(a.daily,columns=['code','ymd','dist_ma20_atr']);x.code=x.code.astype(str).str.zfill(4);f.code=f.code.astype(str).str.zfill(4);x=x.merge(f,left_on=['code','action_ymd'],right_on=['code','ymd'],how='left',validate='one_to_one');x['penalty_overextended_ma20']=x.dist_ma20_atr.lt(-.5).astype(int);x['adjusted_score']=x.score-x.penalty_overextended_ma20;x['gate_pass']=x.adjusted_score.ge(2)
 results={str(y):rates(x[x.year.eq(y)&x.gate_pass]) for y in YEARS};formal=all(results[str(y)]['down_first']>results[str(y)]['rebound_first'] for y in range(2021,2026));external=all(results[str(y)]['down_first']>results[str(y)]['rebound_first'] for y in [2019,2020]);breadth=all(results[str(y)]['n']>=20 for y in range(2021,2026));z=x[(x.code.eq('9962'))&x.action_ymd.eq(20260713)][['score','dist_ma20_atr','penalty_overextended_ma20','adjusted_score','gate_pass','outcome']];anchor=z.where(pd.notna(z),None).to_dict('records')
 data={'schema_version':'tradex_weak_rebound_overextension_penalty_v1.compare.v1','artifact_role':'authoritative','review_only':True,'axis':'subtract one point when MA20 rebreak is already overextended','fixed_conditions':{'base_score':'equal three-point score unchanged','single_penalty':'-1 when action close is below MA20 by more than 0.5 ATR','selection':'adjusted_score>=2','formal_years':[2021,2022,2023,2024,2025],'external_diagnostic_years':[2019,2020],'minimum_each_formal_year':20,'threshold_sweep':False,'feature_join':'code+action_ymd'},'year_results':results,'human_anchor_9962':anchor,'observed_branching':{'base_score_ge2':int(x.score.ge(2).sum()),'adjusted_score_ge2':int(x.gate_pass.sum()),'removed_events':int((x.score.ge(2)&~x.gate_pass).sum()),'selection_divergence_reason':'an otherwise valid setup is downgraded when the MA20 break is already stretched enough to increase rebound risk'},'judgment':{'candidate_local_decision':'hold' if formal and breadth else 'drop','external_stability_decision':'keep' if external else 'drop','formal_direction_pass':formal,'formal_breadth_pass':breadth,'external_direction_pass':external,'reason':'formal years pass, but 2020 external diagnostic fails; do not adopt'},'not_changed':['base points','other candle/MA features','other branches','MeeMee','ranking','runtime DB']}
 cp=a.output/'compare.json';cp.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');x.to_parquet(a.output/'overextension_penalty_ledger.parquet',index=False);(a.output/'audit.json').write_text(json.dumps({'duplicates':int(x.duplicated(['code','action_ymd']).sum()),'missing_action_feature':int(x.dist_ma20_atr.isna().sum()),'future_used_for_selection':False,'input_sha256':{'score_ledger':sha(a.score_ledger),'daily':sha(a.daily)}},indent=2)+'\n',encoding='utf-8');(a.output/'_ARTIFACT_COMPLETE.json').write_text(json.dumps({'complete':True,'authoritative':'compare.json','sha256':sha(cp)},indent=2)+'\n',encoding='utf-8');print(json.dumps({'output':str(a.output),'results':results,'anchor':anchor,'judgment':data['judgment']},ensure_ascii=False,indent=2))
if __name__=='__main__':main()
