"""One-axis filter: require downside room to the nearest long support at action close."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
import pandas as pd

YEARS=(2023,2024,2025)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rates(x,col):return {"n":int(len(x)),"codes":int(x.code.nunique()),"down_first":None if x.empty else float(x[col].eq("down_first").mean()),"rebound_first":None if x.empty else float(x[col].eq("rebound_first").mean()),"neutral":None if x.empty else float(x[col].str.startswith("neutral").mean())}
def main():
 p=argparse.ArgumentParser();p.add_argument("--path-ledger",type=Path,required=True);p.add_argument("--features",type=Path,required=True);p.add_argument("--output",type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=False)
 x=pd.read_parquet(a.path_ledger);f=pd.read_parquet(a.features,columns=["code","ymd","c","atr14","ma60","ma100","ma200","support20"]);f["code"]=f.code.astype(str).str.zfill(4);x["code"]=x.code.astype(str).str.zfill(4)
 specs={"IMMEDIATE_CONTINUATION_MA7_ADD":("ma7_recross_failure_ymd","ma7_recross_outcome_fixed3_h5"),"WEAK_REBOUND_MA20_REBREAK_CORE":("ma20_rebreak_ymd","ma20_rebreak_outcome_fixed3_h5")};results={};filtered=[];gates={}
 for fam,(date_col,out_col) in specs.items():
  z=x[x.path_family.eq(fam)].copy();z["action_ymd"]=z[date_col].astype(int);z=z.merge(f,left_on=["code","action_ymd"],right_on=["code","ymd"],how="left",validate="many_to_one",suffixes=("","_action"));dist=pd.concat([(z.c-z.ma60)/z.atr14,(z.c-z.ma100)/z.atr14,(z.c-z.ma200)/z.atr14,(z.c-z.support20)/z.atr14],axis=1);z["nearest_support_room_atr"]=dist.where(dist.ge(0)).min(axis=1);q=z[z.nearest_support_room_atr.gt(.35)].copy();q["path_family"]=fam;filtered.append(q)
  results[fam]={str(y):{"baseline":rates(z[z.year.eq(y)],out_col),"challenger":rates(q[q.year.eq(y)],out_col)} for y in YEARS};breadth=all(results[fam][str(y)]["challenger"]["n"]>=30 for y in YEARS);positive=breadth and all(results[fam][str(y)]["challenger"]["down_first"]>results[fam][str(y)]["challenger"]["rebound_first"] for y in YEARS);gates[fam]={"breadth_pass":breadth,"down_exceeds_rebound_all_years":positive,"decision":"keep" if positive else "drop"}
 out=pd.concat(filtered,ignore_index=True);anchor=out[(out.code=="6532")&out.path_family.eq("IMMEDIATE_CONTINUATION_MA7_ADD")&out.action_ymd.eq(20230704)].where(pd.notna(out),None).to_dict("records");passing=[k for k,v in gates.items() if v["decision"]=="keep"]
 data={"schema_version":"tradex_ordered_sequence_support_room_oos_v1.compare.v1","artifact_role":"authoritative","axis":"downside room to nearest MA60 MA100 MA200 or support20 at sequence action close","fixed_conditions":{"base_paths":"unchanged ordered path split","single_filter":"nearest non-negative support distance >0.35ATR","threshold":"existing support-room veto contract; no sweep","outcome":"inherited exact OHLC symmetric fixed 3 percent h5","years":list(YEARS),"minimum_each_year":30},"year_path_results":results,"path_gates":gates,"human_anchor_6532":anchor,"observed_branching":{"base_events":int(len(x)),"kept_events":int(len(out)),"removed_events":int(len(x)-len(out)),"passing_path_count":len(passing),"changed_top5_members_count":None,"changed_top10_members_count":None,"changed_rank_count":2,"selection_divergence_reason":"sequence actions with insufficient room before the next long support are vetoed"},"judgment":{"decision":"keep" if passing else "hold","passing_paths":passing,"human_anchor_preserved":len(anchor)==1,"reason":"path is retained only when support-room filter preserves breadth and down-first dominance in every OOS year"},"not_changed":["sequence ordering","monthly environment","action dates","oversold risk","existing lifecycle","MeeMee","ranking","runtime DB"]}
 cp=a.output/"compare.json";cp.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");out.to_parquet(a.output/"support_room_filtered_path_ledger.parquet",index=False);audit={"base_events":int(len(x)),"kept_events":int(len(out)),"missing_support_room":int(out.nearest_support_room_atr.isna().sum()),"duplicates":int(out.duplicated(["code","erasure_ymd","path_family"]).sum()),"future_used_for_selection":False,"review_only":True,"path_sha256":sha(a.path_ledger),"feature_sha256":sha(a.features)};(a.output/"audit.json").write_text(json.dumps(audit,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");(a.output/"_ARTIFACT_COMPLETE.json").write_text(json.dumps({"complete":True,"authoritative":"compare.json","sha256":sha(cp)},indent=2)+"\n",encoding="utf-8");print(json.dumps({"output":str(a.output),"results":results,"gates":gates,"anchor_6532":len(anchor)==1,"judgment":data["judgment"]},ensure_ascii=False,indent=2))
if __name__=="__main__":main()
