from __future__ import annotations
import argparse,json
from pathlib import Path
import duckdb,pandas as pd
def met(g):return {"n":int(len(g)),"codes":int(g.code.nunique()),"rise5_rate":float(g.rise5_in5.mean()),"drop5_rate":float(g.drop5_in5.mean()),"clean_rise_rate":float(g.clean_rise3_before_drop5.mean()),"mean_close5_pct":float(g.close5_pct.mean()),"median_low5_pct":float(g.low5_pct.median()),"p10_low5_pct":float(g.low5_pct.quantile(.1)),"rise10_20_rate":float(g.rise10_in20.mean())}
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--inventory",required=True);ap.add_argument("--output",required=True);a=ap.parse_args();out=Path(a.output);out.mkdir(parents=True,exist_ok=False);c=duckdb.connect();q=c.execute(f"SELECT quantile_cont(range20,.9),quantile_cont(ret5,.1),quantile_cont(ret5,.9) FROM read_parquet('{str(Path(a.inventory)).replace(chr(39),chr(39)*2)}') WHERE ymd<20240101").fetchone();c.close();r90,rlo,rhi=map(float,q)
 d=pd.read_parquet(a.inventory,columns=["code","ymd","range20","ret5","rise5_in5","drop5_in5","clean_rise3_before_drop5","close5_pct","low5_pct","rise10_in20"]);d["buy_family"]="通常値幅";hv=d.range20.ge(r90);d.loc[hv,"buy_family"]="高値幅中立";d.loc[hv&d.ret5.le(rlo),"buy_family"]="急落反発";d.loc[hv&d.ret5.ge(rhi),"buy_family"]="上昇継続";d["period"]=d.ymd.lt(20240101).map({True:"development",False:"validation"})
 rows=[];yrs=[]
 for (p,f),g in d.groupby(["period","buy_family"]):rows.append({"period":p,"buy_family":f,**met(g)})
 for (y,f),g in d.assign(year=d.ymd//10000).groupby(["year","buy_family"]):yrs.append({"year":int(y),"buy_family":f,**met(g)})
 m=pd.DataFrame(rows);yr=pd.DataFrame(yrs);d.to_parquet(out/"buy_family_ledger.parquet",index=False);m.to_parquet(out/"buy_family_metrics.parquet",index=False);yr.to_parquet(out/"buy_family_yearly_metrics.parquet",index=False);v=m[m.period.eq("validation")].set_index("buy_family");checks={"rebound_rise_gt_baseline":bool(v.loc["急落反発","rise5_rate"]>v.loc["通常値幅","rise5_rate"]),"momentum_rise_gt_baseline":bool(v.loc["上昇継続","rise5_rate"]>v.loc["通常値幅","rise5_rate"]),"both_families_n_ge1000":bool(v.loc["急落反発","n"]>=1000 and v.loc["上昇継続","n"]>=1000)}
 for f in ["急落反発","上昇継続"]:
  z=yr[(yr.year>=2024)&yr.buy_family.eq(f)];b=yr[(yr.year>=2024)&yr.buy_family.eq("通常値幅")].set_index("year");checks[f"{f}_all_years_above_baseline"]=bool(len(z)==3 and all(r.rise5_rate>b.loc[r.year,"rise5_rate"] for r in z.itertuples()))
 keep=all(checks.values());res={"schema_version":"tradex_long_rise_family_branch_v1.compare.v1","artifact_role":"authoritative_long_rise_family_branch","review_only":True,"fixed_conditions":{"development":"2019-2023","validation":"2024-2026","high_volatility":"range20 >= development p90","recent_direction":"ret5 <= development p10 rebound; ret5 >= p90 momentum","contracts":{"range20_p90":r90,"ret5_p10":rlo,"ret5_p90":rhi},"costs":"ignored"},"authoritative_result":{"validation":m[m.period.eq("validation")].to_dict("records"),"validation_years":yr[yr.year>=2024].to_dict("records"),"gate_checks":checks},"observed_branching":{"changed_top5_members_count":None,"changed_top10_members_count":None,"changed_rank_count":int(hv.sum()),"selection_divergence_reason":"high-volatility population branches by recent direction"},"judgment":{"candidate_local_decision":"keep" if keep else "hold","session_aggregate_decision":"keep_rebound_and_momentum_families" if keep else "hold_family_branch","authoritative_rollup_decision":"keep_long_rebound_momentum_family_branch_v1_review_only" if keep else "hold_continue_family_branch","reason_type":"both_directional_families_stable_above_baseline"},"not_changed":["hard screen","combined score","MeeMee","ranking","runtime DB","production logic"],"remaining_risks":["families share volatility axis","entry timing absent","extreme paths may have large adverse tails"]}
 (out/"compare.json").write_text(json.dumps(res,ensure_ascii=False,indent=2),encoding="utf-8");(out/"_ARTIFACT_COMPLETE.json").write_text(json.dumps({"complete":True,"authoritative":"compare.json"}));print(json.dumps(res["authoritative_result"],ensure_ascii=False))
if __name__=="__main__":main()
