"""Decompose MA200 CORE outcomes by one fixed strong-bull breadth regime."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
import pandas as pd

YEARS=tuple(range(2020,2027))
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def cell(z,col):
 n=len(z);d=int(z[col].eq('down_first').sum());r=int(z[col].eq('rebound_first').sum());return {'n':n,'down_first':d,'rebound_first':r,'neutral':n-d-r}
def main():
 p=argparse.ArgumentParser();p.add_argument('--core-ledger',type=Path,nargs='+',required=True);p.add_argument('--daily',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=False)
 x=pd.concat([pd.read_parquet(v) for v in a.core_ledger],ignore_index=True);d=pd.read_parquet(a.daily,columns=['ymd','market_breadth_ma60']).drop_duplicates('ymd');x=x.merge(d,left_on='core_ymd',right_on='ymd',how='left',validate='many_to_one');x=x[x.separation_gate_pass].copy();x['strong_bull_regime']=x.market_breadth_ma60.ge(.75)
 results={str(y):{reg:{'whole_1_1':cell(x[(x.core_year==y)&(x.strong_bull_regime==(reg=='STRONG_BULL'))],'whole_position_outcome_1_1'),'whole_1_2':cell(x[(x.core_year==y)&(x.strong_bull_regime==(reg=='STRONG_BULL'))],'whole_position_outcome_1_2')} for reg in ['STRONG_BULL','OTHER']} for y in YEARS};anchor=x[(x.code=='9107')&(x.core_ymd==20241122)].to_dict('records');bad_years={str(y):{'strong_bull_n':results[str(y)]['STRONG_BULL']['whole_1_2']['n'],'other_n':results[str(y)]['OTHER']['whole_1_2']['n'],'other_down':results[str(y)]['OTHER']['whole_1_2']['down_first'],'other_rebound':results[str(y)]['OTHER']['whole_1_2']['rebound_first']} for y in [2022,2026]}
 explains=all(v['strong_bull_n']>0 and v['other_down']>v['other_rebound'] for v in bad_years.values())
 data={'schema_version':'tradex_ma200_market_regime_decomposition_v1.compare.v1','artifact_role':'authoritative','review_only':True,'axis':'strong bull market breadth only','fixed_conditions':{'strong_bull':'Nikkei225 member breadth above MA60 >= 75% at CORE close','base_core':'probe separation pass unchanged','outcome':'whole position fixed3 h5, 1:1 and 1:2','years':list(YEARS),'threshold_sweep':False},'year_results':results,'problem_years_2022_2026':bad_years,'human_anchor_9107':anchor,'observed_branching':{'strong_bull_rows':int(x.strong_bull_regime.sum()),'other_rows':int((~x.strong_bull_regime).sum()),'changed_rank_count':int(x.strong_bull_regime.sum()),'selection_divergence_reason':'diagnostic split only; no selector adoption'},'judgment':{'decision':'drop_market_regime_gate','strong_bull_explains_2022_2026':explains,'problem_attribution':'selection_or_sequence_not_broad_market_strength' if not explains else 'market_regime','human_anchor_not_penalized':bool(anchor) and not bool(anchor[0]['strong_bull_regime']),'reason':'2022 and 2026 failures occur entirely outside the fixed strong-bull regime'},'not_changed':['CORE selector','monthly classifier','management classifier','MeeMee','ranking','runtime DB']}
 cp=a.output/'compare.json';cp.write_text(json.dumps(data,ensure_ascii=False,indent=2,default=str)+'\n',encoding='utf-8');x.to_parquet(a.output/'market_regime_core_ledger.parquet',index=False);(a.output/'audit.json').write_text(json.dumps({'rows':len(x),'missing_breadth':int(x.market_breadth_ma60.isna().sum()),'duplicates':int(x.duplicated(['code','probe_ymd']).sum()),'future_used_for_selection':False,'daily_sha256':sha(a.daily),'core_sha256':[sha(v) for v in a.core_ledger]},indent=2)+'\n',encoding='utf-8');(a.output/'_ARTIFACT_COMPLETE.json').write_text(json.dumps({'complete':True,'authoritative':'compare.json','sha256':sha(cp)},indent=2)+'\n',encoding='utf-8');print(json.dumps({'output':str(a.output),'bad_years':bad_years,'judgment':data['judgment']},ensure_ascii=False,indent=2))
if __name__=='__main__':main()
