from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
import duckdb
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def esc(p):return str(Path(p).resolve()).replace("'","''")
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--daily",required=True);ap.add_argument("--output",required=True);a=ap.parse_args();out=Path(a.output);out.mkdir(parents=True,exist_ok=False);ep=out/"rise_episode_inventory.parquet";en=out/"daily_rise_outcome_inventory.parquet"
 con=duckdb.connect()
 con.execute(f"""COPY (SELECT *, (high5_pct>=5)::INTEGER rise5_in5,(high10_pct>=8)::INTEGER rise8_in10,(high20_pct>=10)::INTEGER rise10_in20,(first_rise3_day<first_drop5_day)::INTEGER clean_rise3_before_drop5 FROM read_parquet('{esc(a.daily)}')) TO '{esc(en)}' (FORMAT PARQUET,COMPRESSION ZSTD,ROW_GROUP_SIZE 100000)""")
 con.execute(f"""COPY (WITH t AS (SELECT *,lag(bar_index) OVER(PARTITION BY code ORDER BY bar_index) p FROM read_parquet('{esc(en)}') WHERE rise5_in5=1),m AS (SELECT *,CASE WHEN p IS NULL OR bar_index-p>5 THEN 1 ELSE 0 END ne FROM t),g AS (SELECT *,sum(ne) OVER(PARTITION BY code ORDER BY bar_index) episode_number FROM m),r AS (SELECT *,row_number() OVER(PARTITION BY code,episode_number ORDER BY bar_index) ord,count(*) OVER(PARTITION BY code,episode_number) episode_signal_count FROM g) SELECT * FROM r WHERE ord=1) TO '{esc(ep)}' (FORMAT PARQUET,COMPRESSION ZSTD,ROW_GROUP_SIZE 50000)""")
 daily=con.execute(f"SELECT count(*),count(distinct code),avg(rise5_in5),avg(rise8_in10),avg(rise10_in20) FROM read_parquet('{esc(en)}')").fetchone();e=con.execute(f"SELECT count(*),count(distinct code),count(*) FILTER(WHERE ymd<20240101),count(*) FILTER(WHERE ymd>=20240101),median(high5_pct),median(low5_pct),avg(clean_rise3_before_drop5) FROM read_parquet('{esc(ep)}')").fetchone();bands=con.execute(f"SELECT CASE WHEN high5_pct>=12 THEN '12%以上' WHEN high5_pct>=8 THEN '8-12%' ELSE '5-8%' END band,count(*),count(distinct code),median(high5_pct),median(low5_pct) FROM read_parquet('{esc(ep)}') GROUP BY 1 ORDER BY median(high5_pct)").fetchall();con.close()
 checks={"daily_n_ge500k":daily[0]>=500000,"episodes_ge10000":e[0]>=10000,"codes_ge300":e[1]>=300,"development_ge5000":e[2]>=5000,"validation_ge2000":e[3]>=2000};keep=all(checks.values())
 res={"schema_version":"tradex_long_rise_event_inventory_v1.compare.v1","artifact_role":"authoritative_full_universe_long_rise_event_inventory","review_only":True,"research_phase":"infrastructure_stabilization","fixed_conditions":{"universe":"same full PAN daily inventory as short study","period":"2019-01-01 through 2026-06-30","entry_reference":"next session open","primary_event":"future intraday high reaches +5% within 5 sessions","episode_deduplication":"same-code target anchors separated by <=5 trading bars share one episode; earliest retained","development":"2019-2023","validation":"2024-2026","costs":"ignored"},"authoritative_result":{"daily":{"n":daily[0],"codes":daily[1],"rise5_rate":daily[2],"rise8_10_rate":daily[3],"rise10_20_rate":daily[4]},"episodes":{"n":e[0],"codes":e[1],"development_n":e[2],"validation_n":e[3],"median_high5_pct":e[4],"median_low5_pct":e[5],"clean_rise3_before_drop5_rate":e[6]},"strength_bands":[{"band":r[0],"n":r[1],"codes":r[2],"median_high5_pct":r[3],"median_low5_pct":r[4]} for r in bands],"gate_checks":checks},"observed_branching":{"changed_top5_members_count":None,"changed_top10_members_count":None,"changed_rank_count":e[0],"selection_divergence_reason":"outcome-first full-universe rise episodes"},"judgment":{"candidate_local_decision":"keep" if keep else "hold","session_aggregate_decision":"keep_rise_inventory" if keep else "hold_rise_inventory","authoritative_rollup_decision":"keep_full_universe_rise_inventory_v1_review_only" if keep else "hold_rebuild_rise_inventory","reason_type":"broad_outcome_first_sample_established" if keep else "insufficient_breadth"},"not_changed":["MeeMee","ranking","runtime DB","production logic","buy selector"],"remaining_risks":["episode anchors are hindsight labels","intraday order unknown","corporate actions need later robustness"]}
 c=out/"compare.json";c.write_text(json.dumps(res,ensure_ascii=False,indent=2),encoding="utf-8");(out/"audit.json").write_text(json.dumps({"source_sha256":sha(a.daily),"artifacts":{"daily":sha(en),"episodes":sha(ep)}},indent=2));(out/"_ARTIFACT_COMPLETE.json").write_text(json.dumps({"complete":True,"authoritative":"compare.json"}));print(json.dumps(res["authoritative_result"],ensure_ascii=False))
if __name__=="__main__":main()
