"""One-axis monthly BOX subtype check for MA200 CORE candidates."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
import pandas as pd

YEARS=tuple(range(2020,2027));FORMAL=(2023,2024,2025)
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def cell(z,col):
 n=len(z);d=int(z[col].eq('down_first').sum());r=int(z[col].eq('rebound_first').sum());return {'n':n,'down_first':d,'rebound_first':r,'neutral':n-d-r}
def main():
 p=argparse.ArgumentParser();p.add_argument('--core-ledger',type=Path,nargs='+',required=True);p.add_argument('--monthly',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=False)
 x=pd.concat([pd.read_parquet(v) for v in a.core_ledger],ignore_index=True);x['effective_month']=pd.to_datetime(x.core_ymd.astype(str)).dt.to_period('M').astype(str);m=pd.read_parquet(a.monthly);m.code=m.code.astype(str).str.zfill(4);m['effective_month']=m.effective_month.astype(str);x=x.merge(m[['code','effective_month','source_month','environment','range12_atr','box_pos','mma6_slope3_atr']],on=['code','effective_month'],how='left',validate='many_to_one');x['tight_box_subtype']=x.range12_atr.le(3.0);base=x[x.separation_gate_pass];sel=base[base.tight_box_subtype]
 results={str(y):{'baseline_1_1':cell(base[base.core_year==y],'whole_position_outcome_1_1'),'baseline_1_2':cell(base[base.core_year==y],'whole_position_outcome_1_2'),'tight_box_1_1':cell(sel[sel.core_year==y],'whole_position_outcome_1_1'),'tight_box_1_2':cell(sel[sel.core_year==y],'whole_position_outcome_1_2')} for y in YEARS}
 formal=all(results[str(y)]['tight_box_1_1']['down_first']>results[str(y)]['tight_box_1_1']['rebound_first'] and results[str(y)]['tight_box_1_2']['down_first']>results[str(y)]['tight_box_1_2']['rebound_first'] for y in FORMAL);external=all(results[str(y)]['tight_box_1_1']['n']==0 or (results[str(y)]['tight_box_1_1']['down_first']>results[str(y)]['tight_box_1_1']['rebound_first'] and results[str(y)]['tight_box_1_2']['down_first']>results[str(y)]['tight_box_1_2']['rebound_first']) for y in (2020,2021,2022,2026));anchor=x[(x.code=='9107')&(x.core_ymd==20241122)].to_dict('records')
 data={'schema_version':'tradex_ma200_monthly_box_width_subtype_v1.compare.v1','artifact_role':'authoritative','review_only':True,'axis':'monthly 12-month BOX width only','fixed_conditions':{'base_core':'existing probe-separation gate unchanged','subtype':'range12_atr <= 3.0 using source month strictly before effective month','outcome':'whole position fixed3 h5, share ratios 1:1 and 1:2','years':list(YEARS),'threshold_sweep':False},'year_results':results,'human_anchor_9107':anchor,'observed_branching':{'baseline':len(base),'selected':len(sel),'removed':len(base)-len(sel),'changed_rank_count':len(base)-len(sel),'selection_divergence_reason':'wide monthly BOX candidates are removed'},'judgment':{'decision':'keep' if formal and external else 'drop','formal_pass':formal,'external_pass':external,'human_anchor_preserved':bool(anchor) and bool(anchor[0]['tight_box_subtype']),'reason':'drop because the subtype does not repair both 2022 and 2026 despite formal improvement' if not external else 'keep requires formal and external direction stability'},'not_changed':['monthly classifier','CORE separation threshold','management classifier','MeeMee','ranking','runtime DB']}
 cp=a.output/'compare.json';cp.write_text(json.dumps(data,ensure_ascii=False,indent=2,default=str)+'\n',encoding='utf-8');x.to_parquet(a.output/'monthly_box_width_core_ledger.parquet',index=False);(a.output/'audit.json').write_text(json.dumps({'rows':len(x),'missing_monthly':int(x.range12_atr.isna().sum()),'duplicates':int(x.duplicated(['code','probe_ymd']).sum()),'future_used_for_selection':False,'monthly_sha256':sha(a.monthly),'core_sha256':[sha(v) for v in a.core_ledger]},indent=2)+'\n',encoding='utf-8');(a.output/'_ARTIFACT_COMPLETE.json').write_text(json.dumps({'complete':True,'authoritative':'compare.json','sha256':sha(cp)},indent=2)+'\n',encoding='utf-8');print(json.dumps({'output':str(a.output),'results':results,'judgment':data['judgment']},ensure_ascii=False,indent=2))
if __name__=='__main__':main()
