"""Split ordered erasure sequences into immediate-continuation and weak-rebound paths."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
import pandas as pd

YEARS=(2023,2024,2025)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rates(x,col):return {"n":int(len(x)),"codes":int(x.code.nunique()),"down_first":None if x.empty else float(x[col].eq("down_first").mean()),"rebound_first":None if x.empty else float(x[col].eq("rebound_first").mean()),"neutral":None if x.empty else float(x[col].str.startswith("neutral").mean())}
def main():
 p=argparse.ArgumentParser();p.add_argument("--sequence-ledger",type=Path,required=True);p.add_argument("--output",type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=False);x=pd.read_parquet(a.sequence_ledger);x=x[x.year.isin(YEARS)].copy()
 immediate=x[x.gd_ymd.notna()&x.ma7_recross_failure_ymd.notna()&(x.ma7_recross_failure_ymd>x.gd_ymd)&(x.post_gd_recovery_atr<.30)].copy();weak=x[x.gd_ymd.notna()&x.ma20_rebreak_ymd.notna()&(x.ma20_rebreak_ymd>x.gd_ymd)&x.weak_rebound&(x.max_consecutive_closes_above_ma7<7)].copy()
 specs={"IMMEDIATE_CONTINUATION_MA7_ADD":(immediate,"ma7_recross_outcome_fixed3_h5"),"WEAK_REBOUND_MA20_REBREAK_CORE":(weak,"ma20_rebreak_outcome_fixed3_h5")};results={};envs={};gates={}
 for name,(q,col) in specs.items():
  results[name]={str(y):rates(q[q.year.eq(y)],col) for y in YEARS};envs[name]={str(env):{str(y):rates(q[q.year.eq(y)&q.environment.eq(env)],col) for y in YEARS} for env in sorted(q.environment.dropna().unique())};breadth=all(results[name][str(y)]["n"]>=30 for y in YEARS);positive=breadth and all(results[name][str(y)]["down_first"]>results[name][str(y)]["rebound_first"] for y in YEARS);gates[name]={"breadth_pass":breadth,"down_exceeds_rebound_all_years":positive,"decision":"keep" if positive else "drop"}
 anchor=immediate[(immediate.code=="6532")&immediate.erasure_ymd.eq(20230623)&immediate.ma7_recross_failure_ymd.eq(20230704)].where(pd.notna(immediate),None).to_dict("records");passing=[k for k,v in gates.items() if v["decision"]=="keep"]
 data={"schema_version":"tradex_ordered_sequence_path_split_oos_v1.compare.v1","artifact_role":"authoritative","axis":"ordered path split after erasure and GD","fixed_conditions":{"IMMEDIATE_CONTINUATION_MA7_ADD":"GD present; recovery<0.30ATR; bearish MA7 recross after GD","WEAK_REBOUND_MA20_REBREAK_CORE":"GD present; recovery>=0.30ATR; max bull body<0.80ATR; fewer than 7 consecutive closes above MA7; bearish MA20 rebreak","outcome":"exact OHLC symmetric fixed 3 percent h5 at action close","minimum_each_year":30,"threshold_sweep":False,"years":list(YEARS)},"year_path_results":results,"environment_path_results":envs,"path_gates":gates,"human_anchors":{"6532":{"match":len(anchor)==1,"rows":anchor},"9962":{"available":False,"match":None,"reason":"not present in the Nikkei225 feature ledger"}},"observed_branching":{"immediate_path_events":int(len(immediate)),"weak_rebound_path_events":int(len(weak)),"passing_path_count":len(passing),"changed_top5_members_count":None,"changed_top10_members_count":None,"changed_rank_count":2,"selection_divergence_reason":"post-GD recovery order separates immediate continuation from weak-rebound failure"},"judgment":{"decision":"keep" if passing else "hold","passing_paths":passing,"reason":"path is retained only when down-first exceeds rebound-first with >=30 events in every OOS year"},"not_changed":["sequence ledger","monthly environment","support-room feature","existing lifecycle","MeeMee","ranking","runtime DB"]}
 cp=a.output/"compare.json";cp.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");pd.concat([immediate.assign(path_family="IMMEDIATE_CONTINUATION_MA7_ADD"),weak.assign(path_family="WEAK_REBOUND_MA20_REBREAK_CORE")],ignore_index=True).to_parquet(a.output/"path_event_ledger.parquet",index=False);audit={"source_sequences":int(len(x)),"immediate":int(len(immediate)),"weak":int(len(weak)),"duplicate_path_rows":int(pd.concat([immediate.assign(p='i'),weak.assign(p='w')]).duplicated(["code","erasure_ymd","p"]).sum()),"future_used_for_selection":False,"review_only":True,"source_sha256":sha(a.sequence_ledger)};(a.output/"audit.json").write_text(json.dumps(audit,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");(a.output/"_ARTIFACT_COMPLETE.json").write_text(json.dumps({"complete":True,"authoritative":"compare.json","sha256":sha(cp)},indent=2)+"\n",encoding="utf-8");print(json.dumps({"output":str(a.output),"results":results,"gates":gates,"anchor_6532":len(anchor)==1,"judgment":data["judgment"]},ensure_ascii=False,indent=2))
if __name__=="__main__":main()
