"""Decompose full-erasure down-vs-rebound outcomes into stable same-day shape drivers."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
import pandas as pd

YEARS=(2023,2024,2025)
FEATURES=["body_ratio","upper_wick_ratio","lower_wick_ratio","close_pos","pos20","bear_count5","bear_body5_atr","upper_supply_count5","lower_rejection_count5","low_close_count3","dist_ma7_atr","dist_ma20_atr","dist_ma60_atr","ma7_slope5_atr","ma20_slope5_atr","ma60_slope5_atr","volume_ratio20","support_break_depth_atr","oversold_risk","weekly_lower_high","weekly_upper_wick_ratio","weekly_close_pos","monthly_high_failure"]
GROUPS={"body_ratio":"candle","upper_wick_ratio":"candle","lower_wick_ratio":"candle","close_pos":"candle","pos20":"location","bear_count5":"sequence","bear_body5_atr":"sequence","upper_supply_count5":"sequence","lower_rejection_count5":"sequence","low_close_count3":"sequence","dist_ma7_atr":"ma_position","dist_ma20_atr":"ma_position","dist_ma60_atr":"ma_position","ma7_slope5_atr":"ma_slope","ma20_slope5_atr":"ma_slope","ma60_slope5_atr":"ma_slope","volume_ratio20":"volume","support_break_depth_atr":"support","oversold_risk":"risk","weekly_lower_high":"weekly","weekly_upper_wick_ratio":"weekly","weekly_close_pos":"weekly","monthly_high_failure":"monthly"}
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def auc_high(down,up):
 s=pd.concat([down.rename("v"),up.rename("v")],ignore_index=True).dropna()
 if down.dropna().empty or up.dropna().empty:return None
 ranks=s.rank(method="average");nd=len(down.dropna());nu=len(up.dropna());return float((ranks.iloc[:nd].sum()-nd*(nd+1)/2)/(nd*nu))
def main():
 p=argparse.ArgumentParser();p.add_argument("--erasure-ledger",type=Path,required=True);p.add_argument("--features",type=Path,required=True);p.add_argument("--output",type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=False)
 e=pd.read_parquet(a.erasure_ledger);e=e[e.challenger&e.year.isin(YEARS)&e.label.isin([0,1])][["code","ymd","year","label"]];f=pd.read_parquet(a.features,columns=["code","ymd"]+FEATURES);x=e.merge(f,on=["code","ymd"],how="left",validate="one_to_one")
 drivers=[]
 for feat in FEATURES:
  yrs={};aucs=[]
  for y in YEARS:
   z=x[x.year.eq(y)];dn=z[z.label.eq(0)][feat].dropna();up=z[z.label.eq(1)][feat].dropna();auc=auc_high(dn,up);yrs[str(y)]={"down_n":int(len(dn)),"rebound_n":int(len(up)),"down_median":None if dn.empty else float(dn.median()),"rebound_median":None if up.empty else float(up.median()),"auc_high_value_predicts_down":auc};aucs.append(auc)
  consistent_high=all(v is not None and v>.5 for v in aucs);consistent_low=all(v is not None and v<.5 for v in aucs);consistent=consistent_high or consistent_low;strength=min(abs(v-.5) for v in aucs if v is not None);drivers.append({"feature":feat,"group":GROUPS[feat],"year_results":yrs,"consistent_direction":"HIGHER_IS_DOWN" if consistent_high else "LOWER_IS_DOWN" if consistent_low else "UNSTABLE","stable_min_auc_distance":strength,"stable_direction_pass":consistent})
 drivers.sort(key=lambda z:(z["stable_direction_pass"],z["stable_min_auc_distance"]),reverse=True)
 stable=[d for d in drivers if d["stable_direction_pass"]]
 data={"schema_version":"tradex_full_erasure_shape_driver_decomposition_v1.compare.v1","artifact_role":"authoritative_diagnostic","axis":"same-day shape, MA, support, weekly and monthly driver direction stability","fixed_conditions":{"entry_family":"UPTREND_FULL_ERASURE unchanged","years":list(YEARS),"outcomes":"fixed3 h5 down_first versus rebound_first only","driver_measure":"Mann-Whitney probability that down feature value exceeds rebound value","stable":"AUC strictly on same side of 0.5 in every year","threshold_selection":"none"},"driver_leaderboard":drivers,"stable_driver_count":len(stable),"observed_branching":{"features_tested":len(FEATURES),"stable_direction_features":len(stable),"changed_top5_members_count":None,"changed_top10_members_count":None,"changed_rank_count":len(FEATURES),"selection_divergence_reason":"diagnostic ranking by worst-year directional consistency, not pooled average"},"judgment":{"decision":"hold" if stable else "drop","next_single_axis_feature":None if not stable else stable[0]["feature"],"next_single_axis_direction":None if not stable else stable[0]["consistent_direction"],"reason":"only features whose down-vs-rebound direction agrees in all three OOS years may advance to a fixed-threshold challenger"},"not_changed":["entry family","feature thresholds","monthly environment","position lifecycle","MeeMee","ranking","runtime DB"]}
 cp=a.output/"driver_leaderboard.json";cp.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");(a.output/"compare.json").write_text(json.dumps({"schema_version":data["schema_version"],"artifact_role":"authoritative_pointer","authoritative":"driver_leaderboard.json","judgment":data["judgment"]},ensure_ascii=False,indent=2)+"\n",encoding="utf-8");audit={"events":int(len(x)),"features":len(FEATURES),"duplicate_events":int(x.duplicated(["code","ymd"]).sum()),"missing_cells":int(x[FEATURES].isna().sum().sum()),"future_used_for_selection":False,"review_only":True,"erasure_sha256":sha(a.erasure_ledger),"feature_sha256":sha(a.features)};(a.output/"audit.json").write_text(json.dumps(audit,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");(a.output/"_ARTIFACT_COMPLETE.json").write_text(json.dumps({"complete":True,"authoritative":"driver_leaderboard.json","sha256":sha(cp)},indent=2)+"\n",encoding="utf-8");print(json.dumps({"output":str(a.output),"judgment":data["judgment"],"stable":[{"feature":z["feature"],"direction":z["consistent_direction"],"strength":z["stable_min_auc_distance"]} for z in stable]},ensure_ascii=False,indent=2))
if __name__=="__main__":main()
