"""Authoritative rollup for MA200 review-only live-readiness research."""
import argparse,hashlib,json
from pathlib import Path
def load(p):return json.loads(Path(p).read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();
 for n in ['monthly','market','core','management','portfolio']:p.add_argument('--'+n,required=True)
 p.add_argument('--output',type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=False)
 mkt=load(a.market);mon=load(a.monthly);core=load(a.core);mg=load(a.management);pf=load(a.portfolio)
 full=pf['clean_oos_2026_by_probe_signal_year'];co=pf['clean_oos_2026_core_executed'];size=pf['portfolio_sizing'];year=core['signal_year_results']
 blockers=[{'type':'clean_oos_full_probe_negative','evidence':{'1_1':full['1_1'],'1_2':full['1_2']}},{'type':'capacity_exceeds_100pct_at_0_50pct_risk','evidence':{'1_1':size['1_1']['0.50%']['max_reserved_capital_pct'],'1_2':size['1_2']['0.50%']['max_reserved_capital_pct']}},{'type':'core_2023_1_2_next_open_failure','evidence':year['2023']['1_2']['next_open']},{'type':'take_profit_next_open_min3_failure','evidence':mg['judgment']}]
 data={'schema_version':'tradex_ma200_live_readiness_rollup_v1.compare.v1','artifact_role':'authoritative_rollup_decision','review_only':True,'fixed_conditions':{'universe':'existing BOX MA200 Nikkei-centered episode population','years':'2020-2026','execution':'signals next-session open','ratios':['probe/core/add 1:1:1','probe/core/add 1:2:2'],'exit':'3% stop, locked TAKE_PROFIT next open, fixed horizon close; downside 3% is diagnostic only','costs':'ignored per project rule','automatic_reflection':False},'authoritative_sources':{k:{'path':str(getattr(a,k)),'sha256':sha(getattr(a,k))} for k in ['monthly','market','core','management','portfolio']},'environment_decomposition':{'monthly_box_width_decision':mon['judgment'],'market_regime_decision':mkt['judgment'],'conclusion':'2022/2026 instability is not repaired by a single monthly BOX-width or broad-market gate; selection/sequence and execution-price quality remain causal candidates'},'core_signal_year_D_R':year,'execution_price_judgment':core['judgment'],'management_execution_judgment':mg['judgment'],'clean_oos_2026':{'all_probe_population':full,'core_executed_population':co,'positive_count_all_probe':{'1_1':full['1_1']['wins'],'1_2':full['1_2']['wins']},'positive_count_core_executed':{'1_1':co['1_1']['wins'],'1_2':co['1_2']['wins']}},'risk':{'year_by_exit':pf['year_results_by_exit_year'],'portfolio_sizing':size,'management_contribution':pf['management_contribution']},'human_anchor_9107':{'core':core['human_anchor_9107'],'strict_episode':pf['human_anchor_9107'],'preserved':all(x.get('management_executed') and x.get('management_action')=='ADD' for x in pf['human_anchor_9107'])},'observed_branching':{'monthly':mon['observed_branching'],'market':mkt['observed_branching'],'core':core['observed_branching'],'strict_episode':pf['observed_branching']},'judgment':{'candidate_local_decision':'hold','session_aggregate_decision':'hold_review_only','authoritative_rollup_decision':'hold_review_only','live_trade_ready':False,'preferred_ratio':None,'blockers':blockers,'reason':'CORE/management contains useful branches and 9107 is preserved, but full probe clean OOS loses, capacity exceeds 100%, 2023 1:2 execution fails, and next-open TAKE_PROFIT does not preserve 3%.'},'next_research_axis':'probe eligibility/capacity selector before entry; do not tune CORE or management simultaneously','not_changed':['MeeMee','ranking','runtime DB','production selection','monthly display']}
 cp=a.output/'compare.json';cp.write_text(json.dumps(data,ensure_ascii=False,indent=2,allow_nan=False)+'\n',encoding='utf-8');(a.output/'audit.json').write_text(json.dumps({'source_count':5,'all_source_artifacts_authoritative':all(v.get('artifact_role','').startswith('authoritative') for v in [mon,mkt,core,mg,pf]),'human_anchor_preserved':data['human_anchor_9107']['preserved'],'automatic_reflection':False},indent=2)+'\n');(a.output/'_ARTIFACT_COMPLETE.json').write_text(json.dumps({'complete':True,'authoritative':'compare.json','sha256':sha(cp)},indent=2)+'\n');print(json.dumps({'output':str(a.output),'judgment':data['judgment'],'clean_oos':data['clean_oos_2026'],'anchor_preserved':data['human_anchor_9107']['preserved']},ensure_ascii=False))
if __name__=='__main__':main()
