import argparse,hashlib,json
from pathlib import Path
import pandas as pd
YEARS=range(2021,2026)
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def rates(x):
 n=len(x);return {'n':n,'down_first':int(x.outcome.eq('down_first').sum()),'rebound_first':int(x.outcome.eq('rebound_first').sum()),'neutral_no_hit':int(x.outcome.eq('neutral_no_hit').sum()),'down_first_pct':None if not n else 100*x.outcome.eq('down_first').mean(),'rebound_first_pct':None if not n else 100*x.outcome.eq('rebound_first').mean()}
def main():
 p=argparse.ArgumentParser();p.add_argument('--sequence',type=Path,required=True);p.add_argument('--daily',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=True)
 d=pd.read_parquet(a.daily,columns=['code','ymd','c','ma60']);d.code=d.code.astype(str).str.zfill(4);d=d.sort_values(['code','ymd']);above=d.c.gt(d.ma60);blocks=above.ne(above.groupby(d.code).shift()).groupby(d.code).cumsum();d['above_ma60_run']=above.groupby([d.code,blocks]).cumcount()+1;d.loc[~above,'above_ma60_run']=0
 s=pd.read_parquet(a.sequence);s.code=s.code.astype(str).str.zfill(4);x=s[s.gd_ymd.notna()&s.ma20_rebreak_ymd.notna()&(s.ma20_rebreak_ymd>s.gd_ymd)&s.weak_rebound&(s.max_consecutive_closes_above_ma7<7)].copy();x['action_ymd']=x.ma20_rebreak_ymd.astype(int);x=x.sort_values('erasure_ymd').drop_duplicates(['code','action_ymd'],keep='last');x['year']=x.action_ymd.astype(str).str[:4].astype(int);x['outcome']=x.ma20_rebreak_outcome_fixed3_h5;x=x.merge(d[['code','ymd','above_ma60_run']],left_on=['code','erasure_ymd'],right_on=['code','ymd'],how='left',validate='one_to_one')
 x['point_strong_gd']=x.gd_gap_pct.le(-.01).astype(int);x['point_weak_bull_recovery']=x.post_gd_max_bull_body_atr.le(.4).astype(int);x['point_mature_ma60_run']=x.above_ma60_run.ge(60).astype(int);x['score']=x[['point_strong_gd','point_weak_bull_recovery','point_mature_ma60_run']].sum(axis=1);x['gate_pass']=x.score.ge(2)
 base={str(y):rates(x[x.year.eq(y)]) for y in YEARS};ch={str(y):rates(x[x.year.eq(y)&x.gate_pass]) for y in YEARS};direction=all(v['down_first']>v['rebound_first'] for v in ch.values());breadth=all(v['n']>=30 for v in ch.values());z=x[(x.code.eq('9962'))&x.action_ymd.eq(20260713)][['score','point_strong_gd','point_weak_bull_recovery','point_mature_ma60_run','outcome']];anchor=z.where(pd.notna(z),None).to_dict('records')
 data={'schema_version':'tradex_weak_rebound_equal_point_score_v1.compare.v1','artifact_role':'authoritative','review_only':True,'axis':'equal-point integration of three independently tested weak-rebound contexts','fixed_conditions':{'points':{'strong_gd':'gap<=-1%','weak_bull_recovery':'max bull body<=0.4ATR','mature_ma60_run':'above MA60 run>=60'},'selection':'score>=2','weights':'equal +1; no fitting','years':list(YEARS),'minimum_each_year':30,'outcome':'inherited exact fixed3 h5'},'baseline_results':base,'challenger_results':ch,'human_anchor_9962':anchor,'observed_branching':{'base_events':len(x),'retained_events':int(x.gate_pass.sum()),'removed_events':int((~x.gate_pass).sum()),'changed_rank_count':int((~x.gate_pass).sum()),'selection_divergence_reason':'multiple independent setup confirmations can compensate for one absent confirmation'},'judgment':{'decision':'keep' if direction and breadth else 'hold','direction_pass_all_years':direction,'breadth_pass':breadth,'anchor_preserved':len(anchor)==1,'failed_years':[y for y,v in ch.items() if v['down_first']<=v['rebound_first']],'reason':'hold integration unless every year passes; use failed years for cohort diagnosis'},'not_changed':['component thresholds','weights','other branches','MeeMee','ranking','runtime DB']}
 cp=a.output/'compare.json';cp.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');x.to_parquet(a.output/'equal_point_score_ledger.parquet',index=False);(a.output/'audit.json').write_text(json.dumps({'duplicates':int(x.duplicated(['code','action_ymd']).sum()),'future_used_for_selection':False,'input_sha256':{'sequence':sha(a.sequence),'daily':sha(a.daily)}},indent=2)+'\n',encoding='utf-8');(a.output/'_ARTIFACT_COMPLETE.json').write_text(json.dumps({'complete':True,'authoritative':'compare.json','sha256':sha(cp)},indent=2)+'\n',encoding='utf-8');print(json.dumps({'output':str(a.output),'challenger':ch,'anchor':anchor,'judgment':data['judgment']},ensure_ascii=False,indent=2))
if __name__=='__main__':main()
