from __future__ import annotations
import argparse,json
from pathlib import Path
import pandas as pd
def met(g):
 z=g[g.executed];miss=g[~g.executed];return {"signals":int(len(g)),"executed":int(len(z)),"execution_rate":float(g.executed.mean()),"rise5_rate_all_signals":float(g.hit5.eq(True).mean()),"rise5_rate_executed":float(z.hit5.mean()) if len(z) else None,"mean_close5_pct_executed":float(z.close_ret.mean()) if len(z) else None,"median_adverse5_pct":float(z.adverse.median()) if len(z) else None,"p10_adverse5_pct":float(z.adverse.quantile(.1)) if len(z) else None,"missed_baseline_hits":int(miss.baseline_hit.sum())}
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--paths",required=True);ap.add_argument("--inventory",required=True);ap.add_argument("--output",required=True);a=ap.parse_args();out=Path(a.output);out.mkdir(parents=True,exist_ok=False)
 p=pd.read_parquet(a.paths);b=pd.read_parquet(a.inventory,columns=["code","ymd","bar_index","o","h","l","c"]);x=p.merge(b[["code","ymd","c"]].rename(columns={"c":"signal_close"}),on=["code","ymd"],validate="many_to_one");z=b.rename(columns={"bar_index":"fi","o":"o6","h":"h6","l":"l6","c":"c6"})[["code","fi","o6","h6","l6","c6"]];x["fi"]=x.bar_index+6;x=x.merge(z,on=["code","fi"],how="left",validate="many_to_one").drop(columns="fi");base_hit=((x[[f"h{k}" for k in range(1,6)]].max(axis=1)/x.o1-1)*100).ge(5)
 pullback=x.d1_low.le(-2)&x.c1.gt(x.o1);defs={"当日引け":(x.signal_close,pd.Series(True,index=x.index),1),"翌日寄り":(x.o1,x.o1.notna(),1),"即上昇確認後":(x.o2,x.entry_day_path.eq("即上昇")&x.o2.notna(),2),"押し目反発確認後":(x.o2,pullback&x.o2.notna(),2)};frames=[]
 for name,(entry,execute,start) in defs.items():
  highs=x[[f"h{k}" for k in range(start,start+5)]].max(axis=1);lows=x[[f"l{k}" for k in range(start,start+5)]].min(axis=1);close=x[f"c{start+4}"];q=x[["code","ymd","period","buy_family"]].copy();q["entry_method"]=name;q["executed"]=execute;q["entry_price"]=entry.where(execute);q["hit5"]=((highs/q.entry_price-1)*100).ge(5).where(execute);q["adverse"]=((lows/q.entry_price-1)*100).where(execute);q["close_ret"]=((close/q.entry_price-1)*100).where(execute);q["baseline_hit"]=base_hit;frames.append(q)
 d=pd.concat(frames);rows=[];yrs=[]
 for (p,f,m),g in d.groupby(["period","buy_family","entry_method"]):rows.append({"period":p,"buy_family":f,"entry_method":m,**met(g)})
 for (y,f,m),g in d.assign(year=d.ymd//10000).groupby(["year","buy_family","entry_method"]):yrs.append({"year":int(y),"buy_family":f,"entry_method":m,**met(g)})
 s=pd.DataFrame(rows);yr=pd.DataFrame(yrs);d.to_parquet(out/"entry_timing_ledger.parquet",index=False);s.to_parquet(out/"entry_timing_metrics.parquet",index=False);yr.to_parquet(out/"entry_timing_yearly_metrics.parquet",index=False);v=s[s.period.eq("validation")];checks={"all_methods_present":len(v)==8,"both_families_n_ge1000":all(v[v.entry_method.isin(["当日引け","翌日寄り"])].signals>=1000)}
 res={"schema_version":"tradex_long_entry_timing_compare_v1.compare.v1","artifact_role":"authoritative_long_entry_timing_compare","review_only":True,"fixed_conditions":{"families":["急落反発","上昇継続"],"methods":{"当日引け":"signal close","翌日寄り":"next open","即上昇確認後":"entry-day high>=3% and low>-3%, following open","押し目反発確認後":"entry-day low<=-2% and close>open, following open"},"horizon":"five sessions from execution","development":"2019-2023","validation":"2024-2026","costs":"ignored"},"authoritative_result":{"validation":v.to_dict("records"),"validation_years":yr[yr.year>=2024].to_dict("records"),"gate_checks":checks},"observed_branching":{"changed_top5_members_count":None,"changed_top10_members_count":None,"changed_rank_count":int((~d.executed).sum()),"selection_divergence_reason":"confirmation methods suppress and delay entries"},"judgment":{"candidate_local_decision":"hold","session_aggregate_decision":"hold_select_entry_after_yearly_review","authoritative_rollup_decision":"hold_long_entry_timing_until_yearly_tradeoff_review","reason_type":"same_population_entry_comparison_completed"},"not_changed":["family membership","MeeMee","ranking","runtime DB","production logic"]}
 (out/"compare.json").write_text(json.dumps(res,ensure_ascii=False,indent=2),encoding="utf-8");(out/"_ARTIFACT_COMPLETE.json").write_text(json.dumps({"complete":True,"authoritative":"compare.json"}));print(json.dumps(v.to_dict("records"),ensure_ascii=False))
if __name__=="__main__":main()
