from __future__ import annotations
import argparse,sys
from datetime import datetime,timezone
from pathlib import Path
import numpy as np,pandas as pd
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:sys.path.insert(0,str(ROOT))
from scripts.tradex_contraction_sequence_challenger_v1 import load_source,build_scores
from scripts.tradex_early_signal_first_detect_v1 import _metrics,_branching
from scripts.tradex_shallow_high_zone_universe_repair_v1 import attach_gap_outcomes,no_reentry_sessions,_sha,_write,extra_metrics
AXIS_ID='tradex_buy_dispersion_concentration_switch_v1';OUT=Path(r'G:\Tradex\tradex_buy_dispersion_concentration_switch_v1');QUANTILES=(.4,.5,.6);WIDTH=.08;PERIODS={'train':(20240101,20241231),'validation':(20250101,20251231),'shadow':(20260101,20261231)}

def dispersion_frame(db_features:pd.DataFrame,db:Path)->pd.DataFrame:
 import duckdb
 with duckdb.connect(str(db),read_only=True) as q:
  rel=q.execute("select cast(strftime(to_timestamp(dt),'%Y%m%d') as int) signal_ymd,cast(code as varchar) code,rel_ret20 from ml_feature_daily where dt between epoch(date '2023-10-01') and epoch(date '2026-12-31')").fetchdf()
 return rel.groupby('signal_ymd').rel_ret20.std(ddof=1).rename('rel_ret20_dispersion').reset_index()

def final_scores(contraction:pd.DataFrame,ranks:pd.DataFrame,disp:pd.DataFrame,threshold:float)->pd.DataFrame:
 x=contraction.merge(disp,on='signal_ymd',how='left',validate='many_to_one');rr=ranks[['signal_ymd','code','baseline_rank']];x=x.merge(rr,on=['signal_ymd','code'],how='left');x['selected_lane']=np.where(x.rel_ret20_dispersion>=threshold,'meemee','contraction');n=x.groupby('signal_ymd').code.transform('size');x['meemee_percentile']=np.where(x.baseline_rank.notna(),1-(x.baseline_rank-1)/n,0.0);x['within_percentile']=np.where(x.selected_lane.eq('meemee'),x.meemee_percentile,x.percentile);x['lane_priority']=np.where(x.selected_lane.eq('meemee'),x.baseline_rank.notna(),x.family_hit).astype(int);x['final_score']=x.lane_priority*2+x.within_percentile;x=x.sort_values(['signal_ymd','final_score','code'],ascending=[True,False,True]);x['final_rank']=x.groupby('signal_ymd').cumcount()+1;x['final_top10']=x.final_rank<=10;x['rank']=x.final_rank;x['top10']=x.final_top10;x['side']='BUY';return x

def generate(db:Path,out:Path)->Path:
 f,b,r,cov=load_source(db);disp=dispersion_frame(f,db);base=attach_gap_outcomes(build_scores(f,b,WIDTH),b);base=base[base.signal_ymd>=20240101].copy();cal=sorted(base.signal_ymd.unique());train=disp[disp.signal_ymd.between(20240101,20241231)].rel_ret20_dispersion.dropna();thresholds={str(int(q*100)):float(train.quantile(q)) for q in QUANTILES};variants=[];sets={};td=sum(d<=20241231 for d in cal)
 for q,t in thresholds.items():
  s=final_scores(base,r,disp,t);e=no_reentry_sessions(s[s.final_rank.eq(1)&s.trade_return_h10.notna()],cal,'final_rank');m=_metrics(e[e.signal_ymd<=20241231],td);variants.append({'train_dispersion_percentile':int(q),'fixed_threshold':t,'train_metrics':m});sets[q]=(s,e)
 chosen=max(variants,key=lambda v:((v['train_metrics']['profit_factor'] if v['train_metrics']['profit_factor'] is not None else -1),v['train_metrics']['expectancy'] if v['train_metrics']['expectancy'] is not None else -1));s,e=sets[str(chosen['train_dispersion_percentile'])];latest=int(f.signal_ymd.max());periods={**PERIODS,'shadow':(20260101,latest)};metrics={};gates={};branch={};coverage={};baselines=[]
 for split,(a,z) in periods.items():
  days=sum(a<=d<=z for d in cal);ch=e[e.signal_ymd.between(a,z)];mm=r[r.signal_ymd.between(a,z)].sort_values(['signal_ymd','baseline_rank','code']).groupby('signal_ymd',as_index=False).head(1).merge(base[['signal_ymd','code','trade_return_h10','exit_day_h10','target_before_stop20','realized_mover20']],on=['signal_ymd','code'],how='left');mm=no_reentry_sessions(mm[mm.trade_return_h10.notna()],cal,'baseline_rank');baselines.append(mm);elig=base[base.signal_ymd.between(a,z)&base.trade_return_h10.notna()];cm={**_metrics(ch,days),**extra_metrics(ch,elig)};bm={**_metrics(mm,days),**extra_metrics(mm,elig)};metrics[split]={'switch_top1':cm,'meemee_buy_top1_same_days':bm};gates[split]={'pf_ge_1_30':(cm['profit_factor'] or 0)>=1.3,'expectancy_positive':(cm['expectancy'] or 0)>0,'pf_improves':cm['profit_factor'] is not None and bm['profit_factor'] is not None and cm['profit_factor']>bm['profit_factor'],'expectancy_improves':cm['expectancy'] is not None and bm['expectancy'] is not None and cm['expectancy']>bm['expectancy'],'cvar_non_degrade':cm['cvar10'] is not None and bm['cvar10'] is not None and cm['cvar10']>=bm['cvar10'],'dd_non_degrade':cm['max_drawdown'] is not None and bm['max_drawdown'] is not None and cm['max_drawdown']>=bm['max_drawdown']};branch[split]=_branching(s[s.final_top10],r.assign(side='BUY'),'BUY',a,z);cnt=s[s.signal_ymd.between(a,z)].groupby('signal_ymd').size();coverage[split]={'days':len(cnt),'min_ranked':int(cnt.min()) if len(cnt) else 0,'all_days_ranked':bool(cnt.gt(0).all()),'meemee_lane_days':int(s[s.signal_ymd.between(a,z)&s.selected_lane.eq('meemee')].signal_ymd.nunique()),'contraction_lane_days':int(s[s.signal_ymd.between(a,z)&s.selected_lane.eq('contraction')].signal_ymd.nunique())}
 train_pass=(chosen['train_metrics']['profit_factor'] or 0)>=1.3 and (chosen['train_metrics']['expectancy'] or 0)>0;keep=train_pass and all(all(gates[x].values()) for x in ('validation','shadow'));root=out/f"{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}-{AXIS_ID}";root.mkdir(parents=True,exist_ok=False);s.to_parquet(root/'all_symbol_daily_final_scores.parquet',index=False);e.to_parquet(root/'switch_entry_ledger.parquet',index=False);pd.concat(baselines,ignore_index=True).to_parquet(root/'meemee_buy_baseline_ledger.parquet',index=False)
 payload={'schema_version':AXIS_ID+'.compare.v1','artifact_role':'authoritative','research_phase':'effectiveness_judgment','fixed_evaluation_conditions':{'single_axis':'same-close PIT daily cross-sectional standard deviation of rel_ret20','direction':'dispersion >= fixed threshold routes MeeMee BUY; lower routes contraction-sequence','threshold_variants':'2024 daily dispersion percentiles 40/50/60; numeric threshold frozen','contraction_score':'existing contraction sequence width 8% all-symbol score','ranking':'all symbols daily; selected lane priority plus within-lane percentile; top1 entry','execution':'next-open TP8/SL5/H10/10bp; gap-through actual open; open reentry prohibited','splits':'2024 train/2025 untouched validation/2026 untouched shadow','baseline':'MeeMee BUY top1 same days','survivorship_filter':False,'fallback':False,'tuning_after_2024':False},'source_artifacts':[{'path':str(db),'sha256':_sha(db)}],'source_coverage':cov,'train_dispersion_distribution':{'n':len(train),'p40':thresholds['40'],'p50':thresholds['50'],'p60':thresholds['60']},'train_variants':variants,'selected_variant':chosen,'metrics':metrics,'adoption_gates':gates,'branching':branch,'rank_coverage':coverage,'decision':{'candidate_local_decision':'keep' if keep else 'drop','authoritative_rollup_decision':'review_only','train_pf_gate_pass':train_pass},'shadow_tuning_used':False,'silent_fallback_used':False,'runtime_db_write':False,'production_ranking_changed':False,'meemee_changed':False};p=root/'compare.json';_write(p,payload);_write(root/'_ARTIFACT_COMPLETE.json',{'complete':True,'compare':str(p)});return p
def main():
 p=argparse.ArgumentParser();p.add_argument('--db',type=Path,required=True);p.add_argument('--out',type=Path,default=OUT);a=p.parse_args();print(generate(a.db,a.out))
if __name__=='__main__':main()
