from __future__ import annotations
import argparse,json,subprocess,sys
from datetime import datetime,timezone
from pathlib import Path

ALLOWED_ACTIONS={"ENTRY_REVIEW_NEXT_OPEN","WATCH_NO_ENTRY","WAIT_NO_ENTRY","AVOID_NO_ENTRY","CHART_REVIEW_REQUIRED","HOLDING_REVIEW_NO_NEW_ENTRY"}

def main():
 p=argparse.ArgumentParser();p.add_argument('--output',required=True);p.add_argument('--operational-board',type=Path,required=True);p.add_argument('--tail-exit-compare',type=Path,required=True);a=p.parse_args();out=Path(a.output);out.mkdir(parents=True,exist_ok=False);board=json.loads(a.operational_board.read_text(encoding='utf-8'));tail=json.loads(a.tail_exit_compare.read_text(encoding='utf-8'))
 test=subprocess.run([sys.executable,'-m','pytest','tests/test_tradex_long_fresh_operational_board_v1.py','-q'],cwd=Path(__file__).resolve().parents[1],capture_output=True,text=True);result=board['authoritative_result'];rows=result['new_entry_candidates'];entry_rows=[x for x in rows if x['new_entry_action']=='ENTRY_REVIEW_NEXT_OPEN'];vd=tail['authoritative_result']['chosen_without_2026']['deltas']['validation_2024_2025'];ad=tail['authoritative_result']['chosen_without_2026']['deltas']['audit_2026']
 checks={'operational_board_ready':board['judgment']['authoritative_rollup_decision']=='PRODUCTION_DECISION_SUPPORT_READY','runtime_freshness_pass':board['runtime_freshness_guard']['pass'],'latest_matches_confirmed':board['latest_as_of']==board['runtime_freshness_guard']['confirmed_max_date'],'all_actions_typed':all(x['new_entry_action'] in ALLOWED_ACTIONS for x in rows),'entry_requires_same_day_starter':all(x.get('chart_status')=='Starter' for x in entry_rows),'entry_templates_complete':all(all(x['entry_registration_template'].get(k) is not None for k in ['strategy_id','code','signal_date','signal_tail_risk','high_tail_risk']) for x in entry_rows),'managed_entries_have_no_stop':result['stop_count']==0,'automatic_order_execution_disabled':board['fixed_contract']['automatic_order_execution'] is False,'runtime_db_write_disabled':board['fixed_contract']['runtime_db_write'] is False,'meemee_unchanged':board['fixed_contract']['meemee_changed'] is False,'validation_return_drawdown_loss_improve':vd['return_pct_points']>0 and vd['max_drawdown_pct_points']>=0 and vd['raw_loss5_rate_points']<0,'audit_return_drawdown_loss_improve':ad['return_pct_points']>0 and ad['max_drawdown_pct_points']>=0 and ad['raw_loss5_rate_points']<0,'operational_tests_pass':test.returncode==0}
 decision='production_decision_support_ready' if all(checks.values()) else 'hold';payload={'schema_version':'tradex_long_fresh_operational_adoption_audit_v1.audit.v1','artifact_role':'authoritative','generated_at':datetime.now(timezone.utc).isoformat(),'source_operational_board':str(a.operational_board),'source_tail_exit_compare':str(a.tail_exit_compare),'fixed_scope':{'boundary_owner':'TRADEX','production_mode':'decision support with explicit entry registration and close review; no automatic order execution','data':'confirmed PAN daily bars only','production_ranking_changed':False,'meemee_changed':False},'authoritative_result':{'checks':checks,'entry_review_count':len(entry_rows),'entry_review_codes':[x['code'] for x in entry_rows],'test_command':test.args,'test_returncode':test.returncode,'test_stdout':test.stdout.strip(),'validation_deltas':vd,'audit_2026_deltas':ad},'judgment':{'candidate_local_decision':decision,'session_aggregate_decision':decision,'authoritative_rollup_decision':decision,'reason_type':'fresh_fail_closed_operational_reproduction_and_oos_improvement'},'remaining_risks':['decision support does not place orders','same-day chart review remains a required human/Codex confirmation step','executed entries must be registered with actual entry date and price']}
 (out/'audit.json').write_text(json.dumps(payload,ensure_ascii=False,indent=2,default=str),encoding='utf-8');(out/'_ARTIFACT_COMPLETE.json').write_text(json.dumps({'complete':True,'authoritative':'audit.json'}),encoding='utf-8');print(json.dumps({'decision':decision,'entry_codes':payload['authoritative_result']['entry_review_codes'],'checks':checks},ensure_ascii=False))
if __name__=='__main__':main()
