from __future__ import annotations
import argparse,json
from datetime import datetime,timezone
from pathlib import Path
import duckdb,pandas as pd
BUY=Path(r'G:\Tradex\meemee_leaf_consensus_top3_v1\20260713T050728Z-tradex_meemee_leaf_consensus_top3_v1\baseline_events.csv');SELL=Path(r'G:\Tradex\short_leaf20_event_ledger_v1\20260713T044404Z-tradex_short_leaf20_event_ledger_v1\event_ledger.parquet');DB=Path(r'G:\Tradex\scratch\source_snapshots\nightly_candidate_20260713_20260713T002453985795Z.duckdb');OUT=Path(r'G:\Tradex\breadth40_exclusive_side_router_audit_v1')
def metrics(x):
 r=x.side_return;d=x.groupby('signal_ymd').side_return.mean();neg=-d[d<0].sum();loss=r[r<0];cut=r.quantile(.1)if len(r)else None;weeks=pd.to_datetime(x.signal_ymd.astype(str),format='%Y%m%d').dt.strftime('%G-W%V').nunique()if len(x)else 0
 return {'n':len(x),'signal_days':int(x.signal_ymd.nunique())if len(x)else 0,'signal_days_per_week':x.signal_ymd.nunique()/weeks if weeks else None,'daily_equal_weight_expectancy':float(d.mean())if len(d)else None,'daily_equal_weight_profit_factor':float(d[d>0].sum()/neg)if neg else None,'win_rate':float((r>0).mean())if len(r)else None,'payoff_ratio':float(r[r>0].mean()/abs(loss.mean()))if len(r[r>0])and len(loss)else None,'p05':float(r.quantile(.05))if len(r)else None,'cvar10':float(r[r<=cut].mean())if cut is not None else None,'buy_days':int(x.loc[x.side=='buy','signal_ymd'].nunique())if len(x)else 0,'sell_days':int(x.loc[x.side=='sell','signal_ymd'].nunique())if len(x)else 0}
def prepare(buy,sell):
 b=buy.copy();b['signal_ymd']=b.dt.astype(int);b['side']='buy';b['side_return']=b.pnl_yen/b.invested_yen;b['breadth_below_ma20']=pd.to_numeric(b.get('breadth_below_ma20'),errors='coerce');s=sell.copy();s['side']='sell';s['side_return']=s.ret.astype(float);return b,s
def generate(buy:Path,sell:Path,db:Path,out:Path)->Path:
 b=pd.read_csv(buy);s=duckdb.connect().execute(f"select * from read_parquet('{sell}') where signal_ymd between 20240101 and 20261231").fetchdf();b,s=prepare(b,s)
 q="""with u as(select code from daily_bars where source='pan'group by code having max(date)=(select max(date)from daily_bars where source='pan')),x as(select code,cast(strftime(to_timestamp(date),'%Y%m%d')as int)signal_ymd,c,avg(c)over(partition by code order by date rows between 19 preceding and current row)ma20 from daily_bars join u using(code)where source='pan')select signal_ymd,avg(case when c<ma20 then 1.0 else 0.0 end)breadth_below_ma20 from x where signal_ymd between 20240101 and 20261231 group by signal_ymd""";breadth=duckdb.connect(str(db),read_only=True).execute(q).fetchdf();b=b.drop(columns=['breadth_below_ma20'],errors='ignore').merge(breadth,on='signal_ymd',how='left');missing=int(b.breadth_below_ma20.isna().sum());rb=b[b.breadth_below_ma20<.40].copy();rs=s[s.breadth_below_ma20>=.40].copy();router=pd.concat([rb,rs],ignore_index=True,sort=False);baseline=b.copy()
 split=lambda y:'train'if y<20250101 else('validation'if y<20260101 else'shadow');router['split']=router.signal_ymd.map(split);baseline['split']=baseline.signal_ymd.map(split);rm={q:metrics(router[router.split==q])for q in ('train','validation','shadow')};bm={q:metrics(baseline[baseline.split==q])for q in ('train','validation','shadow')}
 now=datetime.now(timezone.utc);root=out/f"{now.strftime('%Y%m%dT%H%M%SZ')}-tradex_breadth40_exclusive_side_router_audit_v1";root.mkdir(parents=True);router.to_csv(root/'router_events.csv',index=False);baseline.to_csv(root/'baseline_buy_events.csv',index=False);p={'schema_version':'tradex_breadth40_exclusive_side_router_audit_v1.compare.v1','artifact_role':'authoritative','fixed_contract':{'threshold':.40,'rule':'breadth<.40 buy MeeMee top3; breadth>=.40 sell support-break only','exclusive_side':True,'capital_allocation_integrated':False,'holding_integrated':False,'splits':{'train':2024,'validation':2025,'shadow':2026}},'router':rm,'baseline_meemee_buy':bm,'delta':{q:{'daily_pf':None if rm[q]['daily_equal_weight_profit_factor']is None or bm[q]['daily_equal_weight_profit_factor']is None else rm[q]['daily_equal_weight_profit_factor']-bm[q]['daily_equal_weight_profit_factor'],'expectancy':None if rm[q]['daily_equal_weight_expectancy']is None or bm[q]['daily_equal_weight_expectancy']is None else rm[q]['daily_equal_weight_expectancy']-bm[q]['daily_equal_weight_expectancy']}for q in rm},'coverage':{'buy_rows_missing_breadth':missing,'silent_fallback':False},'decision':{'authoritative_rollup_decision':'candidate_direction_audit_only'},'threshold_or_rules_changed':False,'runtime_db_write':False,'production_ranking_changed':False};path=root/'compare.json';path.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n');return path
def main():
 a=argparse.ArgumentParser();a.add_argument('--buy',type=Path,default=BUY);a.add_argument('--sell',type=Path,default=SELL);a.add_argument('--db',type=Path,default=DB);a.add_argument('--out',type=Path,default=OUT);x=a.parse_args();print(generate(x.buy,x.sell,x.db,x.out))
if __name__=='__main__':main()
