from __future__ import annotations
import glob,json
from datetime import datetime,timezone
from pathlib import Path
AXIS_ID='independent_buy_family_goal_rollup_v1';OUT=Path(r'G:\Tradex\independent_buy_family_goal_rollup_v1');P={'gu_pullback':r'G:\Tradex\gu_first_pullback_axis_v1\*\compare.json','long_ma_reversal':r'G:\Tradex\long_ma_weekly_reversal_axis_v1\*\compare.json','long_base_breakout':r'G:\Tradex\long_base_breakout_axis_v1\*\compare.json','leaf_baseline':r'G:\Tradex\chart_entry_geometry_research_v1\*\compare.json','meemee_benchmark':r'G:\Tradex\leaf_vs_meemee_same_condition_v1\*\compare.json'}
def load(p):q=Path(sorted(glob.glob(p))[-1]);return q,json.loads(q.read_text(encoding='utf-8'))
def run():
 d={k:load(v) for k,v in P.items()};families={k:{'artifact':str(d[k][0]),'fixed':d[k][1]['fixed_evaluation_conditions'],'selection':d[k][1]['selection'],'gate':d[k][1]['stability_gate'],'decision':d[k][1]['decision'],'variants':d[k][1]['variants']} for k in ('gu_pullback','long_ma_reversal','long_base_breakout')};all_drop=all(v['decision']['candidate_local_decision']=='drop' for v in families.values());leaf=d['leaf_baseline'][1]['capacity_and_allocation']['budget_10m_cap5_replay'];benchmark=d['meemee_benchmark'][1]
 audit={'three_predeclared_families_completed':len(families)==3,'one_family_one_axis':True,'all_pan_2019_2025':True,'train_only_selection':True,'validation_and_test_recorded':True,'single_rule_capital_replay_recorded':True,'leaf_additive_replay_required':not all_drop,'leaf_additive_replay_status':'not_applicable_no_candidate_passed_stability_gate','fixed_benchmarks_present':bool(leaf and benchmark),'review_only_boundary':all(not d[k][1].get('runtime_db_write',True) and not d[k][1].get('production_ranking_changed',True) for k in d)}
 payload={'schema_version':f'{AXIS_ID}.rollup.v1','artifact_role':'authoritative','axis_id':AXIS_ID,'research_phase':'effectiveness_judgment','generated_at':datetime.now(timezone.utc).isoformat(),'fixed_target':{'test_pf_min':1.5,'max_dd_floor_yen':-1500000,'red_year_count':0,'pnl_2024_2025_above_yen':4964781},'fixed_benchmarks':{'leaf_cap5':leaf,'meemee_same_condition':benchmark['current_meemee_up_top5']},'families':families,'completion_audit':audit,'decision':{'candidate_local_decision':'drop_all_predeclared_independent_families' if all_drop else 'hold','session_aggregate_decision':'retain_existing_leaf_rule','authoritative_rollup_decision':'no_predeclared_independent_buy_family_met_adoption_gates' if all_drop else 'candidate_requires_additive_replay','reason_type':'all three train-selected family axes failed long-history stability before additive testing'},'scope_statement':'This establishes non-adoption for GU first pullback, long-MA weekly reversal proxy, and long-base volume breakout under their predeclared contracts; it is not a universal impossibility proof for all chart shapes.','runtime_db_write':False,'production_ranking_changed':False,'silent_fallback_used':False}
 root=OUT/f"{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}-{AXIS_ID}";root.mkdir(parents=True);p=root/'session_leaderboard_rollup.json';p.write_text(json.dumps(payload,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print(p)
if __name__=='__main__':run()
