"""Reveal a frozen 32-event board and validate the fixed HZF short veto."""
import argparse, hashlib, json
from pathlib import Path
import duckdb, pandas as pd

SELL={"PROBE","CORE","ADD","REENTRY_PROBE"};BLOCKED="HIGH_ZONE_FAILURE"
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def evaluate(group,ymd):
    hit=group.index[group.ymd.eq(ymd)]
    if len(hit)!=1 or int(hit[0])+5>=len(group):return {"status":"censored"}
    window=group.iloc[int(hit[0])+1:int(hit[0])+6];entry=float(window.iloc[0].o);target=entry*.97;stop=entry*1.03;price=float(window.iloc[-1].c);out="N";reason="horizon_close";exit_ymd=int(window.iloc[-1].ymd)
    for row in window.itertuples():
        if row.o>=stop:price,out,reason,exit_ymd=float(row.o),"R","gap_stop",int(row.ymd);break
        if row.o<=target:price,out,reason,exit_ymd=float(row.o),"D","gap_target",int(row.ymd);break
        if row.h>=stop and row.l<=target:price,out,reason,exit_ymd=stop,"R","same_bar_stop_first",int(row.ymd);break
        if row.h>=stop:price,out,reason,exit_ymd=stop,"R","stop",int(row.ymd);break
        if row.l<=target:price,out,reason,exit_ymd=target,"D","target",int(row.ymd);break
    return {"status":"complete","entry_ymd":int(window.iloc[0].ymd),"exit_ymd":exit_ymd,"entry_open":entry,"exit_price_fixed3":price,"exit_reason_fixed3":reason,"outcome_fixed3":out,"return_fixed3_pct":100*(entry-price)/entry,"return_h5_close_pct":100*(entry-float(window.iloc[-1].c))/entry}
def stats(frame):
    x=frame[frame.status.eq("complete")].sort_values(["exit_ymd","code"]);v=x.return_fixed3_pct;gain=v[v>0].sum();loss=-v[v<0].sum();equity=v.cumsum();dd=equity-equity.cummax() if len(equity) else pd.Series(dtype=float);run=maxrun=0
    for value in v:run=run+1 if value<0 else 0;maxrun=max(maxrun,run)
    concurrent=0
    for day in sorted(set(x.entry_ymd).union(x.exit_ymd)) if len(x) else []:concurrent=max(concurrent,int(((x.entry_ymd<=day)&(x.exit_ymd>=day)).sum()))
    return {"n":int(len(frame)),"completed":int(len(x)),"D":int(x.outcome_fixed3.eq("D").sum()),"R":int(x.outcome_fixed3.eq("R").sum()),"N":int(x.outcome_fixed3.eq("N").sum()),"D_rate":float(x.outcome_fixed3.eq("D").mean()) if len(x) else None,"R_rate":float(x.outcome_fixed3.eq("R").mean()) if len(x) else None,"mean_fixed3_pct":float(v.mean()) if len(v) else None,"mean_h5_close_pct":float(x.return_h5_close_pct.mean()) if len(x) else None,"profit_factor":None if loss==0 else float(gain/loss),"max_loss_pct":float(v.min()) if len(v) else None,"sum_return_units_pct":float(v.sum()),"max_drawdown_units_pct":0.0 if dd.empty else float(dd.min()),"max_loss_streak":int(maxrun),"max_concurrent":int(concurrent)}
def main():
    ap=argparse.ArgumentParser();ap.add_argument("--discovery",type=Path,required=True);ap.add_argument("--human-freeze",type=Path,required=True);ap.add_argument("--sealed",type=Path,required=True);ap.add_argument("--board",type=Path,required=True);ap.add_argument("--db",type=Path,required=True);ap.add_argument("--output",type=Path,required=True);a=ap.parse_args();a.output.mkdir(parents=True,exist_ok=False)
    discovery=json.loads(a.discovery.read_text(encoding="utf-8"));fixed=discovery["judgment"]["fixed_candidate"];allowed=set(fixed["allowed_environments"])
    if discovery["judgment"]["authoritative_rollup_decision"]!="hold_pending_unused_validation" or allowed!={"MATURE_BOX_UPPER","POST_BOX_RETURN_SELL","UNKNOWN_OR_BREAKDOWN"}:raise RuntimeError("discovery candidate is not the frozen HZF veto")
    human=pd.read_parquet(a.human_freeze/"human_direction_frozen.parquet");sealed=pd.read_parquet(a.sealed/"machine_annotation_sealed.parquet");board=pd.read_parquet(a.board,columns=["case_id","code","ymd"])
    data=human.merge(sealed,on=["case_id","code","ymd"],validate="one_to_one").merge(board,on=["case_id","code","ymd"],validate="one_to_one");data.code=data.code.astype(str).str.zfill(4)
    if len(data)!=32 or data.code.nunique()!=32 or not data.model_action.isin(SELL).all():raise RuntimeError("frozen sample contract failed")
    con=duckdb.connect(str(a.db),read_only=True);prices=con.execute("select code,strftime(to_timestamp(date),'%Y%m%d')::integer ymd,o,h,l,c from daily_bars where code in (select unnest(?)) order by code,date",[data.code.unique().tolist()]).fetchdf();con.close();prices.code=prices.code.astype(str).str.zfill(4);history={code:g.reset_index(drop=True) for code,g in prices.groupby("code")}
    rows=[]
    for row in data.itertuples():rows.append({**row._asdict(),**evaluate(history[row.code],int(row.ymd))})
    ledger=pd.DataFrame(rows);ledger["year"]=ledger.ymd//10000;ledger["model_direction"]="SELL";ledger["gate_sell"]=ledger.monthly_state.isin(allowed);ledger["human_sell"]=ledger.human_direction.eq("SELL")
    baseline=stats(ledger);gate=stats(ledger[ledger.gate_sell]);human_stats=stats(ledger[ledger.human_sell]);dret=gate["D"]/baseline["D"] if baseline["D"] else None
    conditions={"D_retention_ge_0_70":dret is not None and dret>=.70,"R_rate_strictly_lower":gate["R_rate"]<baseline["R_rate"],"max_loss_strictly_better":gate["max_loss_pct"]>baseline["max_loss_pct"],"gated_model_expectancy_positive":gate["mean_fixed3_pct"]>0};keep=all(conditions.values())
    discovery_metrics=fixed["metrics"];discovery_dret=float(fixed["D_retention"])
    stability_failures=[]
    if discovery_metrics["mean_fixed3_pct"]>0 and gate["mean_fixed3_pct"]<=0:stability_failures.append("mean_expectancy_sign_reversal")
    if discovery_metrics["profit_factor"]>1 and (gate["profit_factor"] is None or gate["profit_factor"]<=1):stability_failures.append("profit_factor_fell_below_one")
    if discovery_dret>=.70 and (dret is None or dret<.70):stability_failures.append("D_retention_fell_below_keep_floor")
    if gate["R_rate"]>=baseline["R_rate"]:stability_failures.append("unused_R_rate_not_improved")
    sample_stability={"discovery_fixed_candidate":{"sample_rows":int(fixed["metrics"]["n"]),"D_retention":discovery_dret,"mean_fixed3_pct":float(discovery_metrics["mean_fixed3_pct"]),"profit_factor":discovery_metrics["profit_factor"],"R_rate":float(discovery_metrics["R_rate"]),"max_loss_pct":float(discovery_metrics["max_loss_pct"]),"keep_conditions_pass":bool(fixed["keep_conditions_pass"])},"unused_validation":{"sample_rows":int(gate["n"]),"D_retention":dret,"mean_fixed3_pct":float(gate["mean_fixed3_pct"]),"profit_factor":gate["profit_factor"],"R_rate":float(gate["R_rate"]),"max_loss_pct":float(gate["max_loss_pct"]),"keep_conditions_pass":keep},"directionally_stable":not stability_failures,"stability_failures":stability_failures}
    ledger_path=a.output/"monthly_environment_gate_validation_ledger.parquet";ledger.to_parquet(ledger_path,index=False)
    result={"schema_version":"tradex_monthly_environment_gate_unused_validation_v1.compare.v1","artifact_role":"authoritative_unused_monthly_environment_gate_validation","review_only":True,"research_phase":"effectiveness_judgment","fixed_conditions":{"human_frozen_before_reveal":True,"sample_rows":32,"unique_codes":32,"case_control_environment_mix":{"HIGH_ZONE_FAILURE":16,"MATURE_BOX_UPPER":8,"POST_BOX_RETURN_SELL":8},"fixed_gate":"block HIGH_ZONE_FAILURE; allow other monthly states","execution":"next_session_open","horizon_sessions":5,"barriers":"short target -3%, stop +3%, same-bar stop-first","costs":"ignored","weekly_inputs":[],"aggregate_pf_is_natural_frequency_estimate":False},"current_champion":"ungated_model_sell","current_challenger":"fixed_HZF_veto","authoritative_results":{"model_ungated":baseline,"model_HZF_veto":gate,"human_sell_reference":human_stats},"observed_branching":{"model_candidates":baseline["n"],"gate_candidates":gate["n"],"blocked":int((~ledger.gate_sell).sum()),"blocked_outcomes":{str(k):int(v) for k,v in ledger[~ledger.gate_sell].outcome_fixed3.value_counts().items()},"D_retention":dret,"R_removed":baseline["R"]-gate["R"],"selection_divergence_reason":"HIGH_ZONE_FAILURE veto removed half of the frozen model-sell sample"},"sample_stability":sample_stability,"by_environment":{str(k):stats(v) for k,v in ledger.groupby("monthly_state")},"by_action":{str(k):stats(v) for k,v in ledger.groupby("model_action")},"by_environment_action":{f"{e}:{action}":stats(v) for (e,action),v in ledger.groupby(["monthly_state","model_action"])},"by_year":{str(k):stats(v) for k,v in ledger.groupby("year")},"direction_pairs":{str(k):stats(v) for k,v in ledger.groupby(ledger.model_direction+"__"+ledger.human_direction)},"judgment":{"candidate_local_decision":"keep" if keep else "drop","session_aggregate_decision":"keep_review_only" if keep else "drop_monthly_environment_only_axis","authoritative_rollup_decision":"keep_review_only" if keep else "drop","keep_conditions":conditions,"next_axis_if_drop":"market_regime_only"},"not_changed":["MeeMee","ranking","runtime DB","production trading logic"]}
    compare=a.output/"compare.json";compare.write_text(json.dumps(result,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");audit={"sources":{"discovery":{"path":str(a.discovery.resolve()),"sha256":sha(a.discovery)},"human_freeze":{"path":str((a.human_freeze/"compare.json").resolve()),"sha256":sha(a.human_freeze/"compare.json")},"sealed":{"path":str((a.sealed/"machine_annotation_sealed.parquet").resolve()),"sha256":sha(a.sealed/"machine_annotation_sealed.parquet")},"board":{"path":str(a.board.resolve()),"sha256":sha(a.board)},"db":{"path":str(a.db.resolve()),"read_only":True}},"rows":len(ledger),"completed":int(ledger.status.eq("complete").sum()),"weekly_columns_used":[],"ledger_sha256":sha(ledger_path),"compare_sha256":sha(compare)};(a.output/"audit.json").write_text(json.dumps(audit,indent=2)+"\n",encoding="utf-8");(a.output/"_ARTIFACT_COMPLETE.json").write_text(json.dumps({"complete":True,"authoritative":"compare.json","sha256":sha(compare)},indent=2)+"\n",encoding="utf-8");print(json.dumps({"output":str(a.output),"results":result["authoritative_results"],"branching":result["observed_branching"],"judgment":result["judgment"]},ensure_ascii=False,indent=2))
if __name__=="__main__":main()
