"""One-axis challenger: repeated upper supply in the five bars before full erasure."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
import pandas as pd

YEARS=(2023,2024,2025)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rates(x):return {"n":int(len(x)),"codes":int(x.code.nunique()),"down_first":None if x.empty else float(x.label.eq(0).mean()),"rebound_first":None if x.empty else float(x.label.eq(1).mean()),"neutral":None if x.empty else float(x.label.eq(2).mean())}
def main():
 p=argparse.ArgumentParser();p.add_argument("--erasure-ledger",type=Path,required=True);p.add_argument("--features",type=Path,required=True);p.add_argument("--output",type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=False)
 e=pd.read_parquet(a.erasure_ledger);e=e[e.challenger&e.year.isin(YEARS)].copy();f=pd.read_parquet(a.features,columns=["code","ymd","upper_supply_count5"]);x=e.merge(f,on=["code","ymd"],how="left",validate="one_to_one");q=x[x.upper_supply_count5.ge(2)].copy()
 years={str(y):{"baseline":rates(x[x.year.eq(y)]),"challenger":rates(q[q.year.eq(y)])} for y in YEARS};breadth=all(years[str(y)]["challenger"]["n"]>=30 for y in YEARS);positive=breadth and all(years[str(y)]["challenger"]["down_first"]>years[str(y)]["challenger"]["rebound_first"] for y in YEARS);anchor=q[(q.code.astype(str).str.zfill(4)=="2802")&q.ymd.eq(20240206)].where(pd.notna(q),None).to_dict("records")
 data={"schema_version":"tradex_full_erasure_upper_supply_oos_v1.compare.v1","artifact_role":"authoritative","axis":"repeated upper supply before UPTREND_FULL_ERASURE","fixed_conditions":{"base_family":"UPTREND_FULL_ERASURE unchanged","single_filter":"upper_supply_count5>=2","meaning":"at least two upper-rejection/supply bars in the current five-bar context","threshold_sweep":False,"outcome":"inherited exact OHLC symmetric fixed 3 percent h5","years":list(YEARS)},"year_results":years,"overall":{"baseline":rates(x),"challenger":rates(q)},"human_anchor_2802":anchor,"observed_branching":{"removed_event_count":int(len(x)-len(q)),"kept_event_count":int(len(q)),"changed_top5_members_count":None,"changed_top10_members_count":None,"changed_rank_count":None,"selection_divergence_reason":"single full-erasure candles are separated from repeated recent upper supply"},"judgment":{"decision":"keep" if positive and len(anchor)==1 else "drop","breadth_pass":breadth,"down_exceeds_rebound_all_years":positive,"human_anchor_preserved":len(anchor)==1,"reason":"keep requires 2802 anchor, >=30 events and down-first dominance in every OOS year"},"not_changed":["full-erasure candle","monthly environment","oversold risk","other shape features","position lifecycle","MeeMee","ranking","runtime DB"]}
 cp=a.output/"compare.json";cp.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");q.to_parquet(a.output/"filtered_event_ledger.parquet",index=False);audit={"base_events":int(len(x)),"challenger_events":int(len(q)),"missing_feature":int(x.upper_supply_count5.isna().sum()),"duplicates":int(x.duplicated(["code","ymd"]).sum()),"future_used_for_selection":False,"review_only":True,"source_sha256":sha(a.erasure_ledger),"features_sha256":sha(a.features)};(a.output/"audit.json").write_text(json.dumps(audit,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");(a.output/"_ARTIFACT_COMPLETE.json").write_text(json.dumps({"complete":True,"authoritative":"compare.json","sha256":sha(cp)},indent=2)+"\n",encoding="utf-8");print(json.dumps({"output":str(a.output),"year_results":years,"anchor":anchor,"judgment":data["judgment"],"branching":data["observed_branching"]},ensure_ascii=False,indent=2))
if __name__=="__main__":main()
