"""Evaluate one daily feature at a time with environment-specific walk-forward direction."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
import pandas as pd

TEST_YEARS=(2021,2022,2023,2024,2025)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rates(x):return {"n":int(len(x)),"codes":int(x.code.nunique()),"down_first":None if x.empty else float(x.outcome.eq("down_first").mean()),"rebound_first":None if x.empty else float(x.outcome.eq("rebound_first").mean()),"neutral":None if x.empty else float(x.outcome.str.startswith("neutral").mean())}
def main():
 p=argparse.ArgumentParser();p.add_argument("--candidate-union",type=Path,required=True);p.add_argument("--feature",required=True);p.add_argument("--fixed-direction",choices=["HIGHER_IS_DOWN","LOWER_IS_DOWN"]);p.add_argument("--include-source-family-context",action="store_true");p.add_argument("--output",type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=False);x=pd.read_parquet(a.candidate_union);x["score_context"]=x.base_regime.fillna("MISSING").astype(str)+("|"+x.source_families.astype(str) if a.include_source_family_context else "")
 if a.feature not in x.columns:raise SystemExit(f"missing feature: {a.feature}")
 score_rows=[];tables={};results={}
 for year in TEST_YEARS:
  train=x[(x.year<year)&x.outcome.isin(["down_first","rebound_first"])];test=x[x.year.eq(year)].copy();test["feature_point"]=0;table={}
  for env,z in train.groupby("score_context",dropna=False):
   dn=z[z.outcome.eq("down_first")][a.feature].dropna();rb=z[z.outcome.eq("rebound_first")][a.feature].dropna();key="MISSING" if pd.isna(env) else str(env)
   if len(dn)<10 or len(rb)<10:table[key]={"train_down_n":int(len(dn)),"train_rebound_n":int(len(rb)),"eligible":False};continue
   threshold=float(z[a.feature].median());direction=a.fixed_direction or ("LOWER_IS_DOWN" if float(dn.median())<float(rb.median()) else "HIGHER_IS_DOWN");mask=test.score_context.eq(env);fav=test[a.feature].le(threshold) if direction=="LOWER_IS_DOWN" else test[a.feature].ge(threshold);test.loc[mask&fav,"feature_point"]=1;test.loc[mask&~fav,"feature_point"]=-1;table[key]={"train_down_n":int(len(dn)),"train_rebound_n":int(len(rb)),"eligible":True,"threshold_train_median":threshold,"down_median":float(dn.median()),"rebound_median":float(rb.median()),"direction":direction,"direction_source":"fixed" if a.fixed_direction else "training_medians"}
  selected=test[test.feature_point>0];tables[str(year)]=table;results[str(year)]={"baseline":rates(test),"selected_positive_feature_point":rates(selected)};score_rows.append(test)
 scored=pd.concat(score_rows,ignore_index=True);direction=all(results[str(y)]["selected_positive_feature_point"]["n"]>0 and results[str(y)]["selected_positive_feature_point"]["down_first"]>results[str(y)]["selected_positive_feature_point"]["rebound_first"] for y in TEST_YEARS);breadth=all(results[str(y)]["selected_positive_feature_point"]["n"]>=30 for y in TEST_YEARS)
 anchors=[]
 for code,ymd in [("9107",20241122),("4755",20251114),("6857",20240903)]:
  z=scored[(scored.code.astype(str).str.zfill(4)==code)&scored.ymd.eq(ymd)];anchors.append({"code":code,"ymd":ymd,"present":not z.empty,"point":None if z.empty else int(z.feature_point.iloc[0]),"selected":False if z.empty else bool(z.feature_point.iloc[0]>0)})
 data={"schema_version":"tradex_core_env_feature_walkforward_v1.compare.v1","artifact_role":"authoritative","axis":f"context-conditioned {a.feature} point","fixed_conditions":{"candidate_union":"unchanged","single_daily_feature":a.feature,"context":"monthly environment plus source family" if a.include_source_family_context else "monthly environment","train":"decisive outcomes strictly before test year, separately by context","direction":"fixed "+a.fixed_direction if a.fixed_direction else "compare prior down median versus rebound median","threshold":"prior context median","point":"favorable half +1; unfavorable half -1","selection":"feature point > 0","test_years":list(TEST_YEARS),"minimum_train_class":10,"minimum_test_year":30,"threshold_sweep":False},"year_tables":tables,"year_results":results,"human_anchor_scores":anchors,"observed_branching":{"scored_rows":int(len(scored)),"selected_rows":int(scored.feature_point.gt(0).sum()),"changed_rank_count":1,"selection_divergence_reason":"one daily feature is interpreted separately inside the configured context"},"judgment":{"decision":"keep" if direction and breadth else "drop","direction_pass_all_years":direction,"breadth_pass":breadth,"reason":"single feature passes every walk-forward year" if direction and breadth else "single feature remains directionally unstable across walk-forward years"},"not_changed":["candidate events","monthly environment labels","source branch labels","other daily features","human episode actions","MeeMee","ranking","runtime DB"]}
 cp=a.output/"compare.json";cp.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");par=a.output/"walkforward_feature_scores.parquet";scored.to_parquet(par,index=False);audit={"scored_rows":int(len(scored)),"duplicates":int(scored.duplicated(["code","ymd"]).sum()),"missing_feature":int(scored[a.feature].isna().sum()),"future_used_for_score":False,"review_only":True,"source_sha256":sha(a.candidate_union)};(a.output/"audit.json").write_text(json.dumps(audit,indent=2)+"\n",encoding="utf-8");(a.output/"_ARTIFACT_COMPLETE.json").write_text(json.dumps({"complete":True,"authoritative":"compare.json","sha256":sha(cp),"parquet_sha256":sha(par)},indent=2)+"\n",encoding="utf-8");print(json.dumps({"output":str(a.output),"feature":a.feature,"results":results,"anchors":anchors,"judgment":data["judgment"],"audit":audit},indent=2))
if __name__=="__main__":main()
