from __future__ import annotations
import argparse,sys
from datetime import datetime,timezone
from pathlib import Path
import duckdb,numpy as np,pandas as pd
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:sys.path.insert(0,str(ROOT))
from scripts.tradex_early_signal_first_detect_v1 import _metrics,_pf
from scripts.tradex_shallow_high_zone_universe_repair_v1 import attach_gap_outcomes,no_reentry_sessions,_sha,_write
from scripts import tradex_sell_support_break_breadth_current_contract_v1 as sellmod
AXIS_ID='tradex_two_sided_portfolio_union_v1';OUT=Path(r'G:\Tradex\tradex_two_sided_portfolio_union_v1');PERIODS={'train':(20240101,20241231),'validation':(20250101,20251231),'shadow':(20260101,20261231)}
def portfolio_metrics(buy:pd.DataFrame,sell:pd.DataFrame,start:int,end:int)->tuple[dict,dict]:
 bd=buy[buy.signal_ymd.between(start,end)].groupby('signal_ymd').trade_return_h10.mean().rename('buy');sd=sell[sell.signal_ymd.between(start,end)].groupby('signal_ymd').trade_return_h10.mean().rename('sell');x=pd.concat([bd,sd],axis=1);both=x.buy.notna()&x.sell.notna();x['buy_weight']=np.where(both,.5,np.where(x.buy.notna(),1.,0.));x['sell_weight']=np.where(both,.5,np.where(x.sell.notna(),1.,0.));x['buy_contribution']=x.buy.fillna(0)*x.buy_weight;x['sell_contribution']=x.sell.fillna(0)*x.sell_weight;x['portfolio_return']=x.buy_contribution+x.sell_contribution
 r=x.portfolio_return;curve=(1+r).cumprod();dd=curve/curve.cummax()-1;cut=r.quantile(.1);weeks=pd.to_datetime(r.index.astype(str),format='%Y%m%d').strftime('%G-W%V').nunique();tr=pd.concat([buy[buy.signal_ymd.between(start,end)].trade_return_h10,sell[sell.signal_ymd.between(start,end)].trade_return_h10]);m={'signal_days':len(r),'calendar_profit_factor':_pf(r),'calendar_expectancy':float(r.mean()) if len(r) else None,'cvar10':float(r[r<=cut].mean()) if len(r) else None,'max_drawdown':float(dd.min()) if len(r) else None,'trade_count':len(tr),'trade_profit_factor':_pf(tr),'trade_expectancy':float(tr.mean()) if len(tr) else None,'signals_per_week':float(len(r)/weeks) if weeks else 0.,'buy_contribution_sum':float(x.buy_contribution.sum()),'sell_contribution_sum':float(x.sell_contribution.sum()),'both_side_days':int(both.sum()),'buy_sell_common_day_correlation':float(x.loc[both,['buy','sell']].corr().iloc[0,1]) if both.sum()>=2 else None};return m,x.reset_index()
def generate(db:Path,out:Path)->Path:
 f,b,sellr,cov=sellmod.load(db);base=sellmod.features(f,b);ss=sellmod.outcomes(sellmod.score_stage(base,1),b);ss=ss[ss.signal_ymd>=20240101];cal=sorted(ss.signal_ymd.unique());sell=sellmod.select(ss,True,cal,'rank')
 with duckdb.connect(str(db),read_only=True) as q:buyr=q.execute("select dt signal_ymd,cast(code as varchar) code,rank from ranking_appearance_daily where ranking_logic_version='ranking:trade:top50:v1' and dir='up' and rank<=50 and dt between 20240101 and 20261231 order by dt,rank,code").fetchdf()
 outs=attach_gap_outcomes(b[['signal_ymd','code']],b)[['signal_ymd','code','trade_return_h10','exit_day_h10','target_before_stop20','realized_mover20']];buyraw=buyr[buyr['rank'].le(10)].merge(outs,on=['signal_ymd','code'],how='left',validate='one_to_one');buy=no_reentry_sessions(buyraw[buyraw.trade_return_h10.notna()],cal,'rank');latest=int(f.signal_ymd.max());periods={**PERIODS,'shadow':(20260101,latest)};metrics={};daily=[];gates={}
 for split,(a,z) in periods.items():
  pm,x=portfolio_metrics(buy,sell,a,z);x['split']=split;daily.append(x);days=sum(a<=d<=z for d in cal);bm=_metrics(buy[buy.signal_ymd.between(a,z)],days);sm=_metrics(sell[sell.signal_ymd.between(a,z)],days);metrics[split]={'portfolio_union':pm,'buy_only_meemee_top10':bm,'sell_only_support_break_wait1':sm};gates[split]={'portfolio_pf_ge_1_30':(pm['calendar_profit_factor'] or 0)>=1.3,'portfolio_expectancy_positive':(pm['calendar_expectancy'] or 0)>0,'cvar_non_degrade_vs_buy':pm['cvar10'] is not None and bm['cvar10'] is not None and pm['cvar10']>=bm['cvar10'],'dd_non_degrade_vs_buy':pm['max_drawdown'] is not None and bm['max_drawdown'] is not None and pm['max_drawdown']>=bm['max_drawdown'],'frequency_ge_1_week':pm['signals_per_week']>=1}
 keep=all(all(gates[x].values()) for x in ('validation','shadow'));root=out/f"{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}-{AXIS_ID}";root.mkdir(parents=True,exist_ok=False);buyr.to_parquet(root/'all_meemee_buy_ranks.parquet',index=False);ss.to_parquet(root/'all_support_break_sell_scores.parquet',index=False);buy.to_parquet(root/'buy_top10_ledger.parquet',index=False);sell.to_parquet(root/'sell_wait1_ledger.parquet',index=False);pd.concat(daily,ignore_index=True).to_parquet(root/'portfolio_daily_returns.parquet',index=False)
 train=metrics['train']['portfolio_union'];reason='validation_shadow_gate_pass' if keep else ('train_negative_but_validation_shadow_evaluated_without_weight_tuning' if (train['calendar_expectancy'] or 0)<=0 else 'validation_or_shadow_gate_failed');payload={'schema_version':AXIS_ID+'.compare.v1','artifact_role':'authoritative','research_phase':'effectiveness_judgment','fixed_evaluation_conditions':{'single_axis':'fixed two-sided portfolio union','buy_lane':'MeeMee BUY daily top10; next-open TP8/SL5/H10/10bp gap-through; same-code open reentry prohibited','sell_lane':'support-break breadth current contract wait1 full-stage eligible; current next-open TP8/SL5/H10/10bp gap-through; same-code open reentry prohibited','portfolio':'within-side daily equal weight; both sides active BUY/SELL 50/50; one side active 100%','variants':'none','splits':'2024 train/2025 validation/2026 untouched shadow','benchmarks':['BUY-only MeeMee calendar','SELL-only support-break wait1'],'weight_tuning':False,'survivorship_filter':False,'fallback':False},'source_artifacts':[{'path':str(db),'sha256':_sha(db)}],'source_coverage':cov,'metrics':metrics,'adoption_gates':gates,'rank_coverage':{'buy_days':int(buyr.signal_ymd.nunique()),'buy_min_ranked':int(buyr.groupby('signal_ymd').size().min()),'sell_days':int(ss.signal_ymd.nunique()),'sell_min_ranked':int(ss.groupby('signal_ymd').size().min()),'all_days_ranked':bool(buyr.groupby('signal_ymd').size().gt(0).all() and ss.groupby('signal_ymd').size().gt(0).all())},'decision':{'candidate_local_decision':'keep' if keep else 'drop','authoritative_rollup_decision':'review_only','reason_type':reason},'shadow_tuning_used':False,'silent_fallback_used':False,'runtime_db_write':False,'production_ranking_changed':False,'meemee_changed':False};p=root/'compare.json';_write(p,payload);_write(root/'_ARTIFACT_COMPLETE.json',{'complete':True,'compare':str(p)});return p
def main():
 p=argparse.ArgumentParser();p.add_argument('--db',type=Path,required=True);p.add_argument('--out',type=Path,default=OUT);a=p.parse_args();print(generate(a.db,a.out))
if __name__=='__main__':main()
