"""Walk-forward base score using only monthly environment on the core candidate union."""
from __future__ import annotations
import argparse,hashlib,json,math
from pathlib import Path
import pandas as pd

TEST_YEARS=(2021,2022,2023,2024,2025)
ENVIRONMENTS=("UPTREND","POST_BOX_BREAKOUT_CONSOLIDATION","BOX","DOWNTREND","AMBIGUOUS")
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rates(x):return {"n":int(len(x)),"codes":int(x.code.nunique()),"down_first":None if x.empty else float(x.outcome.eq("down_first").mean()),"rebound_first":None if x.empty else float(x.outcome.eq("rebound_first").mean()),"neutral":None if x.empty else float(x.outcome.str.startswith("neutral").mean())}
def main():
 p=argparse.ArgumentParser();p.add_argument("--candidate-union",type=Path,required=True);p.add_argument("--include-source-family-context",action="store_true");p.add_argument("--lookback-years",type=int);p.add_argument("--output",type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=False);x=pd.read_parquet(a.candidate_union);x["score_context_key"]=x.base_regime.fillna("MISSING").astype(str)+("|"+x.source_families.astype(str) if a.include_source_family_context else "");x["score_environment"]=0;x["score_log_odds_environment"]=0.0
 tables={};results={};score_rows=[]
 for year in TEST_YEARS:
  train=x[(x.year<year)&x.outcome.isin(["down_first","rebound_first"])];train=train if not a.lookback_years else train[train.year>=year-a.lookback_years];table={}
  contexts=sorted(train.score_context_key.dropna().unique()) if a.include_source_family_context else list(ENVIRONMENTS)
  for env in contexts:
   z=train[train.score_context_key.eq(env)];dn=int(z.outcome.eq("down_first").sum());rb=int(z.outcome.eq("rebound_first").sum());log_odds=math.log((dn+5)/(rb+5));point=1 if log_odds>0 else -1 if log_odds<0 else 0;table[env]={"train_n":int(len(z)),"down":dn,"rebound":rb,"smoothed_log_odds":log_odds,"point":point}
  tables[str(year)]=table;test=x[x.year.eq(year)].copy();test["score_environment"]=test.score_context_key.map({k:v["point"] for k,v in table.items()}).fillna(0).astype(int);test["score_log_odds_environment"]=test.score_context_key.map({k:v["smoothed_log_odds"] for k,v in table.items()}).fillna(0.0);selected=test[test.score_environment>0]
  results[str(year)]={"baseline":rates(test),"selected_positive_environment_score":rates(selected),"selected_environments":sorted(selected.base_regime.dropna().unique().tolist())};score_rows.append(test)
 scored=pd.concat(score_rows,ignore_index=True);direction=all(results[str(y)]["selected_positive_environment_score"]["n"]>0 and results[str(y)]["selected_positive_environment_score"]["down_first"]>results[str(y)]["selected_positive_environment_score"]["rebound_first"] for y in TEST_YEARS);breadth=all(results[str(y)]["selected_positive_environment_score"]["n"]>=30 for y in TEST_YEARS)
 anchors=[]
 for code,ymd,label in [("9107",20241122,"CORE"),("4755",20251114,"CORE"),("6857",20240903,"CORE"),("6532",20230626,"ADD")]:
  z=scored[(scored.code.astype(str).str.zfill(4)==code)&scored.ymd.eq(ymd)];anchors.append({"code":code,"ymd":ymd,"label":label,"present":not z.empty,"environment":None if z.empty else z.base_regime.iloc[0],"environment_point":None if z.empty else int(z.score_environment.iloc[0]),"selected":False if z.empty else bool(z.score_environment.iloc[0]>0)})
 data={"schema_version":"tradex_core_environment_walkforward_score_v1.compare.v1","artifact_role":"authoritative","axis":"monthly environment plus source-family base point" if a.include_source_family_context else "monthly environment base point","fixed_conditions":{"candidate_union":"unchanged","context":"monthly environment plus source family" if a.include_source_family_context else "monthly environment","train":"decisive outcomes strictly before test year","lookback_years":"all prior" if not a.lookback_years else a.lookback_years,"test_years":list(TEST_YEARS),"smoothing":"down+5 versus rebound+5","points":"+1 if smoothed down>rebound; -1 if lower; 0 tie or missing","selection":"context point > 0","minimum_each_year":30,"threshold_sweep":False},"year_score_tables":tables,"year_results":results,"human_anchor_scores":anchors,"observed_branching":{"candidate_rows":int(len(scored)),"selected_rows":int(scored.score_environment.gt(0).sum()),"changed_rank_count":max(len(v) for v in tables.values()),"selection_divergence_reason":"prior-window context hit balance contributes to the base point"},"judgment":{"decision":"keep_base_score" if direction and breadth else "hold" if direction else "drop_as_selector_keep_infrastructure","direction_pass_all_years":direction,"breadth_pass":breadth,"reason":"context base point alone passes all gates" if direction and breadth else "context-only point is insufficient; retain scoring infrastructure"},"not_changed":["candidate branches","daily features","human episode actions","add logic","profit logic","MeeMee","ranking","runtime DB"]}
 cp=a.output/"compare.json";cp.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");par=a.output/"walkforward_environment_scores.parquet";scored.to_parquet(par,index=False);audit={"scored_rows":int(len(scored)),"duplicates":int(scored.duplicated(["code","ymd"]).sum()),"missing_environment":int(scored.base_regime.isna().sum()),"future_used_for_score":False,"review_only":True,"source_sha256":sha(a.candidate_union)};(a.output/"audit.json").write_text(json.dumps(audit,indent=2)+"\n",encoding="utf-8");(a.output/"_ARTIFACT_COMPLETE.json").write_text(json.dumps({"complete":True,"authoritative":"compare.json","sha256":sha(cp),"parquet_sha256":sha(par)},indent=2)+"\n",encoding="utf-8");print(json.dumps({"output":str(a.output),"results":results,"anchors":anchors,"judgment":data["judgment"],"audit":audit},indent=2))
if __name__=="__main__":main()
