"""Reveal a frozen board and validate the lower-half local-box disagreement veto."""
import argparse,hashlib,json
from pathlib import Path
import duckdb,pandas as pd

SELL_ACTIONS={'PROBE','CORE','ADD','REENTRY_PROBE'};THRESHOLD=.5
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def evaluate(g,ymd):
 hit=g.index[g.ymd.eq(ymd)]
 if len(hit)!=1 or int(hit[0])+5>=len(g):return {'status':'censored'}
 w=g.iloc[int(hit[0])+1:int(hit[0])+6];entry=float(w.iloc[0].o);target=entry*.97;stop=entry*1.03;price=float(w.iloc[-1].c);out='N';reason='horizon_close';ey=int(w.iloc[-1].ymd)
 for r in w.itertuples():
  if r.o>=stop:price,out,reason,ey=float(r.o),'R','gap_stop',int(r.ymd);break
  if r.o<=target:price,out,reason,ey=float(r.o),'D','gap_target',int(r.ymd);break
  if r.h>=stop and r.l<=target:price,out,reason,ey=stop,'R','same_bar_stop_first',int(r.ymd);break
  if r.h>=stop:price,out,reason,ey=stop,'R','stop',int(r.ymd);break
  if r.l<=target:price,out,reason,ey=target,'D','target',int(r.ymd);break
 return {'status':'complete','entry_ymd':int(w.iloc[0].ymd),'exit_ymd':ey,'outcome_fixed3':out,'return_fixed3_pct':100*(entry-price)/entry,'return_h5_close_pct':100*(entry-float(w.iloc[-1].c))/entry,'exit_reason_fixed3':reason}
def stats(f):
 x=f[f.status.eq('complete')].sort_values(['exit_ymd','code']);v=x.return_fixed3_pct;gain=v[v>0].sum();loss=-v[v<0].sum();eq=v.cumsum();dd=eq-eq.cummax() if len(eq) else pd.Series(dtype=float);run=maxrun=0
 for z in v:run=run+1 if z<0 else 0;maxrun=max(maxrun,run)
 conc=0
 for day in sorted(set(x.entry_ymd).union(x.exit_ymd)) if len(x) else []:conc=max(conc,int(((x.entry_ymd<=day)&(x.exit_ymd>=day)).sum()))
 return {'n':len(f),'completed':len(x),'D':int(x.outcome_fixed3.eq('D').sum()),'R':int(x.outcome_fixed3.eq('R').sum()),'N':int(x.outcome_fixed3.eq('N').sum()),'D_rate':float(x.outcome_fixed3.eq('D').mean()) if len(x) else None,'R_rate':float(x.outcome_fixed3.eq('R').mean()) if len(x) else None,'mean_fixed3_pct':float(v.mean()) if len(v) else None,'mean_h5_close_pct':float(x.return_h5_close_pct.mean()) if len(x) else None,'profit_factor':None if loss==0 else float(gain/loss),'max_loss_pct':float(v.min()) if len(v) else None,'sum_return_units_pct':float(v.sum()),'max_drawdown_units_pct':0 if dd.empty else float(dd.min()),'max_loss_streak':maxrun,'max_concurrent':conc}
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--human-freeze',type=Path,required=True);ap.add_argument('--sealed',type=Path,required=True);ap.add_argument('--board',type=Path,required=True);ap.add_argument('--db',type=Path,required=True);ap.add_argument('--output',type=Path,required=True);a=ap.parse_args();a.output.mkdir(parents=True,exist_ok=False)
 human=pd.read_parquet(a.human_freeze/'human_direction_frozen.parquet');sealed=pd.read_parquet(a.sealed/'machine_annotation_sealed.parquet');board=pd.read_parquet(a.board);data=human.merge(sealed,on=['case_id','code','ymd'],validate='one_to_one').merge(board[['case_id','current_local_box_position']],on='case_id',validate='one_to_one');codes=data.code.astype(str).str.zfill(4).unique().tolist();con=duckdb.connect(str(a.db),read_only=True);p=con.execute("select code,strftime(to_timestamp(date),'%Y%m%d')::integer ymd,o,h,l,c from daily_bars where code in (select unnest(?)) order by code,date",[codes]).fetchdf();p.code=p.code.astype(str).str.zfill(4);hist={c:g.reset_index(drop=True) for c,g in p.groupby('code')};rows=[]
 for r in data.itertuples():rows.append({**r._asdict(),**evaluate(hist[r.code],int(r.ymd))})
 d=pd.DataFrame(rows);d['model_direction']=d.model_action.map(lambda x:'SELL' if x in SELL_ACTIONS else 'NO_SELL');d['localbox_veto']=d.human_direction.eq('SELL')&d.model_direction.eq('NO_SELL')&d.current_local_box_position.le(THRESHOLD);d['human_gate_sell']=d.human_direction.eq('SELL')&~d.localbox_veto;d['model_sell']=d.model_direction.eq('SELL');d['complement_union_sell']=d.human_gate_sell|d.model_sell
 groups={'human_alone':d[d.human_direction.eq('SELL')],'human_with_localbox_gate':d[d.human_gate_sell],'model_alone':d[d.model_sell],'complement_union':d[d.complement_union_sell],'human_sell_model_avoid':d[d.human_direction.eq('SELL')&d.model_direction.eq('NO_SELL')],'human_nosell_model_sell':d[d.human_direction.eq('NO_SELL')&d.model_direction.eq('SELL')]};metrics={k:stats(v) for k,v in groups.items()};hb=metrics['human_alone'];hg=metrics['human_with_localbox_gate'];dret=None if hb['D']==0 else hg['D']/hb['D'];keep=hg['R_rate']<hb['R_rate'] and hg['max_loss_pct']>hb['max_loss_pct'] and dret>=.7 and metrics['model_alone']['mean_fixed3_pct']>0
 lp=a.output/'localbox_complement_outcome_ledger.parquet';d.to_parquet(lp,index=False);env=d.monthly_state.fillna('UNKNOWN_OR_BREAKDOWN');result={'schema_version':'tradex_blind_localbox_complement_rollup_v1.compare.v1','artifact_role':'authoritative_unused_human_model_complement_validation','review_only':True,'fixed_conditions':{'human_frozen_before_reveal':True,'veto_scope':'human SELL and model AVOID only','veto':'PIT current_local_box_position <= 0.5','execution':'next_session_open','horizon_sessions':5,'barriers':'short target -3%, stop +3%, same-bar stop-first','costs':'ignored','weekly_inputs':[]},'authoritative_results':metrics,'observed_branching':{'human_candidates':hb['n'],'human_gate_candidates':hg['n'],'vetoed':int(d.localbox_veto.sum()),'vetoed_outcomes':{str(k):int(v) for k,v in d[d.localbox_veto].outcome_fixed3.value_counts().items()},'D_retention':dret,'R_removed':hb['R']-hg['R']},'by_model_action':{str(k):stats(v) for k,v in d[d.model_sell].groupby('model_action')},'by_environment':{str(k):stats(v) for k,v in d.groupby(env)},'direction_pairs':{str(k):stats(v) for k,v in d.groupby(d.model_direction+'__'+d.human_direction)},'judgment':{'candidate_local_decision':'keep' if keep else 'drop','authoritative_rollup_decision':'keep_review_only' if keep else 'drop','keep_conditions':{'user_R_rate_strictly_lower':hg['R_rate']<hb['R_rate'],'user_max_loss_strictly_better':hg['max_loss_pct']>hb['max_loss_pct'],'user_D_retention_ge_0_70':dret>=.7,'model_positive_expectancy':metrics['model_alone']['mean_fixed3_pct']>0}},'not_changed':['MeeMee','ranking','runtime DB','production trading logic']};cp=a.output/'compare.json';cp.write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');audit={'human_freeze_sha256':sha(a.human_freeze/'compare.json'),'sealed_sha256':sha(a.sealed/'machine_annotation_sealed.parquet'),'board_sha256':sha(a.board),'db_path':str(a.db.resolve()),'db_read_only':True,'rows':len(d),'completed':int(d.status.eq('complete').sum()),'weekly_columns_used':[],'ledger_sha256':sha(lp)};(a.output/'audit.json').write_text(json.dumps(audit,indent=2)+'\n',encoding='utf-8');(a.output/'_ARTIFACT_COMPLETE.json').write_text(json.dumps({'complete':True,'authoritative':'compare.json','sha256':sha(cp)},indent=2)+'\n',encoding='utf-8');print(json.dumps({'output':str(a.output),'results':metrics,'branching':result['observed_branching'],'judgment':result['judgment']},ensure_ascii=False,indent=2))
if __name__=='__main__':main()
