"""Evaluate lower-half local-box position as a disagreement veto."""
import argparse,hashlib,json
from pathlib import Path
import pandas as pd

THRESHOLD=.5
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def stats(f):
 x=f[f.status.eq('complete')];v=x.return_fixed3_pct;gain=v[v>0].sum();loss=-v[v<0].sum()
 return {'n':len(f),'D':int(x.outcome_fixed3.eq('D').sum()),'R':int(x.outcome_fixed3.eq('R').sum()),'N':int(x.outcome_fixed3.eq('N').sum()),'D_rate':float(x.outcome_fixed3.eq('D').mean()) if len(x) else None,'R_rate':float(x.outcome_fixed3.eq('R').mean()) if len(x) else None,'mean_fixed3_pct':float(v.mean()) if len(v) else None,'profit_factor':None if loss==0 else float(gain/loss),'max_loss_pct':float(v.min()) if len(v) else None}
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--board',type=Path,required=True);ap.add_argument('--outcomes',type=Path,required=True);ap.add_argument('--output',type=Path,required=True);a=ap.parse_args();a.output.mkdir(parents=True,exist_ok=False)
 board=pd.read_parquet(a.board);out=pd.read_parquet(a.outcomes);data=out.merge(board[['case_id','current_local_box_position']],on='case_id',validate='one_to_one');data['lower_half_local_box']=data.current_local_box_position.le(THRESHOLD)
 lane=data[data.human_direction.eq('SELL')&data.model_direction.eq('NO_SELL')];gate=lane[~lane.lower_half_local_box];base=stats(lane);chall=stats(gate);dret=None if base['D']==0 else chall['D']/base['D'];keep=chall['R_rate']<base['R_rate'] and chall['max_loss_pct']>base['max_loss_pct'] and dret>=.7
 lp=a.output/'local_box_axis_ledger.parquet';data.to_parquet(lp,index=False);result={'schema_version':'tradex_human_sell_model_avoid_local_box_axis_v1.compare.v1','artifact_role':'authoritative_single_axis_discovery','review_only':True,'fixed_conditions':{'scope':'human SELL and model AVOID only','axis':'PIT current_local_box_position','veto':'position <= 0.5 (local box lower half)','execution':'next_session_open','horizon_sessions':5,'weekly_inputs':[],'costs':'ignored','clean_oos':False},'baseline':base,'challenger':chall,'observed_branching':{'removed':len(lane)-len(gate),'removed_outcomes':{str(k):int(v) for k,v in lane[lane.lower_half_local_box].outcome_fixed3.value_counts().items()},'D_retention':dret,'R_removed':base['R']-chall['R'],'selection_divergence_reason':'only human SELL/model AVOID disagreements in the lower half of the PIT local box are vetoed'},'judgment':{'candidate_local_decision':'keep_discovery_challenger' if keep else 'drop','authoritative_rollup_decision':'hold_pending_unused_human_validation' if keep else 'drop','keep_conditions':{'R_rate_strictly_lower':chall['R_rate']<base['R_rate'],'max_loss_strictly_better':chall['max_loss_pct']>base['max_loss_pct'],'D_retention_ge_0_70':dret>=.7}},'not_changed':['other human SELL','model SELL','MeeMee','ranking','runtime DB','production trading logic']};cp=a.output/'compare.json';cp.write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');audit={'board_sha256':sha(a.board),'outcomes_sha256':sha(a.outcomes),'rows':len(data),'lane_rows':len(lane),'missing_local_box_position_in_lane':int(lane.current_local_box_position.isna().sum()),'weekly_columns_used':[],'future_selection_columns_used':[],'ledger_sha256':sha(lp)};(a.output/'audit.json').write_text(json.dumps(audit,indent=2)+'\n',encoding='utf-8');(a.output/'_ARTIFACT_COMPLETE.json').write_text(json.dumps({'complete':True,'authoritative':'compare.json','sha256':sha(cp)},indent=2)+'\n',encoding='utf-8');print(json.dumps({'output':str(a.output),'baseline':base,'challenger':chall,'branching':result['observed_branching'],'judgment':result['judgment']},ensure_ascii=False,indent=2))
if __name__=='__main__':main()
