from __future__ import annotations
import argparse,json,sys
from datetime import datetime,timezone
from pathlib import Path
import duckdb,numpy as np,pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeRegressor,_tree
from tradex_long_trend_pullback_portfolio_v1 import simulate,portfolio_summary,COST
from tradex_long_gap_guard_protective_stop_v1 import metrics

FEATURES=['market_median_ret20','market_median_ret60','market_above_ma60_rate','market_ma60_slope20_median','family_bottom_reversal']
def rules(tree):
 t=tree.tree_;out={}
 def walk(n,c):
  if t.feature[n]==_tree.TREE_UNDEFINED:out[int(n)]=c;return
  f=FEATURES[t.feature[n]];q=float(t.threshold[n]);walk(t.children_left[n],c+[f'{f} <= {q:.8g}']);walk(t.children_right[n],c+[f'{f} > {q:.8g}'])
 walk(0,[]);return out
def main():
 p=argparse.ArgumentParser();p.add_argument('--output',required=True);p.add_argument('--pullback',default=r'G:\Tradex\long_selector_10y_research_v1\20260626T054716Z-long_selector_10y_research_v1\strict_trend_pullback_top3_events.csv');p.add_argument('--reversal',default=r'G:\Tradex\long_selector_10y_research_v1\20260626T054716Z-long_selector_10y_research_v1\strict_bottom_reversal_top3_events.csv');a=p.parse_args();out=Path(a.output);out.mkdir(parents=True,exist_ok=False);sys.path[:0]=[str(Path.cwd()),str(Path.cwd()/'app')]
 from backend.services.codex_bridge_service import get_runtime_stock_db_status
 runtime=get_runtime_stock_db_status();frames=[]
 for family,path in [('押し目',a.pullback),('底反転',a.reversal)]:
  x=pd.read_csv(path,dtype={'code':str});x=x[['code','date','rank']+FEATURES[:-1]].copy();x['family']=family;frames.append(x)
 src=pd.concat(frames,ignore_index=True);src['event_id']=range(len(src));src['family_bottom_reversal']=(src.family=='底反転').astype(float)
 with duckdb.connect(runtime['selected_runtime_db_path'],read_only=True) as c:
  c.register('src',src);e=c.execute("""select * exclude(next_rn) from (select s.*,b.date entry_date,b.o entry_price,row_number() over(partition by s.event_id order by b.date) next_rn from src s join daily_bars b on b.code=s.code and b.date>s.date) where next_rn=1""").fetchdf();c.register('events',e)
  events=c.execute("""select * exclude(exit_rn) from (select e.*,i.market_code,b.date exit_date,b.c exit_price,row_number() over(partition by e.event_id order by b.date) exit_rn from events e join industry_master i using(code) join daily_bars b on b.code=e.code and b.date>=e.entry_date where i.market_code in ('プライム（内国株式）','スタンダード（内国株式）','グロース（内国株式）')) where exit_rn=20""").fetchdf()
 events['signal_dt']=pd.to_datetime(events.date,unit='s');events['year']=events.signal_dt.dt.year;events['raw_return_pct']=100*(events.exit_price/events.entry_price-1)-COST;dev=events[events.year.between(2016,2023)];imp=SimpleImputer(strategy='median');tree=DecisionTreeRegressor(max_depth=3,min_samples_leaf=150,random_state=20260720);tree.fit(imp.fit_transform(dev[FEATURES]),dev.raw_return_pct);events['leaf']=tree.apply(imp.transform(events[FEATURES])).astype(int);path=rules(tree);leaves=[];eligible=[]
 for leaf,g in events.groupby('leaf'):
  d=g[g.year.between(2016,2023)].copy();d['realized_ret']=d.raw_return_pct;v=g[g.year.between(2024,2025)].copy();v['realized_ret']=v.raw_return_pct;vy={str(y):metrics(v[v.year.eq(y)]) for y in [2024,2025]};row={'leaf':int(leaf),'rule':path[int(leaf)],'distinct_features':len({x.split()[0] for x in path[int(leaf)]}),'development':metrics(d),'validation_2024_2025':metrics(v),'validation_years':vy,'family_mix_development':d.family.value_counts().to_dict(),'family_mix_validation':v.family.value_counts().to_dict()};leaves.append(row)
  if row['distinct_features']>=2 and row['development']['n']>=150 and row['development']['mean_return_pct']>0 and row['development']['win_rate']>=.50 and row['validation_2024_2025']['n']>=40 and row['validation_2024_2025']['mean_return_pct']>0 and row['validation_2024_2025']['win_rate']>=.50 and all((m['mean_return_pct'] or -99)>0 for m in vy.values() if m['n']>0):eligible.append(int(leaf))
 allowed=events[events.leaf.isin(eligible)].copy();allowed['rank']=allowed['rank'].astype(float)+allowed.family.map({'底反転':0.0,'押し目':.1});portfolio=simulate(allowed,5);portfolio['year']=pd.to_datetime(portfolio.date,unit='s').dt.year;dpf=portfolio[portfolio.year.between(2016,2023)];vpf=portfolio[portfolio.year.between(2024,2025)];tpf=portfolio[portfolio.year.eq(2026)];dm=portfolio_summary(dpf);vm=portfolio_summary(vpf);tm=portfolio_summary(tpf)
 prechecks={'eligible_regime_leaves_without_2026':bool(eligible),'development_trades_at_least_250':dm['trades']>=250,'development_mean_positive':dm['raw_trade_metrics']['mean_return_pct'] is not None and dm['raw_trade_metrics']['mean_return_pct']>0,'development_win_at_least_50pct':dm['raw_trade_metrics']['win_rate'] is not None and dm['raw_trade_metrics']['win_rate']>=.50,'development_capital_loss5_at_most_3pct':dm['capital_contribution_metrics']['severe_loss5_rate'] is not None and dm['capital_contribution_metrics']['severe_loss5_rate']<=.03,'development_months_majority_positive':dm['positive_month_rate'] is not None and dm['positive_month_rate']>.50,'validation_mean_positive':vm['raw_trade_metrics']['mean_return_pct'] is not None and vm['raw_trade_metrics']['mean_return_pct']>0,'validation_win_at_least_50pct':vm['raw_trade_metrics']['win_rate'] is not None and vm['raw_trade_metrics']['win_rate']>=.50,'validation_capital_loss5_at_most_3pct':vm['capital_contribution_metrics']['severe_loss5_rate'] is not None and vm['capital_contribution_metrics']['severe_loss5_rate']<=.03,'validation_months_majority_positive':vm['positive_month_rate'] is not None and vm['positive_month_rate']>.50,'validation_profit_not_concentrated':vm['capital_contribution_metrics']['top3_positive_profit_share'] is not None and vm['capital_contribution_metrics']['top3_positive_profit_share']<=.35}
 testchecks={'pretest_passed':all(prechecks.values()),'test_n250_or_full_audit':all(prechecks.values()),'test_raw_mean_positive':tm['raw_trade_metrics']['mean_return_pct'] is not None and tm['raw_trade_metrics']['mean_return_pct']>0,'test_win_at_least_50pct':tm['raw_trade_metrics']['win_rate'] is not None and tm['raw_trade_metrics']['win_rate']>=.50,'test_capital_loss5_at_most_3pct':tm['capital_contribution_metrics']['severe_loss5_rate'] is not None and tm['capital_contribution_metrics']['severe_loss5_rate']<=.03,'test_months_majority_positive':tm['positive_month_rate'] is not None and tm['positive_month_rate']>.50,'test_profit_not_concentrated':tm['capital_contribution_metrics']['top3_positive_profit_share'] is not None and tm['capital_contribution_metrics']['top3_positive_profit_share']<=.35,'test_total_return_positive':tm['total_return_pct']>0};decision='hold_for_baseline_and_mark_to_market_gate' if all(testchecks.values()) else 'drop'
 payload={'schema_version':'tradex_long_family_regime_router_v1.compare.v1','artifact_role':'authoritative','generated_at':datetime.now(timezone.utc).isoformat(),'runtime':runtime,'fixed_evaluation_conditions':{'sources':{'押し目':a.pullback,'底反転':a.reversal},'ordinary_mature_events':len(events),'universe':'ordinary domestic stocks only: Prime, Standard, Growth','entry':'next session open','exit':'session-20 close','round_trip_cost_pct':COST,'portfolio':'max 5 equal slots, no same-code overlap','axis_changed':'market-regime by family router only','features':FEATURES,'tree':{'max_depth':3,'min_samples_leaf':150,'random_state':20260720},'development':'2016-2023','validation':'2024-2025','full_audit_test':'2026 matured events','production_changed':False},'authoritative_result':{'leaves':leaves,'eligible_without_2026':eligible,'development_portfolio':dm,'validation_portfolio':vm,'test_2026':tm,'test_family_mix':tpf.family.value_counts().to_dict() if len(tpf) else {},'prechecks':prechecks,'checks':testchecks},'observed_branching':{'changed_top5_members_count':None,'changed_top10_members_count':None,'changed_rank_count':tm['trades'],'selection_divergence_reason':'family-specific market regime leaves gate fixed capital slots'},'judgment':{'candidate_local_decision':decision,'authoritative_rollup_decision':decision,'reason_type':'family_regime_router_portfolio_gate'},'remaining_risks':['same-condition baseline and mark-to-market drawdown pending only if test passes']}
 if len(tpf):tpf.to_parquet(out/'test_2026_portfolio_ledger.parquet',index=False)
 (out/'compare.json').write_text(json.dumps(payload,ensure_ascii=False,indent=2,default=str),encoding='utf-8');(out/'_ARTIFACT_COMPLETE.json').write_text(json.dumps({'complete':True,'authoritative':'compare.json'}),encoding='utf-8');print(json.dumps({'eligible':eligible,'development':dm,'validation':vm,'test':tm,'test_family_mix':payload['authoritative_result']['test_family_mix'],'prechecks':prechecks,'checks':testchecks,'decision':decision},ensure_ascii=False))
if __name__=='__main__':main()
