"""Build a deduplicated review-only union of observable CORE_CLOSE candidate branches."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
import pandas as pd

YEARS=tuple(range(2019,2026))
FEATURES=["c","atr14","ma60","ma100","ma200","support20","cross_ma20","body_ratio","upper_wick_ratio","lower_wick_ratio","close_pos","ret3","ret5","pre_ret10","pos20","range20_pct","bear_count5","bear_body5_atr","upper_supply_count5","lower_rejection_count5","low_close_count3","dist_ma7_atr","dist_ma20_atr","dist_ma60_atr","ma7_slope5_atr","ma20_slope5_atr","ma60_slope5_atr","volume_ratio20","support_break_depth_atr","oversold_risk","weekly_lower_high","weekly_upper_wick_ratio","weekly_close_pos","monthly_high_failure","market_breadth_ma20","market_breadth_ma60","market_advancers_ratio","market_mean_ret1"]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--sequence-ledger",type=Path,required=True);p.add_argument("--try-fail-events",type=Path,required=True);p.add_argument("--support-break-events",type=Path,required=True);p.add_argument("--ma200-events",type=Path,required=True);p.add_argument("--features",type=Path,required=True);p.add_argument("--monthly-ledger",type=Path,required=True);p.add_argument("--output",type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=False)
 seq=pd.read_parquet(a.sequence_ledger);weak=seq[seq.gd_ymd.notna()&seq.ma20_rebreak_ymd.notna()&(seq.ma20_rebreak_ymd>seq.gd_ymd)&seq.weak_rebound&(seq.max_consecutive_closes_above_ma7<7)].copy();weak["ymd"]=weak.ma20_rebreak_ymd.astype(int);weak["outcome"]=weak.ma20_rebreak_outcome_fixed3_h5;weak["source_family"]="WEAK_REBOUND_MA20_REBREAK_CORE";weak=weak[["code","ymd","outcome","source_family"]]
 tf=pd.read_parquet(a.try_fail_events)[["code","ymd","outcome"]].assign(source_family="UPTREND_CEILING_TRY_FAIL_CORE")
 sb=pd.read_parquet(a.support_break_events)[["code","ymd","outcome"]].assign(source_family="POSTBOX_SUPPORT_BREAK_DIRECT_CORE")
 ma=pd.read_parquet(a.ma200_events);ma=ma[ma.core_ymd.notna()].copy();ma["ymd"]=ma.core_ymd.astype(int);ma["outcome"]=ma.core_outcome_fixed3_h5;ma["source_family"]="BOX_MA200_REJECTION_CORE";ma=ma[["code","ymd","outcome","source_family"]]
 raw=pd.concat([weak,tf,sb,ma],ignore_index=True);raw["code"]=raw.code.astype(str).str.zfill(4);raw["year"]=raw.ymd.astype(str).str[:4].astype(int);raw=raw[raw.year.isin(YEARS)].drop_duplicates(["code","ymd","source_family"])
 conflicts=raw.groupby(["code","ymd"]).outcome.nunique();outcome_conflicts=int((conflicts>1).sum())
 union=raw.groupby(["code","ymd","year"],as_index=False).agg(outcome=("outcome","first"),source_families=("source_family",lambda s:"|".join(sorted(set(s)))),source_family_count=("source_family","nunique"))
 f=pd.read_parquet(a.features,columns=["code","ymd"]+FEATURES);f["code"]=f.code.astype(str).str.zfill(4);union=union.merge(f,on=["code","ymd"],how="left",validate="one_to_one");union["long_ma_cluster_width_atr"]=(union[["ma60","ma100","ma200"]].max(axis=1)-union[["ma60","ma100","ma200"]].min(axis=1))/union.atr14;rooms=pd.DataFrame({level:(union.c-union[level])/union.atr14 for level in ["ma60","ma100","ma200","support20"]});union["nearest_downside_support_room_atr"]=rooms.where(rooms.ge(0)).min(axis=1);union["effective_month"]=pd.to_datetime(union.ymd.astype(str),format="%Y%m%d").dt.to_period("M").astype(str)
 m=pd.read_parquet(a.monthly_ledger);m["code"]=m.code.astype(str).str.zfill(4);m["effective_month"]=m.effective_month.astype(str);m=m[["code","effective_month","base_regime","post_box","box_reentry","breakout_age","box_pos","local_box_mature","local_box_top_touch_count","local_close_location","local_box_top_close_distance_atr"]];union=union.merge(m,on=["code","effective_month"],how="left",validate="many_to_one")
 counts={str(y):{"events":int((union.year==y).sum()),"down":int(((union.year==y)&union.outcome.eq("down_first")).sum()),"rebound":int(((union.year==y)&union.outcome.eq("rebound_first")).sum()),"neutral":int(((union.year==y)&union.outcome.str.startswith("neutral")).sum())} for y in YEARS}
 data={"schema_version":"tradex_core_candidate_union_v1.compare.v1","artifact_role":"authoritative_infrastructure","review_only":True,"candidate_contract":{"action":"CORE_CLOSE","families":["WEAK_REBOUND_MA20_REBREAK_CORE","UPTREND_CEILING_TRY_FAIL_CORE","POSTBOX_SUPPORT_BREAK_DIRECT_CORE","BOX_MA200_REJECTION_CORE"],"dedupe":"one code/date; preserve all source family tags","outcome":"exact fixed3 h5 inherited from source","years":list(YEARS)},"year_counts":counts,"observed_branching":{"raw_family_events":int(len(raw)),"union_events":int(len(union)),"multi_family_events":int(union.source_family_count.gt(1).sum()),"changed_rank_count":4,"selection_divergence_reason":"four independently observable core branches share one scoring surface"},"judgment":{"decision":"keep_infrastructure" if outcome_conflicts==0 else "drop","reason":"candidate union is ready for walk-forward scoring" if outcome_conflicts==0 else "same action date has conflicting inherited outcomes"},"not_changed":["source branch detectors","source outcomes","human episode agreement","action sizing","add logic","profit logic","MeeMee","ranking","runtime DB"]}
 cp=a.output/"compare.json";cp.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");par=a.output/"core_candidate_union.parquet";union.to_parquet(par,index=False);audit={"raw_rows":int(len(raw)),"union_rows":int(len(union)),"outcome_conflicts":outcome_conflicts,"duplicates":int(union.duplicated(["code","ymd"]).sum()),"missing_feature_rows":int(union[FEATURES].isna().all(axis=1).sum()),"missing_monthly_rows":int(union.base_regime.isna().sum()),"future_used_for_selection":False,"review_only":True,"source_sha256":{k:sha(v) for k,v in {"sequence":a.sequence_ledger,"try_fail":a.try_fail_events,"support_break":a.support_break_events,"ma200":a.ma200_events,"features":a.features,"monthly":a.monthly_ledger}.items()}};(a.output/"audit.json").write_text(json.dumps(audit,indent=2)+"\n",encoding="utf-8");(a.output/"_ARTIFACT_COMPLETE.json").write_text(json.dumps({"complete":True,"authoritative":"compare.json","sha256":sha(cp),"parquet_sha256":sha(par)},indent=2)+"\n",encoding="utf-8");print(json.dumps({"output":str(a.output),"counts":counts,"judgment":data["judgment"],"audit":audit},indent=2))
if __name__=="__main__":main()
