"""Roll up independent raw-trigger probe gate experiments."""
import argparse,hashlib,json
from pathlib import Path
def load(p):return json.loads(Path(p).read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument('--baseline',required=True);p.add_argument('--below7-gate',required=True);p.add_argument('--below7-outcome',required=True);p.add_argument('--support-gate',required=True);p.add_argument('--support-outcome',required=True);p.add_argument('--gu-gate',required=True);p.add_argument('--gu-outcome',required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=False)
 base=load(a.baseline);rows={}
 for name,gp,op in [('below7',a.below7_gate,a.below7_outcome),('support020',a.support_gate,a.support_outcome),('gu',a.gu_gate,a.gu_outcome)]:
  g=load(gp);o=load(op);rows[name]={'axis':g['axis'],'rule':g['rule'],'branching':g['observed_branching'],'clean_oos_2026':o['clean_oos_2026_by_probe_signal_year'],'portfolio_0_50pct':{r:o['portfolio_sizing'][r]['0.50%'] for r in ['1_1','1_2']},'teacher_labels':g['teacher_labels'],'anchor_preserved':g['judgment']['human_anchor_preserved']}
 data={'schema_version':'tradex_ma200_probe_gate_rollup_v1.compare.v1','artifact_role':'authoritative_rollup_decision','review_only':True,'fixed_conditions':{'axes':'each gate tested independently; no composite','execution':'strict episode next-open contract unchanged','years':'2020-2026','clean_oos':'2026','feature_whitelist':'PIT OHLC/MA/support only; future outcome columns excluded'},'baseline_clean_oos_2026':base['clean_oos_2026_by_probe_signal_year'],'challengers':rows,'observed_branching':{k:v['branching'] for k,v in rows.items()},'judgment':{'candidate_local_decision':{'below7':'drop','support020':'hold_diagnostic','gu':'drop'},'session_aggregate_decision':'drop_all_for_adoption','authoritative_rollup_decision':'drop_all_for_adoption','reason':'no independent gate produces positive clean-OOS expectancy or acceptable capacity; support room is the least-bad diagnostic only','architecture_finding':'raw-trigger filtering cannot recover user-labelled missing entries; next branch must generate environment-specific TOP_FAILURE, BREAKDOWN, and RETURN_SELL states'},'not_changed':['CORE','management classifier','MeeMee','ranking','runtime DB']}
 paths=[a.baseline,a.below7_gate,a.below7_outcome,a.support_gate,a.support_outcome,a.gu_gate,a.gu_outcome];data['sources']=[{'path':str(x),'sha256':sha(x)} for x in paths];cp=a.output/'compare.json';cp.write_text(json.dumps(data,ensure_ascii=False,indent=2,allow_nan=False)+'\n',encoding='utf-8');(a.output/'audit.json').write_text(json.dumps({'source_count':len(paths),'all_anchor_preserved':all(v['anchor_preserved'] for v in rows.values()),'future_used':False,'automatic_reflection':False},indent=2)+'\n');(a.output/'_ARTIFACT_COMPLETE.json').write_text(json.dumps({'complete':True,'authoritative':'compare.json','sha256':sha(cp)},indent=2)+'\n');print(json.dumps({'output':str(a.output),'judgment':data['judgment']},ensure_ascii=False))
if __name__=='__main__':main()
