from __future__ import annotations
import glob,json
from datetime import datetime,timezone
from pathlib import Path
import duckdb,pandas as pd
from tradex_leaf_take_profit_signal_quality_v1 import metric
AXIS_ID='leaf20_vol3_breadth_ceiling_2026_oos_v1';DB=Path(r'C:\Users\enish\AppData\Local\MeeMeeScreener-dev\data\stocks.duckdb');OUT=Path(r'G:\Tradex\leaf20_vol3_breadth_ceiling_2026_oos_v1');CEILINGS=(.4,.5,.6,.7,1.0)
def run():
 source=Path(sorted(glob.glob(r'G:\Tradex\chart_entry_geometry_research_v1\*\prehistory_reference_events.csv'))[-1]);x=pd.read_csv(source);x=x[x.shape_leaf==20].copy();x['code']=x.code.astype(str);x['ret']=x.next_open_return
 q="""WITH b AS(SELECT code,date,c,avg(c) over(partition by code order by date rows between 19 preceding and current row) ma20,c/lag(c) over(partition by code order by date)-1 r FROM daily_bars WHERE source='pan'),v AS(SELECT code,date,stddev_samp(r) over(partition by code order by date rows between 19 preceding and current row) vol20,c,ma20 FROM b),br AS(SELECT date,avg(case when c>ma20 then 1.0 else 0.0 end) breadth FROM v GROUP BY date) SELECT v.code,v.date,v.vol20,br.breadth FROM v JOIN br USING(date)"""
 with duckdb.connect(str(DB),read_only=True) as c:f=c.execute(q).fetchdf();f['code']=f.code.astype(str);x=x.merge(f,on=['code','date'],how='left');x=x[x.vol20<.03];dev=x[x.year.between(2019,2025)];reports=[];sets={}
 for ceiling in CEILINGS:
  z=dev[dev.breadth<=ceiling];sets[ceiling]=z;m=metric(z);reports.append({'breadth_ceiling':ceiling,'development_2019_2025':m,'development_gate_pass':m['n']>=200 and m['expectancy']>0 and m['profit_factor']>=1.2 and m['win_rate']>=.45 and m['payoff_ratio']>=1.1})
 valid=[r for r in reports if r['development_gate_pass']];chosen=max(valid,key=lambda r:(r['development_2019_2025']['geometric_mean'],r['development_2019_2025']['expectancy'])) if valid else None;ceiling=chosen['breadth_ceiling'] if chosen else None;oos=x[(x.year==2026)&(x.breadth<=ceiling)].copy() if ceiling else x.iloc[:0];m=metric(oos);positive=bool(m['n']>=5 and m['expectancy']>0 and (m['profit_factor'] or 0)>1 and m['win_rate']>=.45);root=OUT/f"{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}-{AXIS_ID}";root.mkdir(parents=True);oos.to_csv(root/'oos_2026_events.csv',index=False);payload={'schema_version':f'{AXIS_ID}.compare.v1','artifact_role':'authoritative','axis_id':AXIS_ID,'research_phase':'effectiveness_judgment','fixed_evaluation_conditions':{'base_rule':'leaf20 vol20<3% next-open gap<=0 TP8 SL5 H10','changed_axis':'same-day PAN breadth ceiling only','ceilings':CEILINGS,'selection_period':'2019-2025 only','untouched_oos':'2026 complete paths through 2026-07-10','capital_allocation':'not used'},'development_variants':reports,'selection':{'selected_breadth_ceiling':ceiling,'selected':chosen},'oos_2026_metrics':m,'oos_positive_gate_pass':positive,'decision':{'candidate_local_decision':'keep_for_current_selection' if positive else 'drop','authoritative_rollup_decision':'research_only'},'runtime_db_write':False,'production_ranking_changed':False};(root/'compare.json').write_text(json.dumps(payload,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print(root/'compare.json')
if __name__=='__main__':run()
