"""Single-axis PIT gates that promote raw MA200 triggers to probe candidates."""
import argparse,hashlib,json
from pathlib import Path
import numpy as np,pandas as pd

TEACH=[('4208',20260514,'avoid'),('7004',20260317,'avoid'),('7004',20260319,'sell_review'),('7733',20260119,'probe'),('7733',20260126,'take_profit'),('7733',20260210,'reentry'),('7733',20260213,'core'),('3405',20260618,'sell_review'),('3405',20260630,'avoid'),('9531',20260603,'avoid')]
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument('--episodes',required=True);p.add_argument('--daily',required=True);p.add_argument('--axis',choices=['below7_exhaustion','near_support','gu_reject'],required=True);p.add_argument('--support-threshold',type=float,default=.3);p.add_argument('--output',type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=False)
 e=pd.read_parquet(a.episodes);e.code=e.code.astype(str).str.zfill(4);d=pd.read_parquet(a.daily);d.code=d.code.astype(str).str.zfill(4);d=d.sort_values(['code','ymd']).copy();d['prev_c']=d.groupby('code').c.shift();d['gap_pct']=100*(d.o/d.prev_c-1)
 runs=[]
 for _,g in d.groupby('code'):
  b=g.c.lt(g.ma7);runs.append(pd.Series(b.astype(int).groupby((~b).cumsum()).cumsum().values,index=g.index))
 d['below7_run']=pd.concat(runs).sort_index();cols=['ma7','ma20','ma60','ma100','ma200','support20'];s=d[cols].where(d[cols].lt(d.c,axis=0)).max(axis=1);d['nearest_support_room_atr']=(d.c-s)/d.atr14
 f=d[['code','ymd','gap_pct','below7_run','nearest_support_room_atr','pos20','ret5','ret10','dist_ma20_atr','dist_ma60_atr','weekly_close_pos','monthly_high_failure']];z=e.merge(f,left_on=['code','probe_ymd'],right_on=['code','ymd'],how='left',validate='many_to_one')
 if a.axis=='below7_exhaustion':z['gate_pass']=z.below7_run.lt(7)|z.below7_run.isna();rule='reject consecutive closes below MA7 >= 7'
 elif a.axis=='near_support':z['gate_pass']=z.nearest_support_room_atr.gt(a.support_threshold)|z.nearest_support_room_atr.isna();rule=f'reject nearest lower MA/support20 <= {a.support_threshold} ATR'
 else:z['gate_pass']=z.gap_pct.lt(1.0)|z.gap_pct.isna();rule='reject signal-day GU >= 1.0%'
 selected=z[z.gate_pass][e.columns].copy();labels=pd.DataFrame(TEACH,columns=['code','ymd','label']).merge(f,on=['code','ymd'],how='left');labels['gate_pass']=labels.apply(lambda r:(r.below7_run<7 if a.axis=='below7_exhaustion' else r.nearest_support_room_atr>a.support_threshold if a.axis=='near_support' else r.gap_pct<1),axis=1)
 anchor=z[(z.code=='9107')&(z.probe_ymd==20241121)];data={'schema_version':'tradex_ma200_probe_entry_gate_v1.compare.v1','artifact_role':'authoritative_challenger','review_only':True,'axis':a.axis,'rule':rule,'fixed_conditions':{'episode_membership':'existing raw triggers','feature_timing':'probe signal close only, no future data','other_axes':'unchanged','costs':'ignored'},'year_counts':{str(y):{'baseline':int((z.year==y).sum()),'selected':int(((z.year==y)&z.gate_pass).sum()),'removed':int(((z.year==y)&~z.gate_pass).sum())} for y in sorted(z.year.unique())},'teacher_labels':json.loads(labels.to_json(orient='records')),'human_anchor_9107':json.loads(anchor[['code','probe_ymd','gap_pct','below7_run','nearest_support_room_atr','gate_pass']].to_json(orient='records')),'observed_branching':{'baseline':len(z),'selected':len(selected),'removed':int((~z.gate_pass).sum()),'changed_rank_count':int((~z.gate_pass).sum()),'selection_divergence_reason':rule},'judgment':{'decision':'hold_pending_outcome','human_anchor_preserved':bool(len(anchor)) and bool(anchor.gate_pass.all())},'not_changed':['CORE','management classifier','MeeMee','ranking','runtime DB']}
 cp=a.output/'compare.json';cp.write_text(json.dumps(data,ensure_ascii=False,indent=2,allow_nan=False)+'\n',encoding='utf-8');selected.to_parquet(a.output/'selected_episode_ledger.parquet',index=False);z.to_parquet(a.output/'gate_ledger.parquet',index=False);(a.output/'audit.json').write_text(json.dumps({'rows':len(z),'feature_missing':int(z.ymd.isna().sum()),'duplicates':int(z.duplicated(['code','probe_ymd']).sum()),'future_used':False,'episodes_sha256':sha(a.episodes),'daily_sha256':sha(a.daily)},indent=2)+'\n');(a.output/'_ARTIFACT_COMPLETE.json').write_text(json.dumps({'complete':True,'authoritative':'compare.json','sha256':sha(cp)},indent=2)+'\n');print(json.dumps({'axis':a.axis,'output':str(a.output),'branching':data['observed_branching'],'anchor':data['human_anchor_9107'],'teacher':data['teacher_labels']},ensure_ascii=False))
if __name__=='__main__':main()
