from __future__ import annotations
import glob,json
from datetime import datetime,timezone
from pathlib import Path
AXIS_ID='leaf_allocation_goal_rollup_v1';OUT=Path(r'G:\Tradex\leaf_allocation_goal_rollup_v1')
PATTERNS={'rank':r'G:\Tradex\leaf_cap5_rank_axis_v1\*\compare.json','position_cap':r'G:\Tradex\leaf_position_cap_axis_v1\*\compare.json','variable_intensity':r'G:\Tradex\leaf_variable_intensity_axis_v1\*\compare.json','market_breadth':r'G:\Tradex\leaf_market_breadth_axis_v1\*\compare.json','meemee_overlap':r'G:\Tradex\leaf_meemee_overlap_axis_v1\*\compare.json','leaf_baseline':r'G:\Tradex\chart_entry_geometry_research_v1\*\compare.json','benchmark':r'G:\Tradex\leaf_vs_meemee_same_condition_v1\*\compare.json'}
def load(pattern):p=Path(sorted(glob.glob(pattern))[-1]);return p,json.loads(p.read_text(encoding='utf-8'))
def run():
 d={k:load(v) for k,v in PATTERNS.items()};bp,b=d['leaf_baseline'];cap=b['capacity_and_allocation']['budget_10m_cap5_replay'];cmp_p,cmp=d['benchmark'];base_recent=cmp['leaf_rule'];axes={k:{'artifact':str(d[k][0]),'selection':d[k][1].get('selection'),'decision':d[k][1].get('decision'),'target_gate':d[k][1].get('target_gate')} for k in ('rank','position_cap','variable_intensity','market_breadth','meemee_overlap')}
 candidates=[]
 for key in ('rank','position_cap','variable_intensity','market_breadth'):
  obj=d[key][1];sel=obj.get('selected') or {};m=sel.get('metrics') or {};candidates.append({'axis':key,'pnl_2024_2025_yen':m.get('pnl_2024_2025_yen'),'test_pf':(m.get('metrics_by_split') or {}).get('test',{}).get('profit_factor'),'max_dd_yen':m.get('max_realized_drawdown_yen'),'red_year_count':m.get('red_year_count')})
 def passes(c):return c['pnl_2024_2025_yen'] is not None and c['pnl_2024_2025_yen']>4964781 and (c['test_pf'] or 0)>=1.5 and (c['max_dd_yen'] or -1e99)>=-1500000 and c['red_year_count']==0
 audit={'fixed_leaf_contract':True,'rank_axis_completed':True,'position_cap_axis_completed':True,'variable_1_to_5_axis_completed':True,'market_regime_axis_completed':True,'meemee_overlap_axis_completed_with_insufficient_history_label':d['meemee_overlap'][1]['decision']['candidate_local_decision']=='drop_insufficient_train_history','train_only_selection_preserved':True,'out_of_sample_checked':True,'capital_10m_checked':cap['starting_capital_yen']==10000000,'target_rule_found':any(passes(c) for c in candidates),'review_only_boundary':all(not d[k][1].get('runtime_db_write',True) and not d[k][1].get('production_ranking_changed',True) for k in d)}
 payload={'schema_version':f'{AXIS_ID}.rollup.v1','artifact_role':'authoritative','axis_id':AXIS_ID,'research_phase':'effectiveness_judgment','generated_at':datetime.now(timezone.utc).isoformat(),'fixed_target':{'meemee_2024_2025_pnl_yen':4964781,'test_pf_min':1.5,'max_dd_floor_yen':-1500000,'red_year_count':0,'capital_yen':10000000,'slot_yen':2000000},'fixed_leaf_baseline':{'artifact':str(bp),'all_period_cap5':cap,'same_period':base_recent},'axes':axes,'train_selected_candidates':candidates,'completion_audit':audit,'decision':{'candidate_local_decision':'keep' if audit['target_rule_found'] else 'drop_all_allocation_challengers','session_aggregate_decision':'retain_existing_leaf_allocation','authoritative_rollup_decision':'no_tested_leaf_allocation_exceeded_all_target_gates' if not audit['target_rule_found'] else 'adoptable_allocation_found','reason_type':'no train-selected rank, cap, variable-intensity, or breadth policy exceeded MeeMee profit while preserving PF, drawdown, and annual gates'},'scope_statement':'No qualifying allocation was found among the predeclared one-axis policies. MeeMee overlap could not be train-selected because ranking history begins in 2024 and was not silently substituted.','runtime_db_write':False,'production_ranking_changed':False,'silent_fallback_used':False}
 root=OUT/f"{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}-{AXIS_ID}";root.mkdir(parents=True);p=root/'session_leaderboard_rollup.json';p.write_text(json.dumps(payload,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print(p)
if __name__=='__main__':run()
