"""Evaluate PIT prior-20-low break as a veto for human SELL / model AVOID disagreements."""
import argparse,hashlib,json
from pathlib import Path
import duckdb,pandas as pd

def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def stats(f):
 x=f[f.status.eq('complete')];v=x.return_fixed3_pct;gain=v[v>0].sum();loss=-v[v<0].sum()
 return {'n':len(f),'D':int(x.outcome_fixed3.eq('D').sum()),'R':int(x.outcome_fixed3.eq('R').sum()),'N':int(x.outcome_fixed3.eq('N').sum()),'D_rate':float(x.outcome_fixed3.eq('D').mean()) if len(x) else None,'R_rate':float(x.outcome_fixed3.eq('R').mean()) if len(x) else None,'mean_fixed3_pct':float(v.mean()) if len(v) else None,'profit_factor':None if loss==0 else float(gain/loss),'max_loss_pct':float(v.min()) if len(v) else None}
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--board',type=Path,required=True);ap.add_argument('--outcomes',type=Path,required=True);ap.add_argument('--db',type=Path,required=True);ap.add_argument('--output',type=Path,required=True);a=ap.parse_args();a.output.mkdir(parents=True,exist_ok=False)
 board=pd.read_parquet(a.board);out=pd.read_parquet(a.outcomes);d=out.merge(board[['case_id','c','l','support_break']],on='case_id',validate='one_to_one');codes=d.code.astype(str).str.zfill(4).unique().tolist();con=duckdb.connect(str(a.db),read_only=True);p=con.execute("select code,strftime(to_timestamp(date),'%Y%m%d')::integer ymd,h,l,c from daily_bars where code in (select unnest(?)) order by code,date",[codes]).fetchdf();p.code=p.code.astype(str).str.zfill(4)
 rows=[]
 for r in d.itertuples():
  g=p[p.code.eq(r.code)].reset_index(drop=True);hit=g.index[g.ymd.eq(int(r.ymd))]
  if len(hit)!=1:raise RuntimeError(f'missing {r.code} {r.ymd}')
  i=int(hit[0]);prior=g.iloc[:i];through=g.iloc[:i+1];prev=through.c.shift(1);tr=pd.concat([through.h-through.l,(through.h-prev).abs(),(through.l-prev).abs()],axis=1).max(axis=1);atr=float(tr.tail(14).mean());pl20=float(prior.tail(20).l.min());pl60=float(prior.tail(60).l.min());rows.append({'case_id':r.case_id,'atr14':atr,'prior_low20':pl20,'prior_low60':pl60,'close_break_prior_low20':bool(r.c<pl20),'intraday_break_prior_low20':bool(r.l<pl20),'close_vs_prior_low20_atr':(r.c-pl20)/atr,'close_break_prior_low60':bool(r.c<pl60)})
 data=d.merge(pd.DataFrame(rows),on='case_id',validate='one_to_one');lane=data[data.human_direction.eq('SELL')&data.model_direction.eq('NO_SELL')];gate=lane[lane.intraday_break_prior_low20];allhuman=data[data.human_direction.eq('SELL')];allgate=allhuman[allhuman.intraday_break_prior_low20];lb,lg,ab,ag=stats(lane),stats(gate),stats(allhuman),stats(allgate);dret=None if lb['D']==0 else lg['D']/lb['D'];keep=lg['R_rate']<lb['R_rate'] and lg['max_loss_pct']>lb['max_loss_pct'] and dret>=.7
 lp=a.output/'support_break_diagnostic_ledger.parquet';data.to_parquet(lp,index=False);result={'schema_version':'tradex_human_sell_model_avoid_support_break_axis_v1.compare.v1','artifact_role':'authoritative_single_axis_discovery','review_only':True,'fixed_conditions':{'scope':'human SELL and model AVOID disagreement lane only','axis':'signal low breaks prior 20-session low','prior_low_excludes_signal_day':True,'execution':'next_session_open','horizon_sessions':5,'weekly_inputs':[],'costs':'ignored'},'disagreement_baseline':lb,'disagreement_require_break':lg,'all_human_sell_diagnostic':ab,'all_human_sell_if_misapplied':ag,'observed_branching':{'removed':len(lane)-len(gate),'removed_outcomes':{str(k):int(v) for k,v in lane[~lane.intraday_break_prior_low20].outcome_fixed3.value_counts().items()},'D_retention':dret,'R_removed':lb['R']-lg['R']},'judgment':{'candidate_local_decision':'keep_discovery_challenger' if keep else 'drop','authoritative_rollup_decision':'hold_pending_unused_validation' if keep else 'drop','keep_conditions':{'R_rate_strictly_lower':lg['R_rate']<lb['R_rate'],'max_loss_strictly_better':lg['max_loss_pct']>lb['max_loss_pct'],'D_retention_ge_0_70':dret>=.7},'misapplication_warning':'across all human SELL it retains only 2 of 5 D'},'not_changed':['MeeMee','ranking','runtime DB','production trading logic']};cp=a.output/'compare.json';cp.write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');audit={'board_sha256':sha(a.board),'outcomes_sha256':sha(a.outcomes),'db_path':str(a.db.resolve()),'db_read_only':True,'rows':len(data),'weekly_columns_used':[],'future_selection_columns_used':[],'ledger_sha256':sha(lp)};(a.output/'audit.json').write_text(json.dumps(audit,indent=2)+'\n',encoding='utf-8');(a.output/'_ARTIFACT_COMPLETE.json').write_text(json.dumps({'complete':True,'authoritative':'compare.json','sha256':sha(cp)},indent=2)+'\n',encoding='utf-8');print(json.dumps({'output':str(a.output),'baseline':lb,'gate':lg,'all_human_misapply':ag,'judgment':result['judgment']},ensure_ascii=False,indent=2))
if __name__=='__main__':main()
