import argparse,hashlib,json
from pathlib import Path
import pandas as pd
YEARS=range(2021,2026)
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def rates(x):
 n=len(x);return {'n':n,'down_first':int(x.outcome.eq('down_first').sum()),'rebound_first':int(x.outcome.eq('rebound_first').sum()),'neutral_no_hit':int(x.outcome.eq('neutral_no_hit').sum()),'down_first_pct':None if not n else 100*x.outcome.eq('down_first').mean(),'rebound_first_pct':None if not n else 100*x.outcome.eq('rebound_first').mean()}
def main():
 p=argparse.ArgumentParser();p.add_argument('--sequence',type=Path,required=True);p.add_argument('--daily',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=True)
 d=pd.read_parquet(a.daily,columns=['code','ymd','c','ma60']);d.code=d.code.astype(str).str.zfill(4);d=d.sort_values(['code','ymd']);above=d.c.gt(d.ma60);blocks=above.ne(above.groupby(d.code).shift()).groupby(d.code).cumsum();d['above_ma60_run']=above.groupby([d.code,blocks]).cumcount()+1;d.loc[~above,'above_ma60_run']=0
 s=pd.read_parquet(a.sequence);s.code=s.code.astype(str).str.zfill(4);x=s[s.gd_ymd.notna()&s.ma20_rebreak_ymd.notna()&(s.ma20_rebreak_ymd>s.gd_ymd)&s.weak_rebound&(s.max_consecutive_closes_above_ma7<7)].copy();x['action_ymd']=x.ma20_rebreak_ymd.astype(int);x=x.sort_values('erasure_ymd').drop_duplicates(['code','action_ymd'],keep='last');x['year']=x.action_ymd.astype(str).str[:4].astype(int);x['outcome']=x.ma20_rebreak_outcome_fixed3_h5;x=x.merge(d[['code','ymd','above_ma60_run']],left_on=['code','erasure_ymd'],right_on=['code','ymd'],how='left',validate='one_to_one');x['gate_pass']=x.above_ma60_run.ge(60)
 base={str(y):rates(x[x.year.eq(y)]) for y in YEARS};ch={str(y):rates(x[x.year.eq(y)&x.gate_pass]) for y in YEARS};direction=all(v['down_first']>v['rebound_first'] for v in ch.values());breadth=all(v['n']>=30 for v in ch.values());z=x[(x.code.eq('9962'))&x.action_ymd.eq(20260713)][['erasure_ymd','above_ma60_run','gate_pass','outcome']];anchor=z.where(pd.notna(z),None).to_dict('records')
 data={'schema_version':'tradex_weak_rebound_ma60_run_oos_v1.compare.v1','artifact_role':'authoritative','review_only':True,'axis':'mature high-zone duration before weak-rebound sequence','fixed_conditions':{'base_branch':'WEAK_REBOUND_MA20_REBREAK_CORE normalized','single_gate':'consecutive closes above MA60 at erasure >=60','threshold_source':'human 9962 annotation; no sweep','years':list(YEARS),'minimum_each_year':30,'outcome':'inherited exact fixed3 h5'},'baseline_results':base,'challenger_results':ch,'human_anchor_9962':anchor,'observed_branching':{'base_events':len(x),'retained_events':int(x.gate_pass.sum()),'removed_events':int((~x.gate_pass).sum()),'changed_rank_count':int((~x.gate_pass).sum()),'selection_divergence_reason':'the same breakdown sequence is separated by prior time spent continuously above MA60'},'judgment':{'decision':'keep' if direction and breadth else 'hold' if direction else 'drop','direction_pass_all_years':direction,'breadth_pass':breadth,'anchor_preserved':len(anchor)==1,'reason':'adopt only with all-year direction, breadth, and anchor preservation'},'not_changed':['GD','rebound candles','monthly classifier','other branches','MeeMee','ranking','runtime DB']}
 cp=a.output/'compare.json';cp.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');x.to_parquet(a.output/'ma60_run_ledger.parquet',index=False);(a.output/'audit.json').write_text(json.dumps({'duplicates':int(x.duplicated(['code','action_ymd']).sum()),'missing_run':int(x.above_ma60_run.isna().sum()),'future_used_for_selection':False,'input_sha256':{'sequence':sha(a.sequence),'daily':sha(a.daily)}},indent=2)+'\n',encoding='utf-8');(a.output/'_ARTIFACT_COMPLETE.json').write_text(json.dumps({'complete':True,'authoritative':'compare.json','sha256':sha(cp)},indent=2)+'\n',encoding='utf-8');print(json.dumps({'output':str(a.output),'challenger':ch,'anchor':anchor,'judgment':data['judgment']},ensure_ascii=False,indent=2))
if __name__=='__main__':main()
