from __future__ import annotations
import argparse
from datetime import datetime,timezone
from pathlib import Path
import numpy as np,pandas as pd
from scripts.tradex_early_signal_first_detect_v1 import load_source,_metrics,_branching
from scripts.tradex_shallow_high_zone_universe_repair_v1 import attach_gap_outcomes,no_reentry_sessions,_sha,_write,extra_metrics
AXIS_ID='tradex_buy_cross_sectional_momentum_v1';OUT=Path(r'G:\Tradex\tradex_buy_cross_sectional_momentum_v1');VARIANTS=('rel_ret20','close_ret60','blend');PERIODS={'train':(20240101,20241231),'validation':(20250101,20251231),'shadow':(20260101,20261231)}
def score(x:pd.DataFrame,variant:str)->pd.DataFrame:
 z=x.copy()
 if variant=='blend':
  def std(s):return (s-s.mean())/s.std(ddof=0) if s.std(ddof=0)>0 else s*0
  z['score']=z.groupby('signal_ymd').rel_ret20.transform(std)+z.groupby('signal_ymd').close_ret60.transform(std)-z.high20_dist.abs()
 else:z['score']=pd.to_numeric(z[variant],errors='coerce')
 z['score']=z.score.replace([np.inf,-np.inf],np.nan).fillna(-99);z=z.sort_values(['signal_ymd','score','code'],ascending=[True,False,True]);z['rank']=z.groupby('signal_ymd').cumcount()+1;z['percentile']=1-(z['rank']-1)/z.groupby('signal_ymd').code.transform('size');z['top10']=z['rank']<=10;z['side']='BUY';return z
def top1(s:pd.DataFrame,cal:list[int],rank_col:str)->pd.DataFrame:
 q=s[s.trade_return_h10.notna()].sort_values(['signal_ymd',rank_col,'code']).groupby('signal_ymd',as_index=False).head(1).reset_index(drop=True);return no_reentry_sessions(q,cal,rank_col)
def generate(db:Path,out:Path)->Path:
 f,b,meta=load_source(db);r=meta['rankings'];r=r[(r.dir=='up')&r['rank'].le(10)].rename(columns={'rank':'baseline_rank'});need=f[['signal_ymd','code','rel_ret20','close_ret60','high20_dist']];base=attach_gap_outcomes(need.assign(side='BUY'),b,'BUY') if False else attach_gap_outcomes(need,b);base=base[base.signal_ymd>=20240101];cal=sorted(base.signal_ymd.unique());td=sum(d<=20241231 for d in cal);variants=[];sets={}
 for v in VARIANTS:
  s=score(base,v);e=top1(s,cal,'rank');m=_metrics(e[e.signal_ymd<=20241231],td);variants.append({'priority':v,'train_metrics':m});sets[v]=(s,e)
 ok=[v for v in variants if (v['train_metrics']['expectancy'] or 0)>0 and v['train_metrics']['profit_factor'] is not None and v['train_metrics']['signals_per_week']>=1];pool=ok or [v for v in variants if v['train_metrics']['profit_factor'] is not None];chosen=max(pool,key=lambda v:(v['train_metrics']['profit_factor'],v['train_metrics']['expectancy']));chosen['train_pf_gate_pass']=(chosen['train_metrics']['profit_factor'] or 0)>=1.3;s,e=sets[chosen['priority']];s['split']=np.select([s.signal_ymd<20250101,s.signal_ymd<20260101],['train','validation'],default='shadow');mm=r.merge(s[['signal_ymd','code','trade_return_h10','exit_day_h10','target_before_stop20','realized_mover20']],on=['signal_ymd','code'],how='left');mm=top1(mm,cal,'baseline_rank');latest=int(f.signal_ymd.max());periods={**PERIODS,'shadow':(20260101,latest)};metrics={};gates={};branch={};coverage={}
 for split,(a,z) in periods.items():
  days=sum(a<=d<=z for d in cal);ch=e[e.signal_ymd.between(a,z)];bl=mm[mm.signal_ymd.between(a,z)];allx=s[s.signal_ymd.between(a,z)&s.trade_return_h10.notna()];cm={**_metrics(ch,days),**extra_metrics(ch,allx)};bm={**_metrics(bl,days),**extra_metrics(bl,allx)};metrics[split]={'momentum_top1':cm,'meemee_buy_same_days_top1':bm};gates[split]={'pf_ge_1_30':(cm['profit_factor'] or 0)>=1.3,'expectancy_positive':(cm['expectancy'] or 0)>0,'frequency_ge_1_week':cm['signals_per_week']>=1,'pf_improves':cm['profit_factor'] is not None and bm['profit_factor'] is not None and cm['profit_factor']>bm['profit_factor'],'expectancy_improves':cm['expectancy'] is not None and bm['expectancy'] is not None and cm['expectancy']>bm['expectancy'],'cvar_non_degrade':cm['cvar10'] is not None and bm['cvar10'] is not None and cm['cvar10']>=bm['cvar10'],'dd_non_degrade':cm['max_drawdown'] is not None and bm['max_drawdown'] is not None and cm['max_drawdown']>=bm['max_drawdown']};branch[split]=_branching(s[s.top10],r.assign(side='BUY'),'BUY',a,z);cnt=s[s.signal_ymd.between(a,z)].groupby('signal_ymd').size();coverage[split]={'days':len(cnt),'min_ranked':int(cnt.min()),'all_days_ranked':bool(cnt.gt(0).all())}
 root=out/f"{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}-{AXIS_ID}";root.mkdir(parents=True,exist_ok=False);s.to_parquet(root/'all_symbol_daily_buy_scores.parquet',index=False);e.to_parquet(root/'momentum_entry_ledger.parquet',index=False);mm.to_parquet(root/'meemee_buy_baseline_ledger.parquet',index=False);keep=bool(chosen['train_pf_gate_pass'] and all(all(gates[x].values()) for x in ('validation','shadow')));payload={'schema_version':AXIS_ID+'.compare.v1','artifact_role':'authoritative','research_phase':'effectiveness_judgment','fixed_evaluation_conditions':{'priorities_train_only':['rel_ret20','close_ret60','daily z(rel_ret20)+z(close_ret60)-abs(high20_dist)'],'ranking':'all historical feature-covered PAN daily BUY rank; top1 entry; no candidate suppression','entry_gate':'none; selected priority top1 only; no threshold search','entry_exit':'next-open TP8/SL5/H10/10bp; gap-through actual open; reentry prohibited','baseline':'MeeMee BUY top1 same days','survivorship_filter':False,'fallback':False},'source_artifacts':[{'path':str(db),'sha256':_sha(db)}],'source_coverage':meta['coverage'],'train_variants':variants,'selected_variant':chosen,'metrics':metrics,'adoption_gates':gates,'branching':branch,'rank_coverage':coverage,'decision':{'candidate_local_decision':'keep' if keep else 'drop','authoritative_rollup_decision':'review_only'},'shadow_tuning_used':False,'silent_fallback_used':False,'runtime_db_write':False,'production_ranking_changed':False,'meemee_changed':False};p=root/'compare.json';_write(p,payload);_write(root/'_ARTIFACT_COMPLETE.json',{'complete':True,'compare':str(p)});return p
def main():
 p=argparse.ArgumentParser();p.add_argument('--db',type=Path,required=True);p.add_argument('--out',type=Path,default=OUT);a=p.parse_args();print(generate(a.db,a.out))
if __name__=='__main__':main()
