"""Integrate separately reviewed MA200 ADD points into action decisions."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
import pandas as pd

def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def cell(z):
    n=len(z);d=int(z.add_outcome_fixed3_h5.eq('down_first').sum());r=int(z.add_outcome_fixed3_h5.eq('rebound_first').sum())
    return {'n':n,'down_first':d,'rebound_first':r,'neutral':n-d-r}

def main():
    p=argparse.ArgumentParser();p.add_argument('--episodes',type=Path,required=True);p.add_argument('--daily',type=Path,required=True);p.add_argument('--output',type=Path,required=True);p.add_argument('--years',type=int,nargs='+',default=[2023,2024,2025]);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=False);years=tuple(a.years)
    x=pd.read_parquet(a.episodes);x=x[x.add_ymd.notna()].copy();x.code=x.code.astype(str).str.zfill(4);x.core_ymd=x.core_ymd.astype(int);x.add_ymd=x.add_ymd.astype(int);x['action_year']=x.add_ymd//10000;x=x[x.action_year.isin(years)].copy()
    cols=['code','ymd','o','l','c','atr14','ma60','ma100','ma200','support20','dist_ma20_atr','lower_wick_ratio']
    d=pd.read_parquet(a.daily,columns=cols);d.code=d.code.astype(str).str.zfill(4);d=d.sort_values(['code','ymd']);d['prior_close']=d.groupby('code',sort=False).c.shift(1);hist={c:g.set_index('ymd') for c,g in d.groupby('code',sort=False)}
    rows=[]
    for r in x.itertuples(index=False):
        g=hist[r.code];probe=float(g.loc[int(r.probe_ymd),'c']);core=float(g.loc[r.core_ymd,'c']);q=g.loc[r.add_ymd];prior_low=float(g.loc[(g.index>=r.core_ymd)&(g.index<r.add_ymd),'l'].min())
        gap_pct=100*(float(q.o)/float(q.prior_close)-1);gap_point=2 if gap_pct<=-2 else (1 if gap_pct<=-1 else 0);break_depth=(prior_low-float(q.l))/float(q.atr14);low_break_point=int(break_depth>=1)
        support_room=(float(q.c)-float(q.support20))/float(q.atr14);held_support=bool(0<=support_room<=.35 and float(q.l)>=float(q.support20));long_ma_span=(max(float(q.ma60),float(q.ma100),float(q.ma200))-min(float(q.ma60),float(q.ma100),float(q.ma200)))/float(q.atr14);long_ma_cluster=bool(long_ma_span<=1.0);raw_score=gap_point+low_break_point-int(held_support)-int(long_ma_cluster)
        entry11=(probe+core)/2;entry12=(probe+2*core)/3;profit11=100*(entry11-float(q.c))/entry11;profit12=100*(entry12-float(q.c))/entry12
        target_profit=bool(profit11>=3 and profit12>=3);high_profit=bool(profit11>=6 and profit12>=6);weak_target_profit=bool(raw_score<2 and target_profit);extreme=bool(float(q.dist_ma20_atr)<=-4 and target_profit);lower_wick_exhaustion=bool(raw_score>=3 and float(q.lower_wick_ratio)>=.30)
        action='TAKE_PROFIT' if (high_profit or weak_target_profit or extreme) else ('HOLD' if lower_wick_exhaustion else ('ADD' if raw_score>=2 else 'HOLD'))
        rows.append({'code':r.code,'probe_ymd':int(r.probe_ymd),'core_ymd':r.core_ymd,'add_ymd':r.add_ymd,'probe_year':int(r.year),'action_year':int(r.action_year),'gap_pct':gap_pct,'gap_point':gap_point,'running_low_break_depth_atr':break_depth,'low_break_point':low_break_point,'prior_support_room_atr':support_room,'held_support_penalty':held_support,'long_ma_span_atr':long_ma_span,'long_ma_cluster_penalty':long_ma_cluster,'raw_score':raw_score,'preadd_profit_1_1_pct':profit11,'preadd_profit_1_2_pct':profit12,'target_profit_reached_both_ratios':target_profit,'weak_score_target_take_profit':weak_target_profit,'high_profit_take_profit':high_profit,'dist_ma20_atr':float(q.dist_ma20_atr),'lower_wick_ratio':float(q.lower_wick_ratio),'extreme_profit_override':extreme,'lower_wick_exhaustion_hold':lower_wick_exhaustion,'action':action,'add_outcome_fixed3_h5':r.add_outcome_fixed3_h5})
    z=pd.DataFrame(rows);results={str(y):{act:cell(z[(z.action_year==y)&(z.action==act)]) for act in ['ADD','HOLD','TAKE_PROFIT']} for y in years};anchor=z[(z.code=='9107')&(z.add_ymd==20241126)].to_dict('records')
    active_add_years=[str(y) for y in years if results[str(y)]['ADD']['n']>0];add_total=sum(results[str(y)]['ADD']['n'] for y in years);add_pass=bool(active_add_years) and all(results[y]['ADD']['down_first']>results[y]['ADD']['rebound_first'] for y in active_add_years)
    external=years != (2023,2024,2025)
    ext_decision='hold_no_external_add' if add_total==0 else ('keep_external' if add_pass else 'drop_external')
    data={'schema_version':'tradex_ma200_add_hold_profit_classifier_v1.compare.v1','artifact_role':'authoritative_external_validation' if external else 'authoritative_retrospective_candidate','review_only':True,'fixed_conditions':{'score':'gap point 0/1/2 + running-low break >=1ATR point - held prior-support penalty - long MA cluster penalty','long_ma_cluster_penalty':'(max(MA60,MA100,MA200)-min)/ATR14 <= 1.0','TAKE_PROFIT':'profit >=6% under both ratios; or raw score<2 with profit >=3% under both ratios; or dist MA20 <= -4ATR with profit >=3%','profit_basis':'3% is the fixed outcome unit; weak continuation plus achieved target realizes profit instead of HOLD','HOLD':'raw score <2 without achieved target, or raw score>=3 and lower wick>=30%','ADD':'raw score>=2 unless override','execution':'action at ADD-candidate close; costs ignored','year_attribution':'calendar year of ADD action date, not probe date','years':list(years),'research_design':'locked external validation' if external else 'same-period retrospective integration; must be locked before external validation'},'year_results':results,'human_anchor_9107':anchor,'observed_branching':{'actions':z.action.value_counts().to_dict(),'changed_rank_count':int((z.action!='ADD').sum()),'selection_divergence_reason':'weak continuation, held support, long-MA congestion, exhaustion wick, or achieved existing profit changes ADD into HOLD/TAKE_PROFIT'},'judgment':{'decision':ext_decision if external else 'hold_locked_candidate','external_add_total':add_total if external else None,'active_add_years':active_add_years,'add_down_exceeds_rebound_active_years':add_pass,'human_anchor_action_add':None if external else bool(anchor) and anchor[0]['action']=='ADD','reason':('no external ADD survived; false-add avoidance observed but positive ADD effectiveness unproven' if add_total==0 else 'locked rules; active ADD years require down-first dominance') if external else 'lock for external validation; same-period integration and thin yearly ADD cells prohibit keep'},'not_changed':['source detector','monthly environment','position execution in MeeMee','ranking','runtime DB']}
    cp=a.output/'compare.json';cp.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');z.to_parquet(a.output/'action_classifier_ledger.parquet',index=False)
    (a.output/'audit.json').write_text(json.dumps({'rows':len(z),'duplicates':int(z.duplicated(['code','probe_ymd']).sum()),'future_used_for_action':False,'episodes_sha256':sha(a.episodes),'daily_sha256':sha(a.daily)},indent=2)+'\n',encoding='utf-8');(a.output/'_ARTIFACT_COMPLETE.json').write_text(json.dumps({'complete':True,'authoritative':'compare.json','sha256':sha(cp)},indent=2)+'\n',encoding='utf-8')
    print(json.dumps({'output':str(a.output),'results':results,'actions':data['observed_branching']['actions'],'anchor':anchor,'judgment':data['judgment']},ensure_ascii=False,indent=2))
if __name__=='__main__':main()
