from __future__ import annotations
import argparse,json
from pathlib import Path
import pandas as pd
H=[2,3,4,5]
def met(g):return {"n":int(len(g)),"codes":int(g.code.nunique()),"mean_return_pct":float(g.ret.mean()),"median_return_pct":float(g.ret.median()),"win_rate":float(g.ret.gt(0).mean()),"severe_loss5_rate":float(g.ret.le(-5).mean()),"p10_return_pct":float(g.ret.quantile(.1))}
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--paths",required=True);ap.add_argument("--output",required=True);a=ap.parse_args();out=Path(a.output);out.mkdir(parents=True,exist_ok=False);x=pd.read_parquet(a.paths);x=x[x.buy_family.eq("急落反発")].copy();rows=[];yrs=[];ds=[];i=.25
 for h in H:
  q=x.copy();im=q.entry_day_path.eq("即上昇");stall=q.entry_day_path.eq("失速");exitc=q[f"c{h}"];q["ret"]=100*i*(exitc/q.o1-1);q.loc[im,"ret"]=100*(i*(exitc[im]/q.loc[im,"o1"]-1)+(1-i)*(exitc[im]/q.loc[im,"o2"]-1));q.loc[stall,"ret"]=100*i*(q.loc[stall,"o2"]/q.loc[stall,"o1"]-1);q["holding_days"]=h;ds.append(q)
  for p,g in q.groupby("period"):rows.append({"period":p,"holding_days":h,**met(g)})
  for y,g in q.assign(year=q.ymd//10000).groupby("year"):yrs.append({"year":int(y),"holding_days":h,**met(g)})
 d=pd.concat(ds);m=pd.DataFrame(rows);yr=pd.DataFrame(yrs);d.to_parquet(out/"holding_period_ledger.parquet",index=False);m.to_parquet(out/"holding_period_metrics.parquet",index=False);yr.to_parquet(out/"holding_period_yearly_metrics.parquet",index=False);dev=m[m.period.eq("development")];ok=dev[(dev.mean_return_pct>0)&(dev.severe_loss5_rate<=.1)];selected=None if ok.empty else int(ok.sort_values(["mean_return_pct","severe_loss5_rate"],ascending=[False,True]).iloc[0].holding_days);v=m[(m.period.eq("validation"))&(m.holding_days.eq(selected))] if selected else m.iloc[0:0];yy=yr[(yr.year>=2024)&yr.holding_days.eq(selected)] if selected else yr.iloc[0:0];checks={"selected_on_development":selected is not None,"validation_positive":bool(len(v)==1 and v.iloc[0].mean_return_pct>0),"validation_tail_le10":bool(len(v)==1 and v.iloc[0].severe_loss5_rate<=.1),"all_validation_years_positive":bool(len(yy)==3 and (yy.mean_return_pct>0).all())};keep=all(checks.values())
 res={"schema_version":"tradex_long_rebound_holding_period_v1.compare.v1","artifact_role":"authoritative_long_rebound_holding_period","review_only":True,"fixed_conditions":{"family":"急落反発","entry":"next open 25%","add":"immediate rise following open to 100%","stall":"following open exit","flat_other":"25% only","holding_candidates":H,"selected_on":"development only","costs":"ignored"},"authoritative_result":{"selected_holding_days":selected,"period_metrics":m.to_dict("records"),"validation":v.to_dict("records"),"validation_years":yy.to_dict("records"),"gate_checks":checks},"judgment":{"candidate_local_decision":"keep" if keep else "hold","session_aggregate_decision":"keep_rebound_holding" if keep else "hold_rebound_holding","authoritative_rollup_decision":"keep_long_rebound_holding_period_v1_review_only" if keep else "hold_no_year_stable_holding_period","reason_type":"positive_yearly_tail_holding_gates"},"not_changed":["family","entry","size","path rules","MeeMee","ranking","runtime DB","production logic"]}
 (out/"compare.json").write_text(json.dumps(res,ensure_ascii=False,indent=2),encoding="utf-8");(out/"_ARTIFACT_COMPLETE.json").write_text(json.dumps({"complete":True,"authoritative":"compare.json"}));print(json.dumps(res["authoritative_result"],ensure_ascii=False))
if __name__=="__main__":main()
